### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by xiaomengzaici** [2dust/clashN#1]
我安装了.net 6.0.3依旧提示我缺少该部件，重启后依旧如此，win11系统

**Comment by Cost11** [comment]
不光windows11 Windows10也是这样

**Comment by fyhzc** [comment]
win10 64位下，安装完dotnet-runtime-6.0.3-win-x64，不能运行

**Comment by MetaCubeX** [comment]
你好，该下的都下了，就是运行不来。

**Comment by Lemonawa** [comment]
+1

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.0
已经修复，请重新下载

**Comment by hjp070928** [comment]
> https://github.com/2dust/clashN/releases/tag/1.0 已经修复，请重新下载

还是打不开

**Comment by fyhzc** [comment]
很好，成功了。

**Comment by Cost11** [comment]
我的能打开了 但是网络不通 报错error: dial tcp4 40.91.78.9:443: i/o timeout  有谁知道怎么解决吗

**Comment by Cost11** [comment]
> 很好，成功了。

你是win10 吗 我的网络一直不通

**Comment by fyhzc** [comment]
是的，我成功了
![无标题](https://user-images.githubusercontent.com/26890748/161411058-eddac07a-fea2-4db5-9076-7e2d0550b2fd.png)
。

**Comment by Cost11** [comment]
> 是的，我成功了 ![无标题](https://user-images.githubusercontent.com/26890748/161411058-eddac07a-fea2-4db5-9076-7e2d0550b2fd.png) 。

你是机场还是自建 什么协议？

**Comment by fyhzc** [comment]
订阅的

**Comment by Cost11** [comment]
> 订阅的

唉 好吧

**Comment by Cost11** [comment]
> > 是的，我成功了 ![无标题](https://user-images.githubusercontent.com/26890748/161411058-eddac07a-fea2-4db5-9076-7e2d0550b2fd.png) 。
> 
> 你是机场还是自建 什么协议？

你这图片怎么上传的 我找了半天没找到入口

**Comment by fyhzc** [comment]
Attach files by dragging & dropping, selecting or pasting them.
通过拖放、选择或粘贴来附加文件。

**Comment by 2dust** [comment]
> Attach files by dragging & dropping, selecting or pasting them. 通过拖放、选择或粘贴来附加文件。

有建议请单独提交issue
