### ISSUE TITLE
添加服务器链接转换功能

### ISSUE THREAD

**Issue by Lemonawa** [2dust/clashN#10]
在软件内部，将形如`vmess://absdsdsdsds`的链接转换为Clash版本的配置文件

**Comment by 2dust** [comment]
clash的配置文件是高度耦合的
即使导入了多个节点配置，也会因为clash的组和路由等需要配置无法很方便的使用。
所以clashN目前暂时只支持clash自有的配置文件使用。

等基本功能稳定了，可能会考虑增加单个节点，组和路由的图形界面维护

**Comment by 2dust** [comment]
clash的配置文件是高度耦合的
即使导入了多个节点配置，也会因为clash的组和路由等需要配置无法很方便的使用。
所以clashN目前暂时只支持clash自有的配置文件使用。

如果您有好的建议可以提出来

**Comment by fyhzc** [comment]
他是想要clash.net 那样的功能

**Comment by fyhzc** [comment]
可惜clash.net到1.28版，作者跑了，删库了，挂逼了

**Comment by Lemonawa** [comment]
> 他是想要clash.net 那样的功能

确实，~~每次都转换烦死~~

**Comment by Lemonawa** [comment]
> 他是想要clash.net 那样的功能

确实，~~每次都转换烦死~~

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.3

**Comment by Lemonawa** [comment]
> https://github.com/2dust/clashN/releases/tag/1.3

Awesome
