### ISSUE TITLE
关于开机启动 tun 的问题提个小建议

### ISSUE THREAD

**Issue by alexchanchan** [2dust/clashN#100]
目前开机启动是无法启动tun模式，是否可以参考cfw的思路安装一个服务，由服务的进程来启动clash内核来实现。

**Comment by 2dust** [comment]
用服务略显复杂
还有一个可行的方案是使用windows计划任务：以管理员权限开机启动可以实现

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/issues/98#issuecomment-1229160822
