### ISSUE TITLE
PING值虚高和节点地址

### ISSUE THREAD

**Issue by 332sdasf** [2dust/clashN#102]
有些机场用clashn ping的话延迟虚高
![image](https://user-images.githubusercontent.com/70708328/186406433-41bd4f69-d01c-476d-b6f5-1d4d5de94ec8.png)
但用clash就没问题
![image](https://user-images.githubusercontent.com/70708328/186406501-01a7254e-efb6-419f-8c6d-a5dd01c80025.png)
所以还请dalao把tcping域名改成和CFW一样的：
![image](https://user-images.githubusercontent.com/70708328/186406181-0d1b122e-ccf6-4dd5-be6b-861001234329.png)

**Comment by 332sdasf** [comment]
不知怎的 想让大佬把节点地址 端口加上 （也许是我想让界面看起来更像V2rayn一点？？？）![image](https://user-images.githubusercontent.com/70708328/186449252-e724ace4-a9bc-4a4e-9ef5-8a35d17b7030.png)

**Comment by 2dust** [comment]
调用的core的API ` /proxies/:name/delay` 
不知要如何改进？

**Comment by TooYoungTooSimp** [comment]
> 调用的core的API ` /proxies/:name/delay` 不知要如何改进？

![image](https://user-images.githubusercontent.com/6648049/190321961-60b7eb73-ef40-4285-aa96-bed05d1989c5.png)
有一个url参数，传入网址需要做urlencode

**Comment by 2dust** [comment]
url参数使用哪个比较合适？

**Comment by 2dust** [comment]
目前用的是 "https://www.google.com/generate_204"
