### ISSUE TITLE
用了clashN，自动配置文件代理没反应，同时outlook连接不了

### ISSUE THREAD

**Issue by Tdoscar** [2dust/clashN#104]
1 点击自动配置文件代理没反应，需要进入网络和internet中的代理，手动把使用代理服务器打开就能使用。
2 开了clashN后，outlook连接不上服务器，原版的clash是可以的。

**Comment by 2dust** [comment]
1.没有日志详情，无法判断
2.是否已经解除UWP回环？

**Comment by LOUIS-rw** [comment]
Mr.[2dust]，可以在下次更新直接实现TUN模式吗？

**Comment by 2dust** [comment]
> Mr.[2dust]，可以在下次更新直接实现TUN模式吗？

tun模式已经支持

**Comment by Tdoscar** [comment]
> 1.没有日志详情，无法判断 2.是否已经解除UWP回环？

非常感谢出口这么好用的软件 。outlook问题已经搞定，是配置文件问题。 
但是系统代理选择清除系统代理后，再选回自动配置系统代理后，连接不上。还是需要进入网络和internet中的代理，手动把使用代理服务器打开就能使用，而且里面的代理端口也需要手动更改。我用的是WIN11，原版clash软件却没这个问题。 不知道是哪个软件冲突了，还是设置有问题？

**Comment by 2dust** [comment]
1. 检查是否有其他软件修改了系统代理
2. clashN使用管理员启动

**Comment by Tdoscar** [comment]
> 
非常感谢回复，目前电脑只安装了Clash, ClashN，V2rayN，已经是管理员启动了。所以不太清楚什么原因。。。也许是电脑系统的原因吧。
