### ISSUE TITLE
特定机场无法更新订阅

### ISSUE THREAD

**Issue by AgathonLi** [2dust/clashN#105]
使用中发现一个机场**仅在clashN无法订阅**，但在windows和安卓端的clash都能正常更新；在v2rayN也可以更新，导入为ss和trojan节点。

日志debug如下：（去除敏感信息）
更新订阅开始
XXXCloud->开始获取订阅内容
time="2022-08-30T14:30:24+08:00" level=debug msg="[Process] XXXCloud.com from process \\Device\\HarddiskVolume3\\Users\\ali\\Desktop\\Tools\\ClashN\\clashN.exe"
time="2022-08-30T14:30:24+08:00" level=debug msg="[DNS] XXXCloud.com --> xx.xx.xx.xx"
time="2022-08-30T14:30:24+08:00" level=info msg="[TCP] 127.0.0.1:50261 --> XXXCloud:443 match Match() using 漏网之鱼[🇸🇬 SS|新加坡A01]"
XXXCloud->获取订阅内容成功
XXXCloud->导入订阅内容失败
更新订阅结束

咨询机场主，机场主表示“不支持低版本clash，因为安全系数低”，不太理解这个说法。请问大佬这个问题有希望解决吗？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.21
使用此版本更新订阅，提交日志
可发订阅地址到captainIronng@protonmail.com

**Comment by AgathonLi** [comment]
> https://github.com/2dust/clashN/releases/tag/1.21 使用此版本更新订阅，提交日志 可发订阅地址到[captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

谢谢，已经使用最新版本测试，仍然不能更新。日志如下：

更新订阅开始
XXXCloud->开始获取订阅内容
time="2022-08-30T15:59:10+08:00" level=debug msg="[Process] XXXCloud.com from process \\Device\\HarddiskVolume3\\Users\\ali\\Desktop\\Tools\\ClashN\\clashN.exe"
time="2022-08-30T15:59:10+08:00" level=debug msg="[DNS] XXXCloud.com --> xx.xx.xx.xx"
time="2022-08-30T15:59:10+08:00" level=info msg="[TCP] 127.0.0.1:61573 --> XXXCloud.com:443 match Match() using 漏网之鱼[🇭🇰 SS|香港A01]"
XXXCloud->The request returned with HTTP status code Forbidden
XXXCloud->无效的订阅内容
更新订阅结束

订阅链接已经发送到指定邮箱供测试。

**Comment by 2dust** [comment]
clashN打开订阅配置文件，在User Agent 框内填入 ClashforWindows，保存后再订阅更新
