### ISSUE TITLE
我的配置文件，启用了Meta内核，但是还是刷不出节点，错误显示不支持vless

### ISSUE THREAD

**Issue by feidaodu** [2dust/clashN#108]
配置成功
Meta
启动服务(2022/9/4 21:09:43)...
time="2022-09-04T21:09:44+08:00" level=fatal msg="Parse config error: proxy 0: unsupport proxy type: vless"

相应的配置文件，我在OpenClash以及改了内核的ClashforWindows都能运行。
大神们，看看是不是Bug

**Comment by 2dust** [comment]
请打开配置文件确认下core类型

**Comment by PanHsin** [comment]
使用clashN 1.22或1.21版本.
双击节点，编辑节点信息，要选择clash meta。
经测试，软件内更新Clash meta版本可以解决完问题。

@2dust 
或是clashN不能识别目录自带的 clash meta(版本太旧没有支持？)？

即便节点信息选择clash-meta，也不能支持 vless /ss 2022.

软件内 更新clash meta之后，测试正常。

**Comment by 2dust** [comment]
请升级到2.0

**Comment by Likeorange1** [comment]
怎么升级啊请问
