### ISSUE TITLE
clashN无法启动

### ISSUE THREAD

**Issue by zhl111** [2dust/clashN#109]
我下载了clashN-Core.zip，解压后，点击clash.exe，没有任何反应，不提示任何错误，似乎没有启动……
Microsoft [.NET 6.0 Desktop Runtime](https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0/runtime)也安装啦

我也重启了，请教如何解决呢？系统是win11 64位。

**Comment by 2dust** [comment]
https://download.visualstudio.microsoft.com/download/pr/b4a17a47-2fe8-498d-b817-30ad2e23f413/00020402af25ba40990c6cc3db5cb270/windowsdesktop-runtime-6.0.8-win-x64.exe

安装这个，安装后试一试
