### ISSUE TITLE
[功能建议] 增加代理链功能

### ISSUE THREAD

**Issue by zazitufu** [2dust/clashN#11]
比如我有速度比较好的服务器 A和B （如机场的鸡鸡），另外有 能解锁各种流媒体但是直连速度比较不好的服务器 1，2，3

能否通过v2ray的前置代理功能，用菜单选择的方式来建立代理链 :
A -> 1 
B -> 1
A -> 2
A -> 3
类似这样的功能？

目前我只会通过在A或者B的服务器上面，对v2ray的配置进行编辑，增加inbound 和outbound， 然后通过单独的配置文件来实现代理链，但是这种方式要求能访问和修改A/B服务器，如果A/B服务器是机场提供的就不能用这个方式来建立代理链了。即使AB是自己的服务器，配置里代理链写完了之后要修改也很不方便。

我看到v2ray的文档里面是有可以实现前置代理的功能的，在一些openwrt的插件比如 SSR+这个插件，里面也能实现前置代理的功能（供您参考）。

**Comment by 2dust** [comment]
此项目是clash客户端
v2rayN是v2ray的客户端
您要的功能请用v2rayN写自定义配置
