### ISSUE TITLE
允许局域网的连接 

### ISSUE THREAD

**Issue by ipx2001** [2dust/clashN#111]
这个功能不知道哪里有问题，能连接，能ping通，就是在手机上用v2rayNG同网络段，创建socks127.0.0.1:7891(四个端口都测试了)，手机APP无法连接到外网，但是telegram可以连接，其他的都连接不上去！

**Comment by 2dust** [comment]
看不懂您要表达什么？

**Comment by ipx2001** [comment]
问题找出来了，clashN要打开系统代理，它才能处理局域网的请求连接外网，v2rayN就没这个问题，不打开一样可以处理局域网的请求，不知道你能明白吗？

**Comment by 2dust** [comment]
并不是这样的逻辑
系统代理只是作用在本机
你要局域网用请参数设置中开启
