### ISSUE TITLE
流量统计会统计直链部分?/添加测速功能/UI改进

### ISSUE THREAD

**Issue by cancundeyingzi** [2dust/clashN#112]
规则模式,看b站,发现今日下载增加,百度ip,显示ip在国内,google搜ip显示ip在国外
和v2rayn一样加个节点测速?
UI布局感觉不是很行,美观不如cfw,操作也不是很方便,比如开关tun/开关代理等,不符合工具高效的目标

**Comment by 2dust** [comment]
流量统计由Core提供 https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference###Traffic
测速可能会加
如果用管理员模式运行calshN，开关tun是很方便的，编辑配置文件重载配置就行了

**Comment by cancundeyingzi** [comment]
> 流量统计由Core提供[https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference###](https://github.com/Dreamacro/clash/wiki/External-controller-API-Reference###Traffic)流量 测速可能会加 用管理员模式运行calshN，开关屯是很方便的，编辑配置文件重载配置就行了

哦这么说是统计所有经过clashn的流量?,那再和cfw一样加个连接的监控?
另外我也看到别人说记住窗口大小,表格长宽等,经测试正常退出确实可以保存,但是重启电脑就废,不是很方便,节点别名每次都看不全...
开机自启也没有管理员模式,cfw也只要点两三下鼠标就能开关了,
甚至可以把配置文件和当前代理放在一个页面,现在俩页面点来点去,按钮也比较小...
我个人看法是如果不想和cfw竞争美观,那就从高效入手,怎么高效怎么来,,当然你要说这玩意纯自己兴趣做着玩,那当我没说(笑哭)
我现在弃用cfw主要是他们设置里奇奇怪怪的太多,稍微有点臃肿,稳定性也不行,还没'信息'栏

**Comment by cancundeyingzi** [comment]
对比cfw,v2n优点,真连接延迟,双内核,日志信息
缺点,UI,连接,流量使用情况,便捷程度,测速

**Comment by 2dust** [comment]
UI正在重构，请等待一段时间

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.0

**Comment by cancundeyingzi** [comment]
> https://github.com/2dust/clashN/releases/tag/2.0

我已经在昨天听说了新版本了，正在体验。
