### ISSUE TITLE
以后会支持proxy-provider吗？

### ISSUE THREAD

**Issue by BaronChushao** [2dust/clashN#114]
希望大佬能够让clashN支持proxy-providers😘

**Comment by 2dust** [comment]
proxy-providers是core功能，配置文件搞好就行，有什么问题吗？

**Comment by BaronChushao** [comment]
可是我添加配置文件时选中clash可用的那个配置文件，当前代理里面没有节点，难道是我的操作有问题吗？🤣

**Comment by BaronChushao** [comment]
![image](https://user-images.githubusercontent.com/98247704/189656509-eb152abd-552f-4e25-8846-4d12ea441566.png)

**Comment by 2dust** [comment]
unsupported rule type RULE-SET

clash core 不支持 RULE-SET
切换成clash p core

**Comment by BaronChushao** [comment]
好的，我去试试
