### ISSUE TITLE
提几点小意见

### ISSUE THREAD

**Issue by xixiri** [2dust/clashN#115]
1、左右列表大小和各列调整大小后能记住吗，下次打开又还原了，太麻烦了
2、当前代理列表左边列表，点空白处时，右边的代理列表别消失好吗
3、右边代理表格，能记住按测试结果排序吗，每次排序都要点一下，calsh原版可以啊

**Comment by 2dust** [comment]
UI正在重构，请等待

**Comment by 2dust** [comment]
请试用2.0后反馈问题，此issue关闭

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.0
