### ISSUE TITLE
不能在线更新？

### ISSUE THREAD

**Issue by final999** [2dust/clashN#116]
不能在线更新clashn、core、meta core，提示

warning msg="[TCP] dial DIRECT to github.com:443 error: dual stack tcp shake hands failed"
The SSL connection could not be established, see inner exception.
Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接

**Comment by 2dust** [comment]
支持
需要您的代理支持访问GitHub

**Comment by final999** [comment]
现在又可以更新了。
本来是可以更新的，后来在配置文件中多了一个文件，就不能更新了，删除后就可以更新了，忘记那个文件名字了
