### ISSUE TITLE
[FR] Portable Mode

### ISSUE THREAD

**Issue by ag2s20150909** [2dust/clashN#12]
When a new folder named ```data``` is created in the current directory of the software executable, portable mode will use this folder as the base startup folder and as the Home Directory

**Comment by 2dust** [comment]
clashN is already in portable mode

**Comment by ag2s20150909** [comment]
> clashN is already in portable mode

but it store file  in ```C:\Users\xxxx\.config\clash```,when use local flie ```proxy-providers```

**Comment by 2dust** [comment]
proxy-providers type: http or file？
If http, you can download it yourself when you use it
If file, you can use absolute path

**Comment by ag2s20150909** [comment]
> proxy-providers type: http or file？ If http, you can download it yourself when you use it If file, you can use absolute path


https://github.com/Dreamacro/clash/blob/30d4668008b493b65e7d6982b4c43bb34871e13c/main.go#L33

https://github.com/MetaCubeX/Clash.Meta/blob/4c8d651d6585bed810b82ce2e4d2e5e31a89f34d/main.go#L34

Clash core use ```-d``` set configuration directory(homeDir) and ```-f``` specify configuration file.
So It is easy to implement this feature.
1，Check whether the target folder exists in the current installation directory.
2, If it exists, add ```-d``` to the startup parameter to specify the homeDir

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/8468824/clashN.zip)
Test with this version
