### ISSUE TITLE
即便是安装了net 6.0.101 x64，软件依旧无法正常工作

### ISSUE THREAD

**Issue by Rosabis** [2dust/clashN#123]
如图
![20220925203628](https://user-images.githubusercontent.com/32984303/192143734-7f213594-ba22-4539-afb9-3050b151fa90.png)

**Comment by PanHsin** [comment]
是安装runtime.

https://download.visualstudio.microsoft.com/download/pr/dc0e0e83-0115-4518-8b6a-590ed594f38a/65b63e41f6a80decb37fa3c5af79a53d/windowsdesktop-runtime-6.0.7-win-x64.exe

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.0
请试用此版本反馈
