### ISSUE TITLE
clashN can't  display the config file contents(when it contains a lot of proxy server)

### ISSUE THREAD

**Issue by COMPIONEZHAO** [2dust/clashN#127]
when i use a subscription which uses the convert function,  tun mode(uses meta core) and it contains 96 proxy server in a yaml file . when i check the current porxy field，it dosen't show any contents! But i can view it when i edit the config file.
I use the version 1.22 clashN and newest clash core and meta core.

**Comment by 2dust** [comment]
try https://github.com/2dust/clashN/releases/tag/2.0
