### ISSUE TITLE
发现一个问题，假设在主窗口中有10个订阅源。我进行“订阅更新”的时候，看到假如这10订阅源中有1个订阅源更新不了，下面“信息”窗口中就会卡住，不会跳过这个更新不了的订阅源，而接着进行下一个订阅源的更新。

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#13]
发现一个问题，假设在主窗口中有10个订阅源。我更行“订阅更新”的时候，假如这10订阅源中有1个订阅源更新不了，下面“信息”窗口中就会卡住，不会跳过这个更新不了的订阅源，而接着进行下一个订阅源的更新。
![image](https://user-images.githubusercontent.com/26890748/162241331-4af43b8c-c081-4c09-9ebb-b3a975997457.png)

**Comment by 2dust** [comment]
原来的模式是多线程并发更新，更新的进度提示有点乱；然后是这次改成一个个更新的模式。
对应你这种情况，增加个超时吧。

**Comment by fyhzc** [comment]
这个：超时 最好能在“参数设置---clashN设置”那里手动设置（1-30秒）

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/8448214/clashN.zip)
固定为5s
设置太多显得复杂了

**Comment by fyhzc** [comment]
可以吧，试了下可以了，5s会 不会短了点，10s吧。嘻嘻
