### ISSUE TITLE
大佬，我在使用clashN2.0的时候，启动后界面和字体都太大了，界面基本上占据了电脑桌面的75%左右，且字体也是比较大，有没有什么方法解决这个问题

### ISSUE THREAD

**Issue by yueliuLEE** [2dust/clashN#131]
![image](https://user-images.githubusercontent.com/104079740/193418447-a37fc8b3-fc66-48cc-8b8f-0210714dd489.png)

**Comment by yueliuLEE** [comment]
![image](https://user-images.githubusercontent.com/104079740/193436574-9cdaa589-9a43-4415-8887-d01042950477.png)

**Comment by yueliuLEE** [comment]
![image](https://user-images.githubusercontent.com/104079740/193436636-7b2844a7-8b4c-4506-8fcc-ed06a95d2d93.png)

**Comment by 2dust** [comment]
启动后界面大小您可以自己拖动缩小，正常退出的时候会保存大小。
字体大小，需要您把系统环境写出来，我们好针对调整

**Comment by yueliuLEE** [comment]
![image](https://user-images.githubusercontent.com/104079740/193453636-84c4c589-00f2-4544-b0df-b710543db403.png)

**Comment by 2dust** [comment]
显示设置的缩放是多少？

**Comment by yueliuLEE** [comment]
![image](https://user-images.githubusercontent.com/104079740/193457647-21d6c7c9-fb7d-4df4-b9d7-a8fc3fd8bd4e.png)

**Comment by DoveBoy** [comment]
2.0后不区分clashn和clashn-core了吗？

**Comment by 2dust** [comment]
> 

你这个分辨率还要150%，是不是有点过了？

接下来字体和界面整体调小点

**Comment by 2dust** [comment]
> +1，分辨率：1920 ×1080，缩放150%， 软件启动后标题栏在屏幕外，手动缩小的话，代理列表和帮助页面底部都显示不全

你这个分辨率还要150%，是不是有点过了？

接下来字体和界面整体调小点

**Comment by 2dust** [comment]
> 2.0后不区分clashn和clashn-core了吗？

不在区分，原来是为了减小发布包的大小，现在没有必要了

**Comment by DoveBoy** [comment]
> 不在区分，原来是为了减小发布包的大小，现在没有必要了

后续是开始只发布2.x版本了吗？新版界面比1.x的好看太多了

**Comment by 2dust** [comment]
[clashN-rc1.zip](https://github.com/2dust/clashN/files/9697700/clashN-rc1.zip)
调整了字体和部分界面，请反馈

**Comment by FrzMtrsprt** [comment]
默认窗口大小仍然会超出屏幕，且工具栏的字体似乎是扁的
手动调整到最小，关闭日志面板后好很多
如果能在首次启动时根据屏幕分辨率调整窗口大小就好了
日志面板也可以做成常闭的状态
![image](https://user-images.githubusercontent.com/15852717/193594142-16d98bda-b3ca-47cf-af9c-d847d046a9c8.png)
![image](https://user-images.githubusercontent.com/15852717/193595054-8e2cc36d-aef4-4634-bfe8-e5d79c049845.png)

**Comment by yueliuLEE** [comment]
clashN-rc1.zip 启动窗口界面大小我觉得是比较合适的，但是右键clashN图标弹出的界面和字体较大，希望能够像v2rayN右键界面大小差不多就很好了
![image](https://user-images.githubusercontent.com/104079740/193721304-bb2adab1-f2e3-4c27-b445-7cd0603164ba.png)

**Comment by 2dust** [comment]
[clashN-rc2.zip](https://github.com/2dust/clashN/files/9702604/clashN-rc2.zip)

继续调整，请反馈

**Comment by yueliuLEE** [comment]
clashN-rc2.zip  启动窗口界面大小是比较合适的,右键图标弹出界面的字体也比较小，但是行距比较大，导致界面看起来较大且感觉不够紧凑
![image](https://user-images.githubusercontent.com/104079740/193786530-98b74ac8-2d42-4f80-aed4-59bcc6a0f3de.png)

**Comment by 2dust** [comment]
> 

暂时找不到在哪里调整
其他的请多多反馈

**Comment by FrzMtrsprt** [comment]
考虑把托盘菜单换回 winform 的 NotifyIcon 吗？
现在托盘菜单的展开动画比较影响使用效率
PowerToys 和 Unigram 等 WinUI 应用也都在使用原生样式的菜单
另外双击打开窗口的操作稍微有些不方便，可以考虑换成单击打开，单击关闭，与 qBittorent、OBS 等应用行为一致。

**Comment by 2dust** [comment]
[clashN-rc4.zip](https://github.com/2dust/clashN/files/9715430/clashN-rc4.zip)
此测试版把系统代理的选项直接显示出来了，规则未处理作为对比；增加了单击显示主窗口（点击有点慢）；增加的再次单击关闭
winform 的 NotifyIcon 无法达到mvvm的要求

多反馈

**Comment by FrzMtrsprt** [comment]
1. 托盘菜单的 radio button 是灰色的，主题色设为黄色时可以明显看出
![image](https://user-images.githubusercontent.com/15852717/194060750-45a40181-f9dc-427b-873a-7aa988052ca9.png)
2. 主界面 4 个 tab 的工具栏宽度、高度不一致，似乎和是否包含图标有关

3. 工具栏的标签和 combo box 的字体大小不一致
![image](https://user-images.githubusercontent.com/15852717/194060879-8698d067-24eb-417a-8729-6652a9865061.png)
4. 可以将界面各处卡片的复选框去掉
![image](https://user-images.githubusercontent.com/15852717/194061245-5695dcde-3b50-496d-bea2-5a0d046a044d.png)
5. 当前连接标题栏中的连接数量不明显，可以改为纯文本，如`当前连接（6）` `当前连接（活跃连接：6）`
![image](https://user-images.githubusercontent.com/15852717/194063132-fe068fe7-a746-4b92-abb7-3b7ef6ee161f.png)
参考：
![image](https://user-images.githubusercontent.com/15852717/194063739-a965b658-a96b-4b99-92cd-055b1ada4cb7.png)
5. 可以考虑减弱日志面板在主界面上的视觉权重，比如减小默认宽度，去掉边框强调色，常闭、点击暂时开启。

6. 建议发布 pre-release，单开一个 issue 征集意见，这样大家都能看到

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.1
能处理的基本都处理了

**Comment by justdoiting** [comment]
![image](https://user-images.githubusercontent.com/109136320/194380541-3ea6d0d2-1d5c-42d6-a0df-f0514ad134d9.png)
2.1有点模糊，而且好像显示的比较小

**Comment by DoveBoy** [comment]
> ![image](https://user-images.githubusercontent.com/109136320/194381478-9384a60d-acc6-4488-9c58-aad039c42219.png) 2.1有点模糊，而且好像显示的比较小，log部分间距太夸张了

同样的感觉，也许是因为电脑屏幕大的原因，感觉2.1界面不如2.0，2.1太过小了

**Comment by DoveBoy** [comment]
> 2.1有点模糊，而且好像显示的比较小，log部分间距太夸张了

同样的感觉，不知道是不是电脑屏幕大小的原因造成的，2.0显示挺正常的，2.1显示的太小了

**Comment by 2dust** [comment]
@justdoiting @DoveBoy  请具体反馈哪些地方显示太小？

**Comment by 2dust** [comment]
[clashN-rc1.zip](https://github.com/2dust/clashN/files/9733486/clashN-rc1.zip)

对当前连接和信息界面做了微调，请测试反馈

**Comment by DoveBoy** [comment]
> @justdoiting @DoveBoy 请具体反馈哪些地方显示太小？

![image](https://user-images.githubusercontent.com/19201447/194544083-c454112a-1ee5-41fe-b5de-6bd9bcb44aaa.png)

**Comment by DoveBoy** [comment]
> [clashN-rc1.zip](https://github.com/2dust/clashN/files/9733486/clashN-rc1.zip)
> 
> 对当前连接和信息界面做了微调，请测试反馈

![image](https://user-images.githubusercontent.com/19201447/194544604-d86a3250-43ab-4181-8c84-b173c19f5e0d.png)

界面字体大了一些

**Comment by 2dust** [comment]
[clashN-rc2信息框在下方.zip](https://github.com/2dust/clashN/files/9733651/clashN-rc2.zip)

此版本是把信息框放到界面下方，请对比反馈，是否这样看起来更好些

**Comment by DoveBoy** [comment]
> [clashN-rc2信息框在下方.zip](https://github.com/2dust/clashN/files/9733651/clashN-rc2.zip)
> 
> 此版本是把信息框放到界面下方，请对比反馈，是否这样看起来更好些

![image](https://user-images.githubusercontent.com/19201447/194549726-10e572d9-983e-4692-b7b8-71fd820ad2ca.png)

似乎这样更好看一些

**Comment by FrzMtrsprt** [comment]
> [clashN-rc2信息框在下方.zip](https://github.com/2dust/clashN/files/9733651/clashN-rc2.zip)
> 
> 此版本是把信息框放到界面下方，请对比反馈，是否这样看起来更好些

可以考虑把信息框放在侧栏的右边，和 VS Code 类似的布局，这样会更美观一些

![image](https://user-images.githubusercontent.com/15852717/194555294-624eb3a1-f40e-49be-a55c-908c5342393a.png)

**Comment by 2dust** [comment]
> > [clashN-rc2信息框在下方.zip](https://github.com/2dust/clashN/files/9733651/clashN-rc2.zip)
> > 此版本是把信息框放到界面下方，请对比反馈，是否这样看起来更好些
> 
> 可以考虑把信息框放在侧栏的右边，和 VS Code 类似的布局，这样会更美观一些
> 
> ![image](https://user-images.githubusercontent.com/15852717/194555294-624eb3a1-f40e-49be-a55c-908c5342393a.png)

这是一个方案
另外是否可以把信息页面，作为左边导航的一页，应该比较美观；缺点是在其他页时不能实时看信息

**Comment by FrzMtrsprt** [comment]
> > > [clashN-rc2信息框在下方.zip](https://github.com/2dust/clashN/files/9733651/clashN-rc2.zip)
> > > 此版本是把信息框放到界面下方，请对比反馈，是否这样看起来更好些
> > 
> > 
> > 可以考虑把信息框放在侧栏的右边，和 VS Code 类似的布局，这样会更美观一些
> > ![image](https://user-images.githubusercontent.com/15852717/194555294-624eb3a1-f40e-49be-a55c-908c5342393a.png)
> 
> 这是一个方案 另外是否可以把信息页面，作为左边导航的一页，应该比较美观；缺点是在其他页时不能实时看信息

确实，单独作为一个页面似乎更好一点，CFW 和 Clash 的 web ui 都是这样做的

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.2

**Comment by DoveBoy** [comment]
> [`2.2` (release)](https://github.com/2dust/clashN/releases/tag/2.2)

2.2更合理一些，日志以单独的页签形式展现，比之前的任何方案都要好，整体页面也不会凌乱了

**Comment by NOthing2O2O** [comment]
> [https://github.com/2dust/clashN/releases/tag/2.2 ](https://github.com/2dust/clashN/releases/tag/2.2)

能否换用其他字体？默认字体有点发虚。

**Comment by FrzMtrsprt** [comment]
字体模糊是字体太小导致的，现在界面显示不全的问题已经解决了，换回默认字体大小应该可以解决。

**Comment by NOthing2O2O** [comment]
> 字体模糊是字体太小导致的，现在界面显示不全的问题已经解决了，换回默认字体大小应该可以解决。

<img width="967" alt="Snipaste_2022-10-09_09-44-10" src="https://user-images.githubusercontent.com/68501505/194733848-5ea48faa-db79-4c27-88da-554a7c11aa54.png">
<img width="322" alt="Snipaste_2022-10-09_09-48-10" src="https://user-images.githubusercontent.com/68501505/194733850-f6c9b421-cc7b-4e10-9bfd-a2e8529d9a2a.png">
<img width="1015" alt="Snipaste_2022-10-09_09-45-58" src="https://user-images.githubusercontent.com/68501505/194733851-466f7d17-e5da-4900-9bb7-e2b1af755388.png">
左边导航标签页的字体看起来就好很多，右边内容区域的字体就有点虚（或许用的细字体？），附上一张clash for Windows界面截图（字体已改用HarmonyOS Sans）。
系统：Windows 11 22H2   分辨率：3840*2160   缩放：150%   clashN版本：2.2

**Comment by 2ndMessiah** [comment]
> > [`2.2` (release)](https://github.com/2dust/clashN/releases/tag/2.2)
> 
> 2.2更合理一些，日志以单独的页签形式展现，比之前的任何方案都要好，整体页面也不会凌乱了

刚开始用clashn, 相对v2，还是更喜欢v1，简洁、高效、直观，和v2rayn一样干练

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.3
