### ISSUE TITLE
2.0 没有启动后最小化了？

### ISSUE THREAD

**Issue by rampageX** [2dust/clashN#134]
如题，每次自启动都显示软件界面了，以前可以最小化启动到任务栏。

**Comment by fyhzc** [comment]
me too

**Comment by 2dust** [comment]
> 



> 同。
> 
> 并且，在 参数设置>日志等级 中选中silent后，重启动后软件无法正常读取配置文件并抛出以下提示
> 
> time="yyyy-MM-ddTH:mm:ss+08:00" level=error msg="invalid mode" configuration file D:\clashN\guiConfigs\config.yaml test failed

https://github.com/2dust/clashN/releases/tag/2.1
bug已经修复

**Comment by 2dust** [comment]
因为用了MVVM模式，暂时是需要显示界面才能绑定
