### ISSUE TITLE
配置文件不显示策略组！

### ISSUE THREAD

**Issue by being123321** [2dust/clashN#136]
选中了订阅，不显示策略组，也无法上网
![image](https://user-images.githubusercontent.com/70810596/194351482-cf48ae17-8ff2-45bd-aebc-2664b34c5777.png)
![image](https://user-images.githubusercontent.com/70810596/194351568-db37a46f-75f6-440b-a82c-75b250542a12.png)

**Comment by being123321** [comment]
发现换meta内核时就会出现，clash内核正常

**Comment by being123321** [comment]
发现换meta内核时就会出现，clash内核正常

**Comment by 2dust** [comment]
感谢反馈，你暂时先用clash

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.2

**Comment by Clackz** [comment]
2.2版本……现在是meta内核正常，clash内核会出现这个问题

**Comment by Clackz** [comment]
> 2.2版本……现在是meta内核正常，clash内核会出现这个问题

配置成功
clash_subscription
启动服务(2022/10/9 0:08:36)...
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial configuration in progress"
time="2022-10-09T00:08:36+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-10-09T00:08:36+08:00" level=info msg="Initial configuration complete, total time: 16ms"
time="2022-10-09T00:08:36+08:00" level=info msg="Sniffer is closed"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider default"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-10-09T00:08:36+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-10-09T00:08:36+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-10-09T00:08:36+08:00" level=info msg="HTTP proxy listening at: [::]:7890"
time="2022-10-09T00:08:36+08:00" level=info msg="SOCKS proxy listening at: [::]:7891"
time="2022-10-09T00:08:36+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7888"
2022/10/9 0:08:37 Change system proxy
2022/10/9 0:08:37 Set rule mode Rule->Rule
2022/10/9 0:08:37 Clash Proxies Latency Test
2022/10/9 0:08:37 Refresh Clash Proxies
配置成功
clash_subscription
启动服务(2022/10/9 0:08:49)...
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-10-09T00:08:49+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2022-10-09T00:08:49+08:00" level=fatal msg="Parse config error: rules[9766] [MATCH,🐟 漏网之鱼,dns-failed] error: proxy [dns-failed] not found"

2022/10/9 0:08:49 Change system proxy
2022/10/9 0:08:49 Set rule mode Rule->Rule
2022/10/9 0:08:49 Clash Proxies Latency Test

**Comment by being123321** [comment]
> 2.2版本……现在遇到一个内核正常，c是内核会出现这个问题

是的

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.3
更新此版本，重新更新订阅一次
