### ISSUE TITLE
新手表示没有图形界面去管理策略组访问指定的网站设置白名单，，黑名单访问

### ISSUE THREAD

**Issue by asu00131** [2dust/clashN#137]
新手表示没有图形界面去管理策略组访问指定的网站设置白名单，，黑名单访问，，
多个yaml，是合并的吗？，，还是分开的？
①访问的策略是规定到延时低的，，集合？？
②访问的策略是规定到速度下载快的集合？？
①②是多个yaml名单的合并的吗，，emmmm如果是分开的，，那么我想要合并多个yaml需要怎么操作

**Comment by 2dust** [comment]
https://github.com/Dreamacro/clash/wiki
先自己看clash的wiki
