### ISSUE TITLE
请问设置Mixin的结果是完全替换对象，还是替换对象中所写的属性？

### ISSUE THREAD

**Issue by SESProMax** [2dust/clashN#138]
如题

**Comment by 2dust** [comment]
```
# 使用clash配置文件关键字则覆盖原配置
#
# removed-rules    循环匹配rules数组每行,符合则移除当前行 (此规则请放最前面)
#
# append-rules    数组合并至原配置rules数组后
# prepend-rules   数组合并至原配置rules数组前
# append-proxies      数组合并至原配置proxies数组后
# prepend-proxies     数组合并至原配置proxies数组前
# append-proxy-groups     数组合并至原配置proxy-groups数组后
# prepend-proxy-groups    数组合并至原配置proxy-groups数组前
# append-rule-providers     数组合并至原配置rule-providers数组后
# prepend-rule-providers    数组合并至原配置rule-providers数组前
```

**Comment by SESProMax** [comment]
> # 使用clash配置文件关键字则覆盖原配置
> #
> # removed-rules    循环匹配rules数组每行,符合则移除当前行 (此规则请放最前面)
> #
> # append-rules    数组合并至原配置rules数组后
> # prepend-rules   数组合并至原配置rules数组前
> # append-proxies      数组合并至原配置proxies数组后
> # prepend-proxies     数组合并至原配置proxies数组前
> # append-proxy-groups     数组合并至原配置proxy-groups数组后
> # prepend-proxy-groups    数组合并至原配置proxy-groups数组前
> # append-rule-providers     数组合并至原配置rule-providers数组后
> # prepend-rule-providers    数组合并至原配置rule-providers数组前

这个说明我看过了，我想问一下假如我在mixin中设置了dns的一个属性，那么原文件中给出的其他属性还会保留吗？

**Comment by 2dust** [comment]
> 这个说明我看过了，我想问一下假如我在mixin中设置了dns的一个属性，那么原文件中给出的其他属性还会保留吗？

不会保留部分，直接全部覆盖。
你可以自己查看\guiConfigs\\config.yaml

**Comment by SESProMax** [comment]
> > 这个说明我看过了，我想问一下假如我在mixin中设置了dns的一个属性，那么原文件中给出的其他属性还会保留吗？
> 
> 不会保留部分，直接全部覆盖。 你可以自己查看\guiConfigs\config.yaml

OK，thanks！
