### ISSUE TITLE
大佬 说明书能整一份吗

### ISSUE THREAD

**Issue by 887BF690** [2dust/clashN#14]
[Clash.Meta](https://github.com/MetaCubeX/Clash.Meta) 内核  介绍一下，网上搜不到详细说明

**Comment by 2dust** [comment]
Clash.Meta 是 https://github.com/Dreamacro/clash 的超集，
原本的文档看这里 https://github.com/Dreamacro/clash/wiki
Clash.Meta增加的看这里 https://github.com/MetaCubeX/Clash.Meta/tree/Meta
