### ISSUE TITLE
配置规则的重新载入好像不起作用

### ISSUE THREAD

**Issue by Rashhz** [2dust/clashN#141]
当我修改了配置文件里的rules后，使用重新载入配置并未起效果，只有我重启了metacore和clashN之后才起作用

**Comment by 2dust** [comment]
这样测试，你修改后重新载入，看guiConfigs下config.yaml，看是否是你修改后的文件
如果是但是不起作用，那应该是core提供的api问题

**Comment by Rashhz** [comment]
> https://github.com/2dust/clashN/releases/tag/2.4
> 
> 我理解你的问题了，此版本修改了部分文字描述，配置文件界面的重载改成刷新；真正能重载配置的是主界面左上角的哪个按钮

大佬辛苦了，刚刚测试了一下，编辑了配置文件之后，选择刷新，config.yaml没有变化。不过左上角的那个按钮确实能起到重载的效果，但是还不太理解配置文件的刷新是什么意思。感谢大佬的贡献
