### ISSUE TITLE
一点点小问题

### ISSUE THREAD

**Issue by xixiri** [2dust/clashN#142]
配置文件里，把鼠标放在几个功能按钮上，提示信息一闪而过，根本就看不清，也就不知道这个按钮是干啥用的了

**Comment by xixiri** [comment]
> https://github.com/2dust/clashN/releases/tag/2.4


https://user-images.githubusercontent.com/19706511/196021707-335ddcee-d845-439b-b960-c8b2cbd4a131.mp4

虽然我有点吹毛求疵了点，但为什么按钮一样，显示的不一样呢

**Comment by 2dust** [comment]
可能是开发工具的bug或系统bug了，因为他们的代码是一样的
