### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by vkj2034** [2dust/clashN#144]
ClashN每次重新打开的时候参数设置会自动恢复为默认比如启用IPV6重新打开ClashN会自动关闭每次都得手动打开，ClashN切换配置文件和选择节点得用右键有点太繁琐，建议只需用鼠标左键点一个节点或者配置文件即可切换就很方便，希望在下个版本更改一下。

**Comment by Yzcloud** [comment]
你是不是设置完了，没有点保存呀？

**Comment by vkj2034** [comment]
> 你是不是设置完了，没有点保存呀？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.4

 此版本修改了部分文字描述，增加了些提示。 特别是修改设置后需要点击保存
