### ISSUE TITLE
配置文件和节点选择点击后的底色

### ISSUE THREAD

**Issue by Yzcloud** [2dust/clashN#147]
![2022-10-12_17-022022-10-12](https://user-images.githubusercontent.com/88927779/195299693-1995a426-9bac-4910-8e39-ace773d34aff.png)

**改成tg点击聊天窗口效果，UI会不会和谐一点**

![2022-10-12_17-012022-10-12](https://user-images.githubusercontent.com/88927779/195299428-f44a50e2-6628-46d8-abdb-a2b0ba3658dd.png)

**Comment by 2dust** [comment]
你的意思是改底色，不改文字颜色？

**Comment by Yzcloud** [comment]
> 你的英文是改底色，不改文字颜色？
是的，目前这个点选后显示的ui太违和了，图标是圆角，然后底色是方形，左右又不整齐，如果换成点选颜色是在圆角ui内显示，不要圆角下那个方形显示，效果会好很多

**Comment by Yzcloud** [comment]
这个版本的UI很漂亮，嘿嘿，或许你可以改成取消内置配色，让用户自定义配色？
