### ISSUE TITLE
几个使用过程中出现的问题

### ISSUE THREAD

**Issue by ForbAvalon** [2dust/clashN#148]
1.有的配置无法读取剩余流量不知道为啥，用的是薯条的代理。不过花云就可以读出来
2.一部分节点ping出resource not found，但是实际上可以连接
3.当前代理缺少默认排序选项，薯条的太乱了，如果不按默认排序找都要找半天

**Comment by 2dust** [comment]
请把薯条订阅发到 captainIronng@protonmail.com
方便我们测试

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.7
1，3已经处理，2暂时无法解决
