### ISSUE TITLE
配置文件里的订阅地址可以拖放调整排序吗？

### ISSUE THREAD

**Issue by EzSync** [2dust/clashN#149]
配置文件里的订阅地址可以拖放调整排序吗？
Clash For Windows里面是可以通过鼠标拖放调整排序的。
当然，如果也能添加更多的排序方式也好，比如按照日期、名称等排序。
另外，订阅以卡片式显示，非常规整，如果能再小一点就更好了，就像”当前代理“里的一样。

**Comment by buiawpkgew1** [comment]
重复问题？ https://github.com/2dust/clashN/issues/150

**Comment by EzSync** [comment]
> 

不好意思，可能是网页反应延迟，提交了2次。发现后找不到哪里可以删除，抱歉！

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.8
