### ISSUE TITLE
2.3版本无法自定义订阅转换网址

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#151]
版本：2.3

现状：
之前1.x的时候，除了预设的几个订阅网址，可以自己定义其他域名的订阅转换服务。到了2.3上之后，只有预留的3个可选。类似下面这样的链接是没法设置的：

https://sub.xeton.dev/sub?target=clash&new_name=true&url={0}&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&emoji=true&list=false&tfo=false&scv=true&fdn=true&sort=true&udp=true

需求：
希望能像1.x那样可以自定义订阅转换网址。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.5
