### ISSUE TITLE
关于1.x到2.x版本的升级后内存的占用

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#152]
首先谢谢作者的努力，提供好用的工具。

刚刚开始使用1.x版本的时候，觉得clashN相较于一直在用的clash for windows占用资源（约220m左右）少，主程序大约40m内存的占用。现在升级到2.x之后，界面是好看了，但是主程序占用内存在128m左右，是原来的3倍了。

2.x还能做到原来那样的资源占用水平吗？

**Comment by 2dust** [comment]
做不到了
已经尽量控制不使用过多的库，只允许必要的库启动就已经占用100m了
您非常在意内存就用1.x吧，基本功能都有了
