### ISSUE TITLE
能否添加更换代理后中断链接的功能

### ISSUE THREAD

**Issue by lleeopen** [2dust/clashN#154]
![003](https://user-images.githubusercontent.com/35162785/196016569-e64f69d5-fb86-4369-aa97-fe31a85bd36c.jpeg)

**能否添加更换代理后中断链接的功能，以便使代理更快生效，非常需要这个功能**

**Comment by 2dust** [comment]
更换代理后中断链接：意思是在切换配置文件的时候，把原来的连接全部中断？

**Comment by lleeopen** [comment]
> 更换代理后中断链接：意思是在切换配置文件的时候，把原来的连接全部中断？

就是更换代理或者配置切换更新更改的时候，中断旧的链接

**Comment by 2dust** [comment]
配置切换理解了。
更换代理是指哪个操作？

**Comment by lleeopen** [comment]
> 配置切换理解了。 更换代理是指哪个操作？
更换代理，指的是手动更换，比如我现在用的香港节点，然后手动换了个美国节点，中断以前的链接

**Comment by 2dust** [comment]
是否不需要增加一个设置选项了，按逻辑应该都要关闭连接才合理

**Comment by lleeopen** [comment]
> 是否不需要增加一个设置选项了，按逻辑应该都要关闭连接才合理

这样也可以，添加一个这样能选项功能

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.7
配置更改或重载时会断开所有连接
