### ISSUE TITLE
现在内存占用太大了希望挂后台的时候有后台模式减少内存占用

### ISSUE THREAD

**Issue by iswlt** [2dust/clashN#156]
cfw都有类似模式好像是叫便携模式，显示面板的时候内存占用大无可厚非，挂后台之后就只有20多的占用了。自动更新设置没看懂怎么搞，能不能更直观简单一点。还有就是字体太辣眼睛了，既然要追求美观其实看以参考一下yacd

**Comment by 2dust** [comment]
内存占用暂时无法解决
