### ISSUE TITLE
开启后10秒自动关闭界面不好吧？

### ISSUE THREAD

**Issue by being123321** [2dust/clashN#158]
开启软件后10秒自动关闭界面，刚好在调参数呢？就自动关闭了。能不能改成开机自启没有任何操作后10秒自动关闭？不然还在设置呢，界面自动关闭了

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.8
改成1s内隐藏窗口，如果您想快捷开窗口可以设置全局热键
