### ISSUE TITLE
其实1.x的界面挺好的，现在反而不如cfw

### ISSUE THREAD

**Issue by SESProMax** [2dust/clashN#161]
个人意见，不喜请关。

**Comment by 2dust** [comment]
感谢提出意见
请问您觉得1.x的界面有哪些优点？
我们可以改进

至于开发工具改成WPF，也是一个尝试

**Comment by SESProMax** [comment]
﻿
主要是界面操作简洁，与v2一脉相承。虽然UI比较复古，但是对于一款工具而言对颜值的要求真不高，稳定好用就行了。现在迁移到wpf上不是说不好，但是这种现代化的UI设计费时费力，什么间距啊圆角啊图标之类的要做到优雅比较困难，而且隔壁已经用electron做了好久了，我是觉得没必要在来个雷同的了。不过也不排除今后设计改进。
最后还是建议突出一下特色。而且感觉现在做软件electron是趋势，做原生的话为什么不试试winui3呢（虽然也不火）
全部仅个人意见，仅供参考。希望N项目越来越好！

在 2022年10月25日，20:13，2dust ***@***.***> 写道：

﻿

感谢提出意见
请问您觉得1.x的界面有哪些优点？
我们可以改进

至于开发工具改成WPF，也是一个尝试

**Comment by 2dust** [comment]
因为winform确实在主题颜色和高分屏上已经无法优化，所以才尝试用wpf。
wpf的UI熟悉了后也不是很费时间，缺点最大的是内存占用高了些；有精力慢慢优化，比如增加快捷键来加快操作等。
winui3/maui等暂时不考虑，确实还不成熟。

感谢您的意见，如果您能针对具体的操作提出详细的改进就更好了
