### ISSUE TITLE
win11 tun模式可能会选中例如Zerotier的其他接口，导致无法上网

### ISSUE THREAD

**Issue by Rashhz** [2dust/clashN#162]
如题，tun模式在启动时可能会选中例如Zerotier的其他虚拟网卡，导致无法上网

**Comment by 2dust** [comment]
这个你需要反馈给core https://github.com/MetaCubeX/Clash.Meta

**Comment by Rashhz** [comment]
> 这个你需要反馈给core https://github.com/MetaCubeX/Clash.Meta

好的
