### ISSUE TITLE
[功能请求] 暗色标题栏

### ISSUE THREAD

**Issue by FrzMtrsprt** [2dust/clashN#165]
暗色状态下，窗口标题栏仍为亮色，不是很美观，希望能在暗色模式下让标题栏也是暗色。

<img width="444" alt="截图" src="https://user-images.githubusercontent.com/15852717/198783706-ade61680-97e6-4c37-a84c-73fc4d7195d7.png">

**Comment by 2dust** [comment]
标题栏是可以随windows主题设置变化的，所以不需要变成暗色
