### ISSUE TITLE
请教，我的浏览器的谷歌翻译无法使用，如何解决？

### ISSUE THREAD

**Issue by zhl111** [2dust/clashN#167]
我用v2rayN就能正常使用，而这个clashN则不行。我的代理每种方式都尝试过了，似乎在升级2.7之前我设置自动代理系统模式还能用……

**Comment by fyhzc** [comment]
me too

**Comment by 2dust** [comment]
谷歌翻译的域名是否加入到规则了？

**Comment by 2dust** [comment]
和clashN无关，是您的clash配置文件中是否有这样的规则？
如果是机场请找机场解决

**Comment by 2dust** [comment]
clashN没有自带规则
clash的规则都是在配置文件中，这个配置文件机场提供的
v2rayN的规则是客户端提供，和机场无关

**Comment by LiSircxy** [comment]
使用http代理的话就会好使 使用本机127.0.01

**Comment by firefox1900** [comment]
mixin编辑添加
prepend-rules:
  - "DOMAIN-SUFFIX,translate.googleapis.com,\U0001F530 节点选择"
