### ISSUE TITLE
订阅转换问题

### ISSUE THREAD

**Issue by Yzcloud** [2dust/clashN#169]
订阅转换经常性抽风更新不了，不转换就能更新，能否设置多个

**Comment by 2dust** [comment]
在本機上架設一個呢？

**Comment by Yzcloud** [comment]
本地的模板不是很好用，自己也不是很懂怎么更改

**Comment by 2dust** [comment]
https://acl4ssr-sub.github.io/
https://id9.cc/
你看这两个服务，你测试下哪个后端你用着最快，然后把这个后端地址配置到clashn中使用

**Comment by t-o-n-y-w** [comment]
本机架设的 有的可以更新 有的更新不出来 这是啥情况？

**Comment by 2dust** [comment]
> 本机架设的 有的可以更新 有的更新不出来 这是啥情况？

本机的可以看转换服务的日志
