### ISSUE TITLE
当前代理页的代理组与代理节点的组件样式

### ISSUE THREAD

**Issue by abtswath** [2dust/clashN#172]
![image](https://user-images.githubusercontent.com/31396419/199691075-8744517e-532e-41dc-a37c-657bffca7178.png)

代理组与代理节点的组件样式太过相似，不太好分辨

**Comment by 2dust** [comment]
一个在最左边，一个在右边
请问改进的UI建议？

**Comment by abtswath** [comment]
主要是这俩组件用了同一个样式，间距啥的都差不多，确实一下子没分清。
如果是多 tab 页的形式或者折叠面板的形式会不会好一些？
![image](https://user-images.githubusercontent.com/31396419/200104146-a3ead079-e842-447c-bc8b-1f379607b545.png)
![image](https://user-images.githubusercontent.com/31396419/200104166-c82346ae-8113-4727-ae20-9109a30a56c1.png)
仅仅是提个建议哈，因为我没用过 C#，不太清楚是否方便实现

**Comment by 2dust** [comment]
tab不合适，显示的信息不足。
折叠的话上下拉动就太长了，大部分配置的分组内节点都差不多。
现在样式确实一样，但是一个在最左边习惯了就好

**Comment by FrzMtrsprt** [comment]
可以给代理组列表添加滚动条，方便操作也便于区分

卡片的边距可能还需要调整一下

<img width="666" alt="image" src="https://user-images.githubusercontent.com/15852717/200125839-a9b05341-ba8e-402a-b404-dbb4d36f560a.png">

**Comment by 2dust** [comment]
分组增加个常在滚动条容易，下一版本改进看看效果

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.10

**Comment by Aslaninaser** [comment]
vmess://eyJhZGQiOiI2NS4yMS4yNDUuMjMiLCJhaWQiOiIwIiwiaG9zdCI6IiIsImlkIjoiNmI3Y2JjNDEtZmI4MC00MWE4LThlYjYtYjViZGIwZTg2MTQ3IiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiI0NDMiLCJwcyI6IkBpUHJveHlNZWxpIDog2LPYsdmI2LHZh9in24wg2KjbjNi02KrYsSIsInNjeSI6ImF1dG8iLCJzbmkiOiIiLCJ0bHMiOiIiLCJ0eXBlIjoiaHR0cCIsInYiOiIyIn0=
