### ISSUE TITLE
能否添加一个 重新载入pac文件的按钮

### ISSUE THREAD

**Issue by t-o-n-y-w** [2dust/clashN#174]
能否添加一个 重新载入pac文件的按钮
每次修改pac文件后 都需要重启clashN
感觉有些麻烦呢

**Comment by 2dust** [comment]
现在系统代理模式切换一下就可以重新载入
后面考虑实现

**Comment by 2dust** [comment]
重新检查了下，点击左上角的重载按钮会重新读取硬盘文件并重启pac
