### ISSUE TITLE
不显示节点，但是可以正常访问网络

### ISSUE THREAD

**Issue by mingchau** [2dust/clashN#177]
![image](https://user-images.githubusercontent.com/18564039/200509060-b5e41205-aebb-4e78-a07f-02ffe02d6082.png)
![image](https://user-images.githubusercontent.com/18564039/200509213-8aee15c3-5988-48a4-a1c9-53c694c9f3cc.png)
![image](https://user-images.githubusercontent.com/18564039/200509112-fcd55d14-512f-408d-886e-4ee5de5a6195.png)

**Comment by 2dust** [comment]
可以把配置发下 captainIronng@protonmail.com

**Comment by 2dust** [comment]
使用你的配置文件测试显示正常
您重启下clashN，左上角的刷新点击几次看看是否有

**Comment by mingchau** [comment]
> 使用你的配置文件测试显示正常 您重启下clashN，左上角的刷新点击几次看看是否有

重启clashN甚至重装了都不行啊，刷新会重新生成`guiNConfig.json`和`config.yaml`，但是节点还是不显示。  
“当前连接”页面也是空白的。
![image](https://user-images.githubusercontent.com/18564039/200845996-f97859ab-b9d7-46c4-83d7-2e746cbe9c72.png)
![image](https://user-images.githubusercontent.com/18564039/200846049-7b3b838e-30eb-4b36-b482-84ce664f91bb.png)

**Comment by mingchau** [comment]
今天竟然正常了，不知道是什么原因……
不知道是否是和clash for windows有什么冲突？昨天把clash for windows的TUN和服务模式给关了，今天就好了。
当然用clashN的时候cfw都是关着的。

**Comment by 2dust** [comment]
那应该是clash API端口被占用了，你把clashN里面的API端口修改成其他的

**Comment by yoholo** [comment]
我也这样，暂时修改端口没用，先重启一下试试
