### ISSUE TITLE
"下列字符开头的地址"是什么意思？我这样填写是正确的吗？

### ISSUE THREAD

**Issue by QyhOfficial** [2dust/clashN#179]
![image](https://user-images.githubusercontent.com/108882720/200750203-0c4f0602-de9d-4ed6-9eb9-1442c38aa0ad.png)

如图，我想要这三个域名走直连，这样填写正确吗？

**Comment by 2dust** [comment]
比如百度和163：*.baidu.com;*.163.com
用分号隔开
