### ISSUE TITLE
报错time="2022-11-15T13:53:49+08:00" level=fatal msg="Parse config error: rules[36] [RULE-SET,Unbreak,DIRECT] error: 

### ISSUE THREAD

**Issue by javatianyufei** [2dust/clashN#186]
time="2022-11-15T13:53:49+08:00" level=fatal msg="Parse config error: rules[36] [RULE-SET,Unbreak,DIRECT] error: 
把链接拷贝到ClashN后，报上面的错误，上不了网，求大佬解决

**Comment by 2dust** [comment]
这个是clash core的提示内容，说明core报错了
请把错误信息详细的发出来
另外RULE-SET 需要clash p core才支持

**Comment by javatianyufei** [comment]
以下是完整的错误信息：
clash_subscription
启动服务(2022/11/17 10:43:45)...
Core类型 clash
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🌎国际流媒体"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🎺Spotify"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🚩归属地更改"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🎈漏网之鱼"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇩🇪德国"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇯🇵日本"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider ⚓手动选择"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🌊Netflix"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider ☁️OneDrive"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 📺YouTube"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇹🇼台湾"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🔮Disney+"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇺🇳其他"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇺🇸美国"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇸🇬新加坡"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider 🇭🇰香港"
time="2022-11-17T10:43:45+08:00" level=info msg="Start initial compatible provider ❌广告拦截"
time="2022-11-17T10:43:45+08:00" level=fatal msg="Parse config error: rules[36] [RULE-SET,Unbreak,DIRECT] error: unsupported rule type RULE-SET"
2022/11/17 10:43:45 Change system proxy
2022/11/17 10:43:45 Set rule mode Rule->Rule
2022/11/17 10:43:45 Clash Proxies Latency Test
2022/11/17 10:44:27 Refresh Clash Proxies
2022/11/17 10:44:31 Refresh Clash Proxies
大佬，我原来用的是Clash For Windows，在Github上看到您的代码，想功能运行正常后进行学习，卡在功能这一块，我自己也再琢磨琢磨。

**Comment by javatianyufei** [comment]
对Clash的认知只停留在基本的使用上，有可能是我的使用方法有问题，我再找找问题

**Comment by 2dust** [comment]
` error: unsupported rule type RULE-SET"`
 RULE-SET 需要clash p core才支持，请去clash 那边下载p core更新到 bin/clash 目录
