### ISSUE TITLE
关于Proxy Provider的更新订阅问题

### ISSUE THREAD

**Issue by chensimmons** [2dust/clashN#187]
今天刚下载clashN，我是直接使用本地的Proxy Provider配置文件引入节点的，第一次使用时，右键单击配置文件然后更新全部订阅，成功出现了节点；
配置文件里的订阅链接是转换过的链接，使用subconverter做转换后端；
后面更新订阅时，看clashN和subconverter的日志，好像是没有更新到的。
**我想问问使用Proxy Provider时，是在哪里更新订阅的？**

<img width="526" alt="20221116134350" src="https://user-images.githubusercontent.com/31755429/202098702-94b5b12f-381e-475c-9fbe-e0051501776e.png">
<img width="676" alt="20221116134731" src="https://user-images.githubusercontent.com/31755429/202098758-e642b7bb-be9b-4553-8137-a193758595b2.png">

**Comment by 2dust** [comment]
Proxy Provider是core里面更新

**Comment by chensimmons** [comment]
> Proxy Provider是core里面更新

嗯嗯，那意思是Proxy Provider没有对应的更新订阅按钮？只能在core里自动更新？

**Comment by 2dust** [comment]
> > Proxy Provider是core里面更新
> 
> 嗯嗯，那意思是Proxy Provider没有对应的更新订阅按钮？只能在core里自动更新？

是的
