### ISSUE TITLE
在没有wifi的情况下，clasN能让电脑严重到不能自己

### ISSUE THREAD

**Issue by zhl111** [2dust/clashN#188]
也就是几乎无法操作电脑，只能重启。但clashN设置的是自动启动，重启后又进入死循环……可有解？

**Comment by 2dust** [comment]
能否看任务管理器，看资源被哪个进程占用？

**Comment by 2dust** [comment]
请看下guilog，发上来

**Comment by 2dust** [comment]
是这个文件，你上传下
另外配置文件也可以上传下，guiConfigs/guiNConfig.json

**Comment by 2dust** [comment]
@zhl111 配置文件已经删除了。
忘记和你说要去多敏感信息。
你可以去机场重置修改下订阅链接

**Comment by 2dust** [comment]
无法复现问题，能否提供更多信息

**Comment by SlimeNull** [comment]
没有 WiFi 是什么意思

**Comment by SlimeNull** [comment]
> 没有Wi-Fi的意思是，我去一个新的地址，网络不能识别出能用的网络的时候，就会出现的严重卡顿的现象

也就是说, 当计算机没有接入到任何可用的互联网时吗?
