### ISSUE TITLE
报毒

### ISSUE THREAD

**Issue by smilencecc** [2dust/clashN#19]
扫描了一下，报毒比较严重
![1](https://user-images.githubusercontent.com/77428601/163711340-52c42610-f5a8-4c7a-be15-f92ec0ced992.jpg)

**Comment by smilencecc** [comment]
> 扫描了一下，报毒比较严重 ![1](https://user-images.githubusercontent.com/77428601/163711340-52c42610-f5a8-4c7a-be15-f92ec0ced992.jpg)

也可能是杀软误报，希望能在下个版本稍微调整一下

**Comment by 2dust** [comment]
无法调整，您只能信任或不用
