### ISSUE TITLE
不需要使用compatible版meta内核时，仍采用了compatible meta内核

### ISSUE THREAD

**Issue by TwooSix** [2dust/clashN#190]
如图，在选择更新meta内核时，程序判断系统使用正常meta内核，下载并解压更新。但实际仍会跳出旧版的alpn错误提示。
实测是因为程序使用了目录下旧版的compatible内核导致，删除后可以正常加载配置
![image](https://user-images.githubusercontent.com/62167519/202498357-6eedb519-f305-4ecb-8328-db318bc1d5af.png)

**Comment by 2dust** [comment]
此问题已经解决，未发版本

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.10
