### ISSUE TITLE
希望log的筛选器能在当前log中立刻找出符合的字段，而不是在随后产生的log中

### ISSUE THREAD

**Issue by Rashhz** [2dust/clashN#192]
如题，目前log的筛选器对已产生的log没有筛选作用（这个是bug？），希望可以能对输入筛选器之前/之后的log都能立刻筛选出来

**Comment by 2dust** [comment]
目前功能就是这样，不是bug
因为目前的功能界面只是个文本框，暂时无法做到筛选历史

**Comment by Rashhz** [comment]
> 目前功能就是这样，不是bug 因为目前的功能界面只是个文本框，暂时无法做到筛选历史

噢噢，希望大佬考虑一下添加这个功能
