### ISSUE TITLE
TUN模式 遇到的问题 我在两台设备上 都安装了clashN 有一台是正常 有一台在TUN模式下 不显示节点

### ISSUE THREAD

**Issue by t-o-n-y-w** [2dust/clashN#195]
TUN模式 遇到的问题 我在两台设备上 都安装了clashN 有一台是正常 有一台在TUN模式下 不显示节点
但换成clash内核 就可以关闭tun模式 就可以显示节点

**Comment by t-o-n-y-w** [comment]
是不是对 网卡驱动有要求？？？

**Comment by 2dust** [comment]
给出配置文件 captainIronng@protonmail.com
