### ISSUE TITLE
TUN模式 clash-meta内核 更新订阅节点不出现 

### ISSUE THREAD

**Issue by t-o-n-y-w** [2dust/clashN#198]
TUN模式 clash-meta内核 更新订阅节点不出现 
已经是以管理员进行运行的clashN
查看 网络适配器 但没有发现TUN的虚拟网卡
之前在安装过 SSTap Netch这两款软件
查看 clashN 日志信息 也没有发现报错
附带一张截图
![image](https://user-images.githubusercontent.com/75150168/203271497-64bb2045-6b36-4a1d-8b06-1ad49916e0f0.png)

**Comment by 2dust** [comment]
先检查更新订阅后本地文件有没有产生？
如果有本地文件，设置中日志设为debug后重启看日志

**Comment by t-o-n-y-w** [comment]
日志文件如何修改 说一下 步骤

**Comment by t-o-n-y-w** [comment]
更新后 可以尝试配置文件

**Comment by t-o-n-y-w** [comment]
没打开mixin  日志内容 
DEBUG 由于目标计算机积极拒绝，无法连接。（127.0.0.1:9090)
ERROR system.NET.Sockets.SocketsException: 由于目标计算机积极拒绝，无法连接。

**Comment by t-o-n-y-w** [comment]
有的时候 还提示
DEBUG THE operation was canceled
DEBUG System.threading.tasks.taskcanceledexception: the operation was canceled.
ERROR System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已终止I/O操作。

**Comment by 2dust** [comment]
看起来你的9090端口被占用了，在设置中修改API端口为其他的

**Comment by t-o-n-y-w** [comment]
更改端口后 还是不行 还是提示
DEBUG 由于目标计算机积极拒绝，无法连接。（127.0.0.1:9090)
ERROR system.NET.Sockets.SocketsException: 由于目标计算机积极拒绝，无法连接。

**Comment by t-o-n-y-w** [comment]
更新订阅 在guiConfigs 可以看到产生的文件 但在 clashN打开后 就是不显示

**Comment by 2dust** [comment]
把你配置文件发到 captainIronng@protonmail.com

**Comment by t-o-n-y-w** [comment]
已经发送给邮箱 请查收

**Comment by jas0nma** [comment]
同样出现此问题，TUN/clash-meta内核，重启电脑后当前代理页面空白，没有任何订阅节点，使用的最新2.11版本。

**Comment by t-o-n-y-w** [comment]
感觉应该是 clash-meta内核的原因 使用抽拉式-p的 内核就可以

**Comment by t-o-n-y-w** [comment]
感觉应该是 clash-meta内核的原因 使用抽拉式-p的 内核就可以
之前在 clash-meta官方频道 反馈 但 回复确实 有可能是 clashN的问题 就不了了之啦

**Comment by 2dust** [comment]
要看下消息页面的日志内容，是否有信息
把日志等级设为debug

**Comment by abtswath** [comment]
我也出现了这个问题，但是排查后发现是我更换订阅后机场配置不同，然后下载的本地配置文件中 proxies 也不同，导致 mixin 中 prepend-rules 里面有些规则使用的代理名称不存在
日志中会有报错信息
```
time="" level=fatal msg="Parse config error: rules[0] [DOMAIN,sm.ms,Proxies] error: proxy [Proxies] not found"
```
你们可以排查下是不是由于类似的问题导致的

**Comment by t-o-n-y-w** [comment]
clash-meta是不是对电脑硬件有要求 有一台电脑 clash-p 跟 clash-meta 的tun模式都可以用
另外一台电脑 只能用 clash-p的tun模式
