### ISSUE TITLE
有些机场的自带clash订阅无法使用，clash内核和clash-mate内核有什么区别啊？怎么使用wintun模式

### ISSUE THREAD

**Issue by being123321** [2dust/clashN#2]
如题！

**Comment by being123321** [comment]
clash-mate也无法使用

**Comment by layou233** [comment]
Clash.Meta 是 clash 的一个非官方分支，在 clash 基础上还实现了一些 clash premium 才有的功能，比如 tun。而且在 tun 这方面，clash premium 需要手动下载wintun.dll，而 Clash.Meta 做到了内置。  
对于一部分来说，Clash.Meta 更重要的功能是 **支持 XTLS** （VLESS/Trojan XTLS）  
Clash.Meta 功能介绍见他仓库的release  
注意他是meta不是mate，是 `Clash.Meta` 而不是 `clash-meta`（这个拼写和clash不一样，他是首字母大写的，估计作者有强迫症）

**Comment by 2dust** [comment]
时间有限，功能会慢慢增加
wintun模式在计划中

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.1
