### ISSUE TITLE
不显示Hysteria协议节点

### ISSUE THREAD

**Issue by kmxuzhi** [2dust/clashN#200]
只有Trojan节点显示，Hysteria协议节点不显示。
同样的订阅地址，在Clash Meta forAndroid上就能够显示。

**Comment by zheshidingxiaoke** [comment]
同问

**Comment by 2dust** [comment]
hi，请把配置文件发到
captainIronng@protonmail.com

**Comment by kmxuzhi** [comment]
> 

已发

**Comment by 2dust** [comment]
请把订阅更新后的clash配置文件发过来

**Comment by kmxuzhi** [comment]
> 

哪个配置文件？发给你邮箱的配置文件里面有订阅地址的。

![Screenshot_20221129_213811_com github metacubex clash meta](https://user-images.githubusercontent.com/64294572/204543537-f3270171-00bc-464d-a741-19d3be1290c0.jpg)
这是手机上同样订阅的节点

**Comment by 2dust** [comment]
是订阅问题，
编辑订阅，在User agent框填入ClashMeta
