### ISSUE TITLE
clashN与onedrive的兼容性问题

### ISSUE THREAD

**Issue by fredericky123** [2dust/clashN#202]
开启clashN 再打开onedrive，则无法同步，顺序反过来是可以同步的
请问如何解决呢？
网上有很多关于回环的设置是针对clash for windows的，clashN怎么设置呢
另外，tun再ClashN下如何开启呢

**Comment by 2dust** [comment]
设置，clashn页面有回环设置
tun在配置文件中可以选择，使用meta core

**Comment by fredericky123** [comment]
好像是得把所有微软相关的回环都排除？要这么操作么？会不会太暴力了
