### ISSUE TITLE
无法访问纯ipv6网站

### ISSUE THREAD

**Issue by yunyuyuan** [2dust/clashN#204]
日志是`error: couldn't find ip`。版本V2.10，之前用clash for windows配合clash premium可以访问ipv6。用clashN和clash.meta无法访问，设置里开启了ipv6，是clash.meta的问题吗。

**Comment by 2dust** [comment]
配置中更换到clash p core试一试？如果可以那您反馈到clash.meta

**Comment by yunyuyuan** [comment]
@2dust 刚试了下换clash premium可以访问ipv6，但是设置里更新不能自动获取premium的url啊
![image](https://user-images.githubusercontent.com/45785585/206858375-a7c480d3-d616-41d0-8a88-2a4fd19e0c0e.png)

**Comment by 2dust** [comment]
升级clashN 2.11，已经内置p core  https://github.com/2dust/clashN/releases/tag/2.11

**Comment by yunyuyuan** [comment]
@2dust 好的，谢谢！
