### ISSUE TITLE
按照下载速度排序貌似不行

### ISSUE THREAD

**Issue by yunyuyuan** [2dust/clashN#207]
![image](https://user-images.githubusercontent.com/45785585/207316993-3067a46d-227b-4815-8636-1650017bb525.png)
按照下载速度排序，与实际的不符。另外这里的select好像没保存？我选择**下载速度**，切到其他界面再切回来，这里又变成了**时间**

**Comment by yunyuyuan** [comment]
而且如果连接多了（例如steam下载，会有很多cdn的连接），软件界面会很卡

**Comment by 2dust** [comment]
此界面目前没有显示速度，你看到的是箭头数据是流量。
选项没有保存这个无法复现，是不是因为你那边太卡导致没有切换过去？

**Comment by 2dust** [comment]
此界面10s刷新一次，刷新的时候只是把数据绑定到了界面，并没有其他特别的操作
你那卡到什么程度？

**Comment by yunyuyuan** [comment]
@2dust 好像是的，太卡了导致没切换过去。有200个链接的时候（开几个直播间，或者多线程下载），刷新的时候就会卡死1秒左右，整个界面unresponsive，应该是数据量太大了

**Comment by 2dust** [comment]
200多链接明白了，等处理

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.12
