### ISSUE TITLE
yaml更新的代理无法及时展示到代理标签中

### ISSUE THREAD

**Issue by raknascute** [2dust/clashN#208]
v2.10~v2.11

普通(非tun) + clash_meta

测试了几种情况,,分别手动修改本地的proxies字段,以及proxy-groups,保存之后软件无反应,切换到另一个yaml再切换回来依然无效.从远程更新配置也是不行,只能关掉重开,这样才会完整识别新的变更,请求修复.

另外流量统计不知道能不能给出上和下分开的统计选择,现在只有一起的,有时候想要一些精确的数据(不清楚流量上限是怎么判断的,始终是正无穷).

**Comment by 2dust** [comment]
首先注意不要修改N生成的config.yaml，而是编辑本地文件。
本地文件确定保存后，可以点击左上角的重新加载按钮刷新，应该会重新载入配置文件。
如果这样操作后不行，请看下日志是否有刷新

**Comment by 2dust** [comment]
流量统计主要还是界面问题，不好显示。
流量上限是从订阅那边抓取，如果不是订阅的则显示无穷

**Comment by staex** [comment]
远程的proxy provider不会更新，重启也不行。log里显示本地文件太旧，需要更新，同时还显示provider的url按规则需要通过代理，但实际上却没有更新。不如单独提供一个更新provider的功能，包括proxy和rule set，这样可以手动更新。

**Comment by 2dust** [comment]
大概明白了，你是修改和provider相关的
而provider是由core调用更新的，gui无法控制。
点击按钮刷新的时候，clashN是调用core的API更新配置文件，可能是core那边没有处理

**Comment by taptictop** [comment]
实测手动reload core确实可以,不知道这个是否应该做成更新后自动reload的逻辑(不过这样是有个会断连的问题)

![image](https://user-images.githubusercontent.com/67857702/208065354-2b5ce9fc-9242-488f-9be1-fa760d570fce.png)
这个显示也许可以优化一下吧,时间都盖住了

不知道应该加什么字段才可以打开流量上限功能?试用了一个机场,导入他提供的clash模板,也没有让上限启用
