### ISSUE TITLE
提一点小建议

### ISSUE THREAD

**Issue by BaronChushao** [2dust/clashN#209]
1.把tun模式单独做成一个开关，现在开关tun模式有点不方便（这个可能和内核有关？不知道可不可以）
2.在最左侧的选项栏里添加一个“规则”，就是可以直接显示配置文件里的所有规则，便于查看
3.日志信息每一条可以用方框框起来，反正日志信息位置很大，让日志看起来更加简洁。现在日志信息界面很大，然后整一面密密麻麻的字，看的眼睛疼。

**Comment by BaronChushao** [comment]
@2dust

**Comment by 2dust** [comment]
最近在更新v2rayN，等有空来处理

**Comment by BaronChushao** [comment]
好的好的

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.12
处理了1
其他暂时不处理

**Comment by pony720** [comment]
我理解TUN模式，应该具有电脑所有程序都可通过clash代理科学上网，当我打开clashN的tun开关后，并未发现电脑内除浏览器外的应用能够科学上。普通clash for win让所有应用全部代理是先下载服务模式（绿色球），打开tun开关即可。作者clashN没有相关方面使用办法，对于我普通用户无法理解打开tun后的作用。如果clashN没有上述功能，请告知。多谢 。

**Comment by 2dust** [comment]
> 我理解TUN模式，应该具有电脑所有程序都可通过clash代理科学上网，当我打开clashN的tun开关后，并未发现电脑内除浏览器外的应用能够科学上。普通clash for win让所有应用全部代理是先下载服务模式（绿色球），打开tun开关即可。作者clashN没有相关方面使用办法，对于我普通用户无法理解打开tun后的作用。如果clashN没有上述功能，请告知。多谢 。

> 

请单独开issue
