### ISSUE TITLE
订阅转换地址相关

### ISSUE THREAD

**Issue by ueyome** [2dust/clashN#210]
默认本地地址
http://127.0.0.1:25500/sub?target=clash&url={0}

如果后面添加外部配置则无效
http://127.0.0.1:25500/sub?target=clash&url={0}&config=clash.ini

转变的配置好像绑死https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini

**Comment by 2dust** [comment]
等待处理

**Comment by hdy331** [comment]
你是否使用subconverter做的转换？那个默认神机规则ACL4SSR，和ClashN无关。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.12

**Comment by t-o-n-y-w** [comment]
2.12版本 不打开subconverter 也能更新成功 啥情况 我选择的 本地转换的
