### ISSUE TITLE
小白提问 为啥小米手机能连上但是翻不出去。。。

### ISSUE THREAD

**Issue by maocafe29** [2dust/clashN#214]
小米咋回事啊 v2rayNG和clash都试了，测速也能显示数值，可是就是翻不出去。。。
手机型号：Redmi Note 9 Pro
系统：MIUI 12.0.11

![498b59014e783ef61a28c8f9912be0e](https://user-images.githubusercontent.com/105865537/210833040-d9f639d7-67a9-44ea-868b-38168c4fcb74.jpg)
![274dd62e8a3e4df92fe60c846ea26ef](https://user-images.githubusercontent.com/105865537/210833242-f53d3a3d-6e5d-4c9d-8d77-b9f5b0563456.jpg)
![b66bf65368fc7bd4fbcb2198ba52972](https://user-images.githubusercontent.com/105865537/210833312-b68219b8-006d-44a9-9358-f2ee6d3d31bf.jpg)

**Comment by maocafe29** [comment]
更新 我发现好像是只有gg不行，gg国内url好像改了？其他网站正常

**Comment by 2dust** [comment]
您可以去clash for Android 提交

**Comment by tdjnodj** [comment]
这种时候就把网址换成 www.google.com.hk 应该就行了
