### ISSUE TITLE
 type: hysteria 这类节点导入无法使用

### ISSUE THREAD

**Issue by July2099** [2dust/clashN#216]
type: hysteria 这类节点导入无法使用。不显示节点！

日志提示：
配置成功
 type: hysteria@2023/1/7
启动服务(2023/1/7 22:46:39)...
Core类型 clash_meta
2023/1/7 22:46:41 Change system proxy
2023/1/7 22:46:41 Set rule mode Rule->Rule
2023/1/7 22:46:41 Clash Proxies Latency Test

**Comment by 2dust** [comment]
请检查配置文件中是否有hysteria 节点

**Comment by jacklee789** [comment]
订阅链接有vmess和hysteria 节点，在clash-verge都可以用

但在clashn中不显示hysteria 节点，只有vmess节点。clashnv2.13版本，clash-meta内核

**Comment by jacklee789** [comment]
> 订阅链接有vmess和hysteria 节点，在clash-verge都可以用
> 
> 但在clashn中不显示hysteria 节点，只有vmess节点。clashnv2.13版本，clash-meta内核

看了之前的问题解答https://github.com/2dust/clashN/issues/200
目前的操作是：
1，导入订阅链接并更新，只有vmess节点，没有hysteria节点
2，编辑订阅，在User agent框填入Clash_Meta,再次更新订阅，可以显示hysteria节点了
虽然成功了，但感觉这是一个bug

**Comment by 2dust** [comment]
是因为订阅源那边做了控制
当更新订阅UA包含Meta时会返回hy节点给你

**Comment by jacklee789** [comment]
能否内核为clash-meta时，User agent框自动设置为Clash_Meta
这样就不需要人工操作了，谢谢
