### ISSUE TITLE
如何设置translate.googleapis.com走代理 config.yaml文件 默认是走直连 不走代理

### ISSUE THREAD

**Issue by t-o-n-y-w** [2dust/clashN#224]
如何设置translate.googleapis.com走代理
我尝试修改 config.yaml这个文件
删除 - "DOMAIN,translate.googleapis.com,\U0001F3AF 全球直连" 这一行 保存后
打开clashN后 config.yaml又自动还原啦

**Comment by 2dust** [comment]
配置文件-编辑本地文件-修改保存
