### ISSUE TITLE
有没有办法保留上次退出时选择的分组

### ISSUE THREAD

**Issue by ttlttc** [2dust/clashN#225]
自己写的配置有多个分组,对应不同的服务商,都是select手动模式,在不同用处的时候自行切换.目前的问题是每次打开后软件都会默认选择分组1进行连接,添加了interval:-1也不起作用,不知道是不是自动刷新那个功能带来的?而且这个也关不掉,软件每次打开都是ON的状态
![image](https://user-images.githubusercontent.com/67857702/215935402-378d648c-5a7f-4883-a074-b1bc12a8284b.png)

设置里面都自己改了
![image](https://user-images.githubusercontent.com/67857702/215935298-41618a20-b595-40b2-b355-375c3e851796.png)

**Comment by haakuya** [comment]
同遇到此问题，表现在加载的情景为默认的自动选择，但是显示的是上次调整到全局模式的节点
