### ISSUE TITLE
tun?打开了，并不是所有应用程序都能科学上网，比如安卓模拟器。

### ISSUE THREAD

**Issue by pony720** [2dust/clashN#226]
我理解TUN模式，应该具有电脑所有程序都可通过clash代理科学上网，当我打开clashN的tun开关后，并未发现电脑内除浏览器外的应用能够科学上。普通clash for win让所有应用全部代理是先下载服务模式（绿色球），打开tun开关即可。作者clashN没有相关方面使用办法，对于我普通用户无法理解打开tun后的作用。如果clashN没有上述功能，请告知。多谢 。

**Comment by pony720** [comment]
普通clash for win先下载服务模式（绿色球），打开tun开关后。安卓模拟器就能够科学上网。

**Comment by t-o-n-y-w** [comment]
clash.Meta-core  clash p core我都试过啦 不起作用 但 产生虚拟网卡 显示已连接

**Comment by yifanlong** [comment]
![IMG20230203191718.jpg](https://user-images.githubusercontent.com/100976327/216590397-c922f92a-2da2-4035-a40b-25a1f1a50f55.jpg)

我这是什么情况😭

**Comment by SinnoSong** [comment]
@yifanlong 你的问题应该是在安装服务时出现问题，可以尝试重新安装服务。
