### ISSUE TITLE
改的字体还不如以前好

### ISSUE THREAD

**Issue by wilsonjor** [2dust/clashN#227]
改的字体还不如以前效果好，Windows，建议还是默认字体

**Comment by raknascute** [comment]
这样倒是能让原先挤出去的文字显示完整了,界面改不了那只能这样了

**Comment by Duck-Deng** [comment]
为什么不使用微软雅黑？Windows上渲染思源黑体作为UI字体实在难看，锯齿很多

**Comment by 2dust** [comment]
等待处理，将会改成和v2rayN一样，可以设置

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.14
