### ISSUE TITLE
2.13版本 TUN模式貌似不起作用 内核是clash_premium

### ISSUE THREAD

**Issue by t-o-n-y-w** [2dust/clashN#228]
2.13版本 TUN模式貌似不起作用 内核是clash_premium

**Comment by 2dust** [comment]
看日志输出

**Comment by t-o-n-y-w** [comment]
我用另外一个设备 用clash.mate内核 也是不起作用 但虚拟网卡 显示已连接 
我用2.11版本 tun模式 就正常

**Comment by t-o-n-y-w** [comment]
日志信息：只输出了已下信息

2023/2/2 21:53:11 Change system proxy
2023/2/2 21:53:11 Set rule mode Rule->Rule
2023/2/2 21:53:11 Clash Proxies Latency Test
2023/2/2 21:53:11 Refresh Clash Proxies
2023/2/2 21:53:27 Refresh Clash Proxies

**Comment by t-o-n-y-w** [comment]
2.12版本 我刚刚也测试啦 也是 与 2.13版本 一样  tun模式 无法使用
2.11版本 可以使用tun模式

**Comment by 2dust** [comment]
用管理员权限启动了吗？

**Comment by t-o-n-y-w** [comment]
是管理员权限启动的
