### ISSUE TITLE
当前代理和当前连接显示空白，但是代理有效的， 可以科学上网。

### ISSUE THREAD

**Issue by gooppo** [2dust/clashN#232]
更新订阅，订阅的本地配置文件也一切正常。
![image](https://user-images.githubusercontent.com/26872119/217715564-b98c621b-ed4b-446e-9df0-8dbd72c183b1.png)
![image](https://user-images.githubusercontent.com/26872119/217715643-51cea0a5-bd06-4841-8385-07af6e0088d7.png)

**Comment by 2dust** [comment]
api端口9090被占用了，在设置中修改下
