### ISSUE TITLE
字体渲染优化建议

### ISSUE THREAD

**Issue by Duck-Deng** [2dust/clashN#234]
现在字体改成了“思源黑体”，但这个字体用来UI显示不够清晰，有些字还有锯齿。为什么不直接用微软雅黑？这样也不需要嵌入一个字体包了，显示效果也更好

**Comment by SlimeNull** [comment]
同意

**Comment by 2dust** [comment]
计划中
等待下

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.14
