### ISSUE TITLE
[Feature Request] 在设置里可以更改延迟测试URL

### ISSUE THREAD

**Issue by kouhe3** [2dust/clashN#235]
目前clashN的设置里没有这个选项。测试默认用的是配置文件里的URL. 比如  gstatic.

希望添加的功能：在设置里可以更改 URL TEST 的 url.

![image](https://user-images.githubusercontent.com/25522053/218305242-8f5e061e-ce7d-45d2-a563-04faef650bc7.png)

**Comment by 2dust** [comment]
关闭
打开文件\guiConfigs\guiNConfig.json
找到 speedPingTestUrl
修改保存重启
