### ISSUE TITLE
界面优化建议 (颜色, 滚动条, 布局, 控件)

### ISSUE THREAD

**Issue by SlimeNull** [2dust/clashN#236]
1. 颜色建议使用与 LOGO 同步的蓝色主题色, 另外还需要注意当某些背景色改变为深色的时候, 前景色也需要变更为浅色 (例如当前代理和配置文件中的 "item" 被选中的时候, 现在背景是深紫色, 而前景色还是黑色, 不雅观)
2. 默认的 WPF 滚动条 + 更改过的控件, 有些违和, 建议将滚动条的样式优化一些, 例如使用圆角
3. 程序主内容没有足够的 Padding, 内容与左侧菜单靠的太近, 影响美观, 可以参考 Fluent Design 中对边距的规范, 也可以参考 Clash for Windows 中主内容布局.
4. 菜单似乎使用了一个类似于 ToolStrip 的控件,,, 这东西在左边有几个点用来移动, 然而在 clashN 中, 显然它不需要被移动, 所以, 最好换掉它, 使用别的控件来装菜单按钮

另外, 某些地方似乎并没有保持正确的圆角, 例如上面提到的菜单, 因为这个菜单不是顶靠标题栏的, 所以它应该有一个和其他控件一样的圆角, 这样也比较美观.

**Comment by SlimeNull** [comment]
我 clone 下来的仓库没办法 build, 导致很多代码提示都没有

**Comment by SlimeNull** [comment]
在改了在改了, 现在还有个问题, 我在把主题色改为蓝色的时候, Material Design 库给它安排的是: "蓝色背景时, 使用黑色字体", 我觉得不好看, 你觉得这个如何改掉

**Comment by 2dust** [comment]
> 在改了在改了, 现在还有个问题, 我在把主题色改为蓝色的时候, Material Design 库给它安排的是: "蓝色背景时, 使用黑色字体", 我觉得不好看, 你觉得这个如何改掉

主题颜色用户可以自己改，可以不必一定是蓝色的。

**Comment by 2dust** [comment]
2.3.4点可以先优化

**Comment by SlimeNull** [comment]
> > 在改了在改了, 现在还有个问题, 我在把主题色改为蓝色的时候, Material Design 库给它安排的是: "蓝色背景时, 使用黑色字体", 我觉得不好看, 你觉得这个如何改掉
> 
> 主题颜色用户可以自己改，可以不必一定是蓝色的。

我觉得 ClashN 的默认主题最好还是蓝色, 而且我找了找, 似乎并没有用户自定义主题色的功能

**Comment by SlimeNull** [comment]
那个 ToolBar 我也不知道弄什么替代比较好了, 就是前面那几个点, 用来移动位置的那个, 感觉太丑了

**Comment by SlimeNull** [comment]
我感觉主功能分开比较好, 最核心的部分弄成一个 `dropdown select` 属实有点奇怪, 分成两个开关, 一个是 "Enable Proxy", 另一个是 "Enable PAC Mode"

![image](https://user-images.githubusercontent.com/69663231/219544844-ab06f0c0-7fe3-4a18-a1cb-89577c734a43.png)

**Comment by 2dust** [comment]
> 我感觉主功能分开比较好, 最核心的部分弄成一个 `dropdown select` 属实有点奇怪, 分成两个开关, 一个是 "Enable Proxy", 另一个是 "Enable PAC Mode"
> 
> ![image](https://user-images.githubusercontent.com/69663231/219544844-ab06f0c0-7fe3-4a18-a1cb-89577c734a43.png)

功能请暂时不变动，再开issue讨论
pr时请分批

**Comment by SlimeNull** [comment]
还有就是, 建议为项目启用 Discussion, 这样可以讨论一些 "小问题", 就不用特地开 issue 了
