### ISSUE TITLE
请推送完整的项目

### ISSUE THREAD

**Issue by SlimeNull** [2dust/clashN#238]
我注意到在 ClashN 中引用了 PacLib... 而这个项目是往外, 往外, 往外, 然后找到 v2rayN... 显然这个项目并不在当前仓库中, 这导致我们 fork 下来的话, 没办法编译, 除非手动去下载 PacLib 之类的, 但这可能破坏项目的结构

我还是建议在一个仓库中, 放完整的, 能够直接编译的项目. 或者, 如果有更好的解决方案, 也可以, 总之, 这一点需要解决.

**Comment by 2dust** [comment]
PacLib将公用
请给个建议，这种情况如何维护？

**Comment by SlimeNull** [comment]
我也没有非常好的建议, 但大概有这些思路:

1. PacLib 弄成 nuget 包, 扔到 nuget 上, 这样至少编译不会有问题, 只是不能看 PacLib 的源码
2. ClashN 和 v2rayN 弄到同一个仓库
3. 嵌套的git仓库, 例如你在 v2rayN 那边的项目有一个 PacLib, 这边 clashN 也应该有一个, 如果 v2rayN 的 PacLib 得到了更新, 将它推送到 github, 然后 clashN 这边再从 github 拉取 (这个是个不错的想法, 当然, 你本地部署 git 服务器也可以

**Comment by FrzMtrsprt** [comment]
可以考虑把 PacLib 放到独立的仓库中，然后在 v2rayN 和 ClashN 中添加 PacLib 作为 Git 子模块

实在不行的话干脆把 v2rayN 整个作为 Git 子模块添加进 ClashN 里也可以

**Comment by SlimeNull** [comment]
> 可以考虑把 PacLib 放到独立的仓库中，然后在 v2rayN 和 ClashN 中添加 PacLib 作为 Git 子模块
> 
> 实在不行的话干脆把 v2rayN 整个作为 Git 子模块添加进 ClashN 里也可以

附议, 这是个好主意的.
