### ISSUE TITLE
大佬能设置双击切换节点或配置文件么

### ISSUE THREAD

**Issue by yao71232** [2dust/clashN#239]
大佬能设置双击切换节点或配置文件么，每次需要右键感觉有点麻烦

**Comment by SlimeNull** [comment]
有快捷键 Enter, 不过, 你说的确实是个问题, 我马上去加

**Comment by SlimeNull** [comment]
https://github.com/2dust/clashN/pull/243

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.15
