### ISSUE TITLE
做了2个图标 看看能用不

### ISSUE THREAD

**Issue by 887BF690** [2dust/clashN#24]
桌面效果
[https://s3.bmp.ovh/imgs/2022/04/19/61fbb6505945aa27.png](https://s3.bmp.ovh/imgs/2022/04/19/61fbb6505945aa27.png)

[https://www.imgurl.org/img/44b6305588866097](https://www.imgurl.org/img/44b6305588866097)

[https://www.imgurl.org/img/cafc095999b5cdab](https://www.imgurl.org/img/cafc095999b5cdab)

**Comment by fyhzc** [comment]
就是说嘛，现在的图标在高清下太粗糙了，

**Comment by 2dust** [comment]
> 
请用下面三个颜色做底色，字母C用白色，做成3个256*256的PNG图片
#3399CC
#FF0000
#800080

发过来后我们放到程序里面看看效果

**Comment by 887BF690** [comment]
[#3399CC](https://s3.bmp.ovh/imgs/2022/04/19/c32929437081df2f.png)
[#FF0000](https://s3.bmp.ovh/imgs/2022/04/19/c1da189999e63c6a.png)
[#800080](https://s3.bmp.ovh/imgs/2022/04/19/95ea4f3cb7d92174.png)

**Comment by 887BF690** [comment]
![](https://s3.bmp.ovh/imgs/2022/04/19/fda85ae098e091d6.png)
![](https://s3.bmp.ovh/imgs/2022/04/19/3818225596de7ae1.png)
![](https://s3.bmp.ovh/imgs/2022/04/19/b35c0b1513ec5b9d.png)

**Comment by 887BF690** [comment]
![](https://s3.bmp.ovh/imgs/2022/04/19/64911ded4cbd1d3b.png)
![](https://s3.bmp.ovh/imgs/2022/04/19/e59b9d40d8a4d1bf.png)
![](https://s3.bmp.ovh/imgs/2022/04/19/95b5ff4c1ee0d036.png)

**Comment by 2dust** [comment]
![image](https://user-images.githubusercontent.com/31833384/163999694-25b0668a-5c03-4a84-a05b-dfa2d5f2f84e.png)

您的工具是否能把png转成这样的复合ico，我们这边转换了几个背景都不透明。
如果您那边可以，帮忙转3个一套的

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/8513081/clashN.zip)

下载测试。
此包内有三个文件NotifyIcon1.ico,NotifyIcon2.ico,NotifyIcon3.ico，分别对应系统代理的三个选项。
切换系统代理设置时，如果文件夹下面有这三个文件则优先使用。高级用法就是您可以用自己的文件替换掉

**Comment by fyhzc** [comment]
还行吧，
![无标题](https://user-images.githubusercontent.com/26890748/164011771-016879fb-87a8-4351-8f1f-e91cef8cf193.jpg)

**Comment by 887BF690** [comment]
复合ico 是这样的吗？

![](https://s3.bmp.ovh/imgs/2022/04/19/5fdb41b125bd873b.png)

**Comment by 887BF690** [comment]
稍等，我调整一下 字母大小

**Comment by 2dust** [comment]
> 对头，就是这样，

你帮忙先测试下用了复合i从后，托盘显示是否有改善？

**Comment by 2dust** [comment]
> 对头，就是这样，

你帮忙先测试下用了复合图标后，托盘显示是否有改善？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.8

**Comment by 2dust** [comment]
> 好像区别不大 对于右下角任务栏的图标 应该是缩放的太小了 @_@

![notify](https://user-images.githubusercontent.com/31833384/165009689-3dc6a9cd-5884-4a1a-81c0-4810de08c734.png)

请帮忙用下面三个颜色做底色，白色图标上传的这个，做成3个256*256的PNG图片，感谢
#3399CC
#FF0000
#800080

**Comment by 887BF690** [comment]
![](url)

**Comment by 2dust** [comment]
@887BF690  感谢

**Comment by 887BF690** [comment]
![](https://s3.bmp.ovh/imgs/2022/04/26/afd9b082dec243fb.png)


还有一套ico图标，看看有没有用哈，网盘 [[aa](https://ws28.cn/f/865y35g2vjh)](https://ws28.cn/f/865y35g2vjh)

**Comment by 887BF690** [comment]
![](https://s3.bmp.ovh/imgs/2022/04/26/1d82c7fa7060f545.png)
网盘[ico2](https://ws28.cn/f/8664e47xy3b)

**Comment by MetaCubeX** [comment]
真心漂亮
