### ISSUE TITLE
【功能请求】改善托盘菜单中代理选单的行为

### ISSUE THREAD

**Issue by FrzMtrsprt** [2dust/clashN#242]
### 目前 ClashN 托盘菜单中的代理选单的行为
1. 系统代理被手动变更后，代理选单中的所选项不会同时改变
2. 再次点击之前的所选项后，无法将代理状态恢复到原先状态

### 示例场景
1. 使用 ClashN 设置系统代理后，系统代理被更改为 ClashN 的代理端口
3. 手动变更系统代理后，打开 ClashN 托盘菜单中的代理选单，选单仍显示“自动配置系统代理”，但此时系统代理并不是 ClashN 的代理端口
4. 再次点击“自动配置系统代理”，试图恢复 ClashN 的系统代理，但系统代理并没有恢复

### 改善方案
1. 将系统代理的合并为两项：系统代理和 PAC 代理，具有独立的勾选和未勾选状态，允许出现 √√ √× ×√ ××（但√√不会出现，除非用户手动同时设置两种代理），同时去掉“不改变系统代理”和“清除系统代理”
2. 手动勾选系统代理时，将系统代理设置为启用，并设置为 ClashN 的地址和端口；手动取消勾选系统代理时，将系统代理设置为禁用
3. 每次右键打开托盘菜单时，查询一次系统代理，若地址和端口与 ClashN 的匹配，则自动勾选系统代理，否则自动取消勾选，PAC 代理同理，这样可以做到选单状态完全反应系统代理状态；勾选状态的自动变化不应触发上一条中系统代理的变化

### 示意图
![image](https://user-images.githubusercontent.com/15852717/220344562-ef89f348-32cf-4b9b-8820-32ad642c87e2.png)

此问题在v2rayN中也有出现，可以考虑将此方案也用到v2rayN上。

**Comment by FrzMtrsprt** [comment]
主界面的代理选单同样可以使用上述改进，相关讨论见 #236

**Comment by 2dust** [comment]
不改变代理的选择如何处理？

**Comment by FrzMtrsprt** [comment]
没太明白这个不改变代理的作用是什么，是让clashN切换到当前系统代理的端口，还是什么也不做呢？

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/wiki/%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86%E5%92%8C%E8%B7%AF%E7%94%B1

**Comment by 2dust** [comment]
不改变代理是很有用的功能

**Comment by FrzMtrsprt** [comment]
两个选项都不选中就是不改变代理。不在每次重启时强制改变系统代理状态，而是让代理选单实时反应系统代理的状态，可能比目前的方案更直观易用一些。

**Comment by FrzMtrsprt** [comment]
不改变菜单内容的话，至少可以修复一下再次点击系统代理却无法恢复系统代理的问题。

方案 1：将“清除系统代理”从选单中独立出来看作单独的按钮（位置不改变），无法被勾选，点击一次就清除一次代理（这样可以保证clashN重启时不会把其他应用的代理清掉）；每次打开菜单时检测一次系统代理，若与clashN代理不符，自动切换到“不改变系统代理”；剩下三项的行为不改变
方案 2：将Menu的事件触发条件改成每个MenuItem的MenuItem.Click事件，只要点击，即使是重复点击已选项，也再次执行触发事件（设置一次代理或清除一次代理）

方案 1 也可以从根本上解决选单状态无法反映系统代理状态的问题，而方案 2 仍需要让用户自己猜测系统代理的状态

**Comment by kyobox** [comment]
希望“当前链接”的标题栏可以筛选项目和升降序排列
