### ISSUE TITLE
ClashN v2.14是否已经支持IPv6节点的Hysteria协议

### ISSUE THREAD

**Issue by Ty2005** [2dust/clashN#244]
本人使用过程中，通过手动本地导入IPv6服务器搭建HY协议的clash-meta.yaml,无法正常使用。发现下列问题。
1. 每次管理员启动后，启用ipv6都是关闭状态（不确认IPv6是否真正工作）
2. 启动ipv6，也无法成功连接，报错如下
2023/2/25 15:45:26 Change system proxy
2023/2/25 15:45:26 Set rule mode Global->Global
2023/2/25 15:45:26 Clash Proxies Latency Test
time="2023-02-25T15:45:26.7743271+08:00" level=warning msg="Deprecated: Use Sniff instead"
2023/2/25 15:45:27 Refresh Clash Proxies
2023/2/25 15:45:32 Refresh Clash Proxies
time="2023-02-25T15:45:35.9873996+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:50780 --> www.google.com:443 error: dual stack dial failed:context deadline exceeded"
time="2023-02-25T15:45:40.9952247+08:00" level=warning msg="[TCP] dial GLOBAL 127.0.0.1:50793 --> www.google.com:443 error: dual stack dial failed:context deadline exceeded"

该节点配置在v2rayN v5.39 或者v6.xxx都能正常使用。

**Comment by 2dust** [comment]
IPv6是core提供的
您可以去对应的core提交疑问
