### ISSUE TITLE
节点名称稍长一点就无法全部显示

### ISSUE THREAD

**Issue by yalik01** [2dust/clashN#250]
希望能全部显示长的名称

**Comment by 2dust** [comment]
名称有多长？
可截图

**Comment by yalik01** [comment]
![屏幕截图 2023-03-22 121456](https://user-images.githubusercontent.com/94151038/226800789-d9e2ee42-1f7b-46f9-bfcf-572242a66e6d.jpg)

**Comment by 2dust** [comment]
https://file.io/gCsh3TJzhsUj

下载此版本看看

**Comment by yalik01** [comment]
![屏幕截图 2023-03-22 200910](https://user-images.githubusercontent.com/94151038/226901434-de8eaa5e-6fc9-40c4-a2ef-402fb7abba19.png)
还是不够宽，一行四个节点排满，整页也可以容纳很多节点了。

**Comment by 2dust** [comment]
https://file.io/QoAanKOjJDH6

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.15
