### ISSUE TITLE
2.15版本热键有问题

### ISSUE THREAD

**Issue by LeibNici** [2dust/clashN#254]
![image](https://user-images.githubusercontent.com/42395062/228103150-4212cc91-c5d8-4baf-b4e2-16ec68b8664c.png)

设置完成，并重启后，发现原本打开代理的热键变成打开主界面，请核查一下是否真存在此问题

建议：是否可以添加类似v2rayN中节点订阅链接处的节点排出正则表达功能，please

**Comment by 2dust** [comment]
热键的问题您清空后再次测试下
clash的订阅节点和路由是耦合在一起的，单独过滤掉节点可能会导致配置文件异常
