### ISSUE TITLE
v2.15不稳定，节点比较多时，往下拉的时候它自己又返回到顶页，

### ISSUE THREAD

**Issue by llkk3353** [2dust/clashN#255]
v2.15不稳定，节点比较多时，往下拉的时候它自己又返回到顶页，还有更新节点时经常没有反应。

**Comment by 2dust** [comment]
你是下拉分组还是节点？
在工具栏关闭自刷新功能试一试？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/files/11187434/clashN.zip

下载此版本测试

**Comment by llkk3353** [comment]
感谢作者的回复，，谢谢你的奉献，已经解决了。
