### ISSUE TITLE
建议增加“规则”栏目以便于查询，并支持手动添加

### ISSUE THREAD

**Issue by BICR** [2dust/clashN#256]
订阅转换而来的配置文件，没法 查看具体规则，也无法手动添加规则。

建议增加“规则”栏目便于查询，并支持手动添加规，且手动规则优先级高于订阅规则，不知道是否可以实现？

**Comment by 2dust** [comment]
能否给出其他app的类似功能截图和操作方式？

**Comment by bicr** [comment]
![image](https://user-images.githubusercontent.com/52844039/229363924-efe9f7c8-deb1-47e7-9873-c58903fd2a5e.png)

**Comment by bicr** [comment]
> 

![image](https://user-images.githubusercontent.com/52844039/229363945-38b16720-b02a-44be-a4fb-0f4a41edb632.png)

**Comment by 2dust** [comment]
订阅或转换的配置，你修改配置中的规则等，下次再更新就会丢失
你试一试设置中，编辑Mixin功能，是否满足？

**Comment by bicr** [comment]
> 

它是手动添加的规则，不会因为配置更新而被覆盖，其优先级最高，所以无论是否更新订阅配置，不影响手动规则的首先执行。

**Comment by 2dust** [comment]
设置中，编辑Mixin功能
# append-rules    数组合并至原配置rules数组后
# prepend-rules   数组合并至原配置rules数组前

**Comment by BICR** [comment]
> 设置中，编辑Mixin功能 append-rules 数组合并至原配置rules数组后 prepend-rules 数组合并至原配置rules数组前

谢谢，虽然也能实现，但感觉还是没有直接在规则处 手动添加 来的直接，而且好像CFW也支持直接添加。

**Comment by 2dust** [comment]
配置文件做出这样的界面还是有点复杂，是否做这样的功能看开发者时间了
