### ISSUE TITLE
clash.meta 的部分功能似乎 clashN 没有支持

### ISSUE THREAD

**Issue by JoeyLearnsToCode** [2dust/clashN#257]
比如[引用代理集](https://docs.metacubex.one/config/proxy-providers/use)和[代理组筛选](https://docs.metacubex.one/function/proxygroups/filter)这两个功能，根据clashMeta的文档，它们是被clashMeta支持的。
但是在clashN使用这两个功能好像有问题。

以[引用代理集](https://docs.metacubex.one/config/proxy-providers/use)为例，我按照clashMeta的示例配置后，clashN启动会报错：`time="2023-04-04T14:38:45.9931703+08:00" level=fatal msg="Parse config error: proxy group[1]: 'meta' not found"`

**Comment by 2dust** [comment]
此提示是clashMeta Core提示的，此功能和GUI无关
你可以把提示发到clashMeta那边
