### ISSUE TITLE
节点不显示

### ISSUE THREAD

**Issue by youyouhdhd** [2dust/clashN#258]
更新订阅后节点不显示，测试clash可以正常显示
![image](https://user-images.githubusercontent.com/54936458/230365548-1a8eb7d4-4842-443f-a422-42c838b99d5e.png)
![image](https://user-images.githubusercontent.com/54936458/230365563-58283856-15a7-4672-a983-7bb8fa8a75a8.png)

**Comment by 2dust** [comment]
把日志信息发出来
可能是api端口被占用了，你是否开了多个clash？

**Comment by youyouhdhd** [comment]
配置成功
pianyi
启动服务(2023/4/6 19:56:42)...
Core类型 Clash
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🍃 应用净化"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 📢 谷歌FCM"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2023-04-06T19:56:42+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2023-04-06T19:56:42+08:00" level=error msg="External controller listen error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
2023/4/6 19:56:43 Change system proxy
2023/4/6 19:56:43 Set rule mode Rule->Rule
2023/4/6 19:56:43 Clash Proxies Latency Test
time="2023-04-06T19:56:52+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2748 --> localhost.sec.qq.com:9410 error: dial tcp4 127.0.0.1:9410: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:52+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2749 --> localhost.ptlogin2.qq.com:4307 error: dial tcp4 127.0.0.1:4307: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:52+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2754 --> localhost.sec.qq.com:16873 error: dial tcp4 127.0.0.1:16873: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:52+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2755 --> localhost.ptlogin2.qq.com:4309 error: dial tcp4 127.0.0.1:4309: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:54+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2769 --> localhost.ptlogin2.qq.com:4307 error: dial tcp4 127.0.0.1:4307: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:54+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2768 --> localhost.sec.qq.com:9410 error: dial tcp4 127.0.0.1:9410: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:54+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2774 --> localhost.ptlogin2.qq.com:4309 error: dial tcp4 127.0.0.1:4309: connectex: No connection could be made because the target machine actively refused it."
time="2023-04-06T19:56:54+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match DomainSuffix/qq.com) 127.0.0.1:2772 --> localhost.sec.qq.com:16873 error: dial tcp4 127.0.0.1:16873: connectex: No connection could be made because the target machine actively refused it."
2023/4/6 19:57:28 Refresh Clash Proxies
配置成功
pianyi
2023/4/6 19:57:36 Change system proxy
2023/4/6 19:57:36 Set rule mode Rule->Rule
2023/4/6 19:57:36 Clash Proxies Latency Test
更新订阅开始
pianyi->开始获取订阅内容
pianyi->获取订阅内容成功
pianyi->更新订阅结束
-------------------------------------------------------
更新订阅结束
配置成功
pianyi
2023/4/6 19:57:43 Change system proxy
2023/4/6 19:57:43 Set rule mode Rule->Rule
2023/4/6 19:57:43 Clash Proxies Latency Test
配置成功
pianyi
2023/4/6 19:57:49 Change system proxy
2023/4/6 19:57:49 Set rule mode Rule->Rule
2023/4/6 19:57:49 Clash Proxies Latency Test




是这样的吗

**Comment by 2dust** [comment]
listen tcp [127.0.0.1:9090](http://127.0.0.1:9090/): bind: An attempt was made to access a socket in a way forbidden by its access permissions.
你修改下设置中的api端口把，被占用了

**Comment by youyouhdhd** [comment]
感谢大佬，我试试

**Comment by youyouhdhd** [comment]
> 感谢大佬，我试试
