### ISSUE TITLE
便携版目录生成错误

### ISSUE THREAD

**Issue by anglesccs** [2dust/clashN#26]
clashN放在下图所示的目录中
![2022-04-19_210458](https://user-images.githubusercontent.com/49857157/164010873-3fdba106-01ae-4586-9994-b627d0c3130f.JPG)
然后会生成一个Green的文件夹,如下图
![2022-04-19_210618](https://user-images.githubusercontent.com/49857157/164011117-f5b14e6a-da4a-49e9-aaca-2236ea39098a.JPG)

应该是因为green software文件夹名是由两个单词组成的。

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/8517348/clashN.zip)

下载测试

**Comment by anglesccs** [comment]
已解决，顺便问一句，有没有把clashN和V2rayN整合到一起的打算？

**Comment by 2dust** [comment]
clash和v2ray的设置和功能差异比较大，整合在一起操作上就比较难兼容，就会导致两个都不是最好的操作
