### ISSUE TITLE
操作逻辑改善建议

### ISSUE THREAD

**Issue by haakuya** [2dust/clashN#261]
在选择proxy-groups时在选择了分组后需要再次选择节点才能改变状态。
另：为何点击刷新后得等快十几秒才生效

**Comment by 2dust** [comment]
没有明白你的意思

**Comment by haakuya** [comment]
比如我从streaming组切换到global组，需要在global组中再次选择节点才能切换到global组，不然只点击global组的按钮状态还会停在streaming组

**Comment by haakuya** [comment]
并且 出现 报错时 WRN [TCP] dial failed error=dial tcp4 192.0.77.40:443: i/o timeout proxy=DIRECT，即使选定全局模式还是会导致浏览器直连

**Comment by 2dust** [comment]
clash应该是没有组切换概念的，组一般就是把很多节点放一起
当你访问某个网址时，规则会自动走某一个组，所以并不存在切换组的功能

**Comment by haakuya** [comment]
比如CFW是可以明确切换global和rule模式，但是像clashN就没有一个切换的变化，而是在选择规则模式 
全局，规则，直连，随原配置
选择时左边的那一栏没有变化

**Comment by 2dust** [comment]
> 比如CFW是可以明确切换global和rule模式，但是像clashN就没有一个切换的变化，而是在选择规则模式 全局，规则，直连，随原配置 选择时左边的那一栏没有变化

选择模式后，确实左边没有变化，但是实际core已经切换到你想要的模式。
你的想法是比如切换到Global后，组里面就剩下GLOBAL吗？
