### ISSUE TITLE
skip-cert-verify: 选项是如何工作的？

### ISSUE THREAD

**Issue by Azuriye** [2dust/clashN#265]
你好，我正在使用DeepL 来翻译... 我想知道skip-cert-verify选项如何工作，因为...

当我把它设置为真时，我不再得到x509：证书对example.com有效，而不是www.microsoft.com，有时则相反（对www.microsoft.com有效，而不是example.com）。

但我注意到的是，当我把它设置为 "真 "时，由于某种原因，互联网变得非常慢，所以我不确定这个选项到底是如何工作的......

当我禁用该选项或完全删除该行时，我在日志选项卡中得到那些x509警告，但互联网现在工作得很快，这很奇怪，因为该选项主要用于启用或禁用证书验证。

希望这里有人能就这个选项给我更多的启发......

谢谢你提供的这个很棒的软件!

==================================================================================
Hello, I am using DeepL to translate... I wanted to know how skip-cert-verify option works because...

When I set it to true I no longer get  x509: certificate is valid for example.com, not www.microsoft.com and sometimes the other way around (valid for www.microsoft.com, not example.com)

But what I've noticed is that when I set it to true for some reason internet becomes very slow so I am not sure how this option really works...

When I disable this option or just completely remove the line I get those x509 warnings in the logs tab but the internet works fast now which  is so odd when this option is mostly used for enabling or disabling certificate verification

Hopefully, someone here could enlighten me more regarding this option...

Thank you for this awesome software as well!

**Comment by 2dust** [comment]
Please check the clash documentation https://github.com/Dreamacro/clash/wiki/Configuration
