### ISSUE TITLE
[建议]能否将.NET运行时和程序一起打包发布

### ISSUE THREAD

**Issue by natsukiKitano** [2dust/clashN#266]
请问能否按照这篇Microsoft Learn文章所说的将.NET框架依赖项和程序一起打包发布，或者额外提供一个这样的发布？
[https://learn.microsoft.com/zh-cn/dotnet/core/deploying/#publish-self-contained](url)
个人认为这样尽管程序的体积会增加不少，但可以使程序直接运行而不必预先安装对应的.NET运行时，省去不必要的麻烦。

**Comment by 2dust** [comment]
这样做发布文件巨大，下载时不方便
当遇到PC实在无法安装时才考虑
