### ISSUE TITLE
2.15版，节点列表空白

### ISSUE THREAD

**Issue by ctmdqgmzzf** [2dust/clashN#267]
从订阅界面切换到节点界面后，无法查看节点及列表，重启也不起作用。

**Comment by 2dust** [comment]
把日志贴出来看看
大概率是API端口9090占用了，你在设置中修改下

**Comment by ctmdqgmzzf** [comment]
> 已在软件界面升级三部件到最新版，在配置文件可以正常切换订阅，但在当前代理界面看不到节点列表，但右键会出现“延迟测试”和“切换活动节点”两个弹出菜单
已确认10086端口无冲突，可以在浏览器打开看到“{"hello":"clash.meta"}”

启动服务(2023/4/14 18:23:29)...
Core类型 ClashMeta
time="2023-04-14T18:23:29.837066+08:00" level=info msg="Start initial configuration in progress"
time="2023-04-14T18:23:29.8391444+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2023-04-14T18:23:29.8421288+08:00" level=info msg="Initial configuration complete, total time: 5ms"
time="2023-04-14T18:23:29.8421288+08:00" level=info msg="Sniffer is closed"
time="2023-04-14T18:23:29.8448072+08:00" level=info msg="RESTful API listening at: 127.0.0.1:10086"
time="2023-04-14T18:23:29.8454425+08:00" level=info msg="HTTP proxy listening at: [::]:7891"
time="2023-04-14T18:23:29.8459788+08:00" level=info msg="SOCKS proxy listening at: [::]:7890"
time="2023-04-14T18:23:29.8459788+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
time="2023-04-14T18:23:29.8459788+08:00" level=info msg="Redirect proxy listening at: [::]:7892"
time="2023-04-14T18:23:29.8464946+08:00" level=error msg="Start Redir server error: not supported on current platform"
time="2023-04-14T18:23:29.8464946+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7888"
time="2023-04-14T18:23:29.8481984+08:00" level=info msg="Start initial compatible provider Helium Network"
time="2023-04-14T18:23:29.8481984+08:00" level=info msg="Start initial compatible provider 自动选择"
time="2023-04-14T18:23:29.8481984+08:00" level=info msg="Start initial compatible provider default"
time="2023-04-14T18:23:29.8481984+08:00" level=info msg="Start initial compatible provider 故障转移"

**Comment by ctmdqgmzzf** [comment]
问题解决，是在clashN界面设置的api监听端口与在mixin配置里的不一致，通通改为10086就OK了

**Comment by ctmdqgmzzf** [comment]
问题解决，是在clashN界面设置的api监听端口与在mixin配置里的不一致，通通改为10086就OK了
