### ISSUE TITLE
刷新之后跳转到固定节点

### ISSUE THREAD

**Issue by richmonde** [2dust/clashN#269]
v2.16

**Comment by 2dust** [comment]
能详细描述下？

**Comment by 2dust** [comment]
如果你是要切换活动节点，需要鼠标双击此节点或选中后按回车健

**Comment by richmonde** [comment]
> 如果你是要切换活动节点，需要鼠标双击此节点或选中后按回车健

但是没有成功，点其他菜单再点回来当前节点也会显示那个固定的节点。
而且在之前的版本里仅仅右键设置为活动节点/双击之后也需要点击刷新节点才能生效。

**Comment by 2dust** [comment]
clash的group type是selector，节点才能被切换，检查是否符合

**Comment by richmonde** [comment]
> clash的group type是selector，节点才能被切换，检查是否符合

是selector
![image](https://user-images.githubusercontent.com/19168163/231934767-ec03c532-828f-4f9f-b690-a28a68c2a3d7.png)
选择其他节点之后刷新又回到这个节点了

**Comment by 2dust** [comment]
感谢反馈
正在修复

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.17
