### ISSUE TITLE
高分屏缩放问题

### ISSUE THREAD

**Issue by FrzMtrsprt** [2dust/clashN#27]
**系统环境：**
- 屏幕分辨率：2560×1600
- 显示缩放：200%

**问题：**
1. 在设置里更改字体后，界面中部分字体变得极大，部分字体变得极小，且换回默认字体、默认大小后，甚至重置设置后仍无法恢复；
2. 系统托盘菜单里，所选项的✅显示不全。

**临时解决方法：**
- 右键clashN.exe属性，兼容性→更改高DPI设置→高DPI缩放替代，选择应用程序。
![clashN_3k5cfPanH5](https://user-images.githubusercontent.com/15852717/164142899-2d8aef2b-fa7e-4a9f-a63d-1da33d44f27a.png)
![image](https://user-images.githubusercontent.com/15852717/164145282-69e3df1c-d0d9-44d6-b542-dd514a8de42e.png)

**Comment by 2dust** [comment]
字体设置存放在注册表： 计算机\HKEY_CURRENT_USER\SOFTWARE\clashNGUI\CurrentFont
删除即可还原。
至于字体设置后变化极大这个需要测试，此功能是框架自带

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.9
此版本可以重置字体
但是大字体显示问题无法解决

**Comment by HanHan666666** [comment]
我在修改字体后也遇到了同样的问题
我的屏幕缩放为150%
分辨率2160x1440
![image](https://user-images.githubusercontent.com/60591430/167834969-4c5303db-6c13-42a1-bce8-d71e240080a3.png)
