### ISSUE TITLE
tun打開後，升級核心會退出tun。重啓clashN不會自動自動tun

### ISSUE THREAD

**Issue by likaifenkeng** [2dust/clashN#272]
在軟件裏打開tun(核心使用clashPremium)，並驗證能用win10客戶端收發gmail。edge能訪問谷歌。

下面是問題：
tun打開後，升級核心會退出tun，軟件顯示tun打開，但是虛擬網卡消失，edge無法訪問google。
重啓clashN不之後，軟件顯示tun打開，但是虛擬網卡消失，edge無法訪問google。

只有手工關閉並再次打開tun，才恢復正常。

Win10 22H2
clashN  2.17

**Comment by likaifenkeng** [comment]
今天再次測試，還是clashPremium核心，已開啓tun開關然後退出，管理員重啓clashN，一分20秒恢復了tun模式。

**Comment by 2dust** [comment]
经测试
在开tun模式时，升级core成功后tun模式还是开启中，网卡也存在

请重复测试几次，把必定复现的步骤写出
