### ISSUE TITLE
全局模式无效

### ISSUE THREAD

**Issue by BARUBORA** [2dust/clashN#276]
CLASH订阅,自动配置系统代理,模式设置为全局时无效,观察"当前连接",各线路依然按照订阅规则在走.

**Comment by q2051839** [comment]
我试了下，确实如此，我这好像是选定任意节点，得到的都是全局直连的效果。

**Comment by 2dust** [comment]
哪个版本？

**Comment by simplerick-simplefun** [comment]
> 哪个版本？

最新版本，[2.17](https://github.com/2dust/clashN/releases/tag/2.17)。
需要用户在自己的配置里把“Match,xxxx”改成“Match,GLOBAL”才能生效。
猜测这应该是程序在生成config.yaml时自动改，但是右bug，没改。

**Comment by T1anjiu** [comment]
我试了前几个版本好像也会这样，不知道什么原因，期间也换电脑尝试，但是还是只能用rule模式
