### ISSUE TITLE
设置页面有bug

### ISSUE THREAD

**Issue by nickonline2005** [2dust/clashN#277]
点击进入参数设置页面，然后关闭clashn窗口，再打开clashn，这时候设置页面上的Core设置/clashn设置/系统代理设置的选项卡会消失。改变以下窗口大小，这几个就又显示了。
![QQ截图20230427212919](https://user-images.githubusercontent.com/23328037/234877370-0bad2b6d-b52d-456f-9185-ad4d9508e9b1.png)

**Comment by mingchau** [comment]
复现了，我说怎么找不到“开机启动”的选项了呢，明明之前看到了的。。。
