### ISSUE TITLE
配置文件适应问题

### ISSUE THREAD

**Issue by anglesccs** [2dust/clashN#28]
![捕获](https://user-images.githubusercontent.com/49857157/164176277-7685d4cb-7d5f-4132-a935-f7a715743f5a.JPG)
配置文件里必须得有这一段才行，否则报错，能不能把这些内容做一个默认配置，如果配置文件里没有这些的话就用默认配置，如果有这些的话就用配置文件里的？

**Comment by 2dust** [comment]
除了mode，其他都是强制会写入的
错误信息发出来

**Comment by anglesccs** [comment]
![捕获](https://user-images.githubusercontent.com/49857157/164574522-4c4bf62c-7e61-4bbd-935f-77e5a6ed5f8d.JPG)
啥也没有，就是配置文件失败，同样的配置文件在clash for windows，openclash都可以用
