### ISSUE TITLE
本地API监听端口存在问题

### ISSUE THREAD

**Issue by Nep-Timeline** [2dust/clashN#286]
如果订阅使用secret设置了访问密钥 那么clashN将无法访问Clash API导致当前代理页面为空

**Comment by MatchlessBrother** [comment]
#309 不设置密码不就ok了，麻烦大兄弟有时间帮我看看这个问题，这个：name参数怎么传呢？

**Comment by leoking670** [comment]
[https://v2ex.com/t/1076579](https://v2ex.com/t/1076579)
这个贴文讨论了，Clash和众多衍生版本实际上是允许跨域的。部分浏览器（包括FF、Edge等）的默认配置并不严格限制跨域。在这个前提下，如果不使用Secret验证，其他网址是可以获取全部代理信息的。我认为本项目的当前代理页面，有必要支持在设置密钥后访问。
