### ISSUE TITLE
2.17页面BUG

### ISSUE THREAD

**Issue by tomagag** [2dust/clashN#292]
升级到2.17后，选取节点的页面不能显示，不知道如何设置才能显示出来。可以正常登录之前的节点，但是无法选取节点
![微信截图_20230702131036](https://github.com/2dust/clashN/assets/85090720/9e2f1fb9-dc4f-43cc-b600-45fc049ae67f)

**Comment by sledDog-cn** [comment]
重新下载软件、更新Windows版本、订阅转换都试试，我记得应该是订阅的问题

**Comment by tomagag** [comment]
谢谢，重新下载软件后，改字体，已经可以正常使用了！







------------------ 原始邮件 ------------------

发 件 人：CATDOG ***@***.***>

发送时间：2023-08-14 13:43:05

收 件 人：2dust/clashN ***@***.***>

抄 送：tomagag ***@***.***>,Author ***@***.***>

主 题：Re: [2dust/clashN] 2.17页面BUG (Issue #292)







重新下载软件、更新Windows版本、订阅转换都试试，我记得应该是订阅的问题
