### ISSUE TITLE
建议给每个订阅源加个开关。控制在更新时有所选择，不是在更新订阅时默认全部更新。谢谢

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#3]

**Comment by fyhzc** [comment]
是在主界面上。

**Comment by 2dust** [comment]
目前每个订阅里面有个有效属性可以关闭更新。
你的意思时选中一个订阅单独更新？

**Comment by fyhzc** [comment]
我 是说在主界面里在别名前面给每个订阅源加一个开关。

**Comment by 2dust** [comment]
> 我 是说在主界面里在别名前面给每个订阅源加一个开关。省得要开关更新都要打开每个单独的属性面板

List控件不方便做此功能。
