### ISSUE TITLE
比较好用，特别是内置的订阅链接转换功能。

### ISSUE THREAD

**Issue by musaart** [2dust/clashN#30]
比较好用，特别是内置的订阅链接转换功能。感谢作者

**Comment by zgithubx-code** [comment]
jms的订阅链接勾选了订阅转换，确定后没看到节点，只看到一个配置文件是我哪里操作不对吗？

**Comment by 2dust** [comment]
> jms的订阅链接勾选了订阅转换，确定后没看到节点，只看到一个配置文件是我哪里操作不对吗？

转换后就是个配置文件，可打开后点编辑查看是否正确

**Comment by AgathonLi** [comment]
请问目前的订阅转换是不是还不支持vless协议呀？
现在每次都需要在长风的这个[节点转换工具](https://v2rayse.com/v2ray-clash/)进行转换，要是内置订阅转换功能能支持就好啦。
