### ISSUE TITLE
Clash.Meta删库了？

### ISSUE THREAD

**Issue by likaifenkeng** [2dust/clashN#306]
最近才更新过1.17.

**Comment by idragonet** [comment]
Releases · MetaCubeX/mihomo - https://github.com/MetaCubeX/mihomo/releases

**Comment by PctAIGM** [comment]
迁移后自动更新ClashMeta失效，需要手工更新

**Comment by idragonet** [comment]
自己修改源代码编译下。

**Comment by PctAIGM** [comment]
对C#不是很熟悉，简单修改了下，也提了pr，看作者有没有空合并吧

**Comment by likaifenkeng** [comment]
多谢多谢。
我目前用笨方法，手工下载mihomo-windows-amd64-alpha和mihomo-windows-amd64-compatible-alpha，解压缩后改名放到bin\ClashMeta目录里。目前运行没出现问题，如果作者能改代码实现升级就最好了。
