### ISSUE TITLE
请问如何切换内核，默认使用的是clash.meta，还有如何更新内核，点了没有反应

### ISSUE THREAD

**Issue by bangbangbangooo** [2dust/clashN#308]
请问如何切换内核，默认使用的是clash.meta，还有如何更新内核，点了没有反应
win10上用的ClashN.17
点击检查更新没有反应，在日志显示：开始更新 Core...
然后没下文了。。

**Comment by PctAIGM** [comment]
https://github.com/2dust/clashN/issues/306
