### ISSUE TITLE
v2.18 界面无法正常显示

### ISSUE THREAD

**Issue by SpaceTimee** [2dust/clashN#311]
v2.18 的软件子界面均显示为空白
![软件子界面](https://github.com/2dust/clashN/assets/55327009/7196cedb-6ebf-476b-bc06-7c0fcce57b24)

小图标的右键菜单也无法使用
![小图标右键菜单](https://github.com/2dust/clashN/assets/55327009/48138473-e4b2-44f3-9907-1f842516d960)

(v2.17 可以正常显示)

测试环境: Windows 11 企业版

**Comment by SpaceTimee** [comment]
是缺少 .Net8 运行时导致的

**Comment by SpaceTimee** [comment]
我在 #312 中尝试修复这个问题

**Comment by itheabyss** [comment]
一样的，把界面最小化后无法激活界面了

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.19
