### ISSUE TITLE
mixin功能可以往新添加的proxy-groups里添加订阅中自带的名字不固定的proxies吗？

### ISSUE THREAD

**Issue by Kam323** [2dust/clashN#319]
订阅的机场proxy-groups不适合使用习惯，所以自行添加了几个新的proxy-groups，但由于订阅机场的proxies名字是不定时变的，所以不能通过mixin功能的prepend-proxy-groups添加订阅里自带的proxies，有没有办法获取订阅自带的proxies添加到proxy-groups中呢？例如clash for windows里的parser有command功能，可以读取proxies然后添加到proxy-groups中

**Comment by PctAIGM** [comment]
clash-verge 的script功能能满足你
