### ISSUE TITLE
I was using V2rayN until now, I switched to ClashN due to issues but I can't place my config in ClashN at all

### ISSUE THREAD

**Issue by Your-Best-Friend86** [2dust/clashN#321]
I'm selecting the Export to clipboard button in V2rayN but import from Clipboard in ClashN is not doing anything at all, I click on it and nothing happens

I also tried QrCode but same, no result

this is how my exported config looks like:

`vless://********-****-****-****-************@***********.com:2082?encryption=none&security=none&type=ws&host=***********.com&path=%2F#CyberTunnel827`

**Comment by Fliny** [comment]
A clash config usually starts with 'https://*****.c**/*****' . vless/vmess could not be used in ClashN.
You need to find the clash subscription link, or use a 'v2ray to clash' convert tool.
