### ISSUE TITLE
打扰一下，貌似Mihomo核心不能升级

### ISSUE THREAD

**Issue by likaifenkeng** [2dust/clashN#322]
ClashN 2.19 ，订阅配置核心使用Mihomo。今天看到 Mihomo 升级为  1.18.1，我在帮助和更新里按了升级 Mihomo 核心，没看到 mihomo.exe 文件 更新。日志只显示"开始更新 Core... "。没有后续的动作。

我是手工下载 mihomo-windows-amd64-compatible.exe 更新的 “ bin\Mihomo\mihomo.exe”文件。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.20

**Comment by likaifenkeng** [comment]
Thank you very much

**Comment by likaifenkeng** [comment]
我对照了各个版本的文件尺寸，好像更新到mihomo-windows-amd64-compatiblev1.17而不是mihomo-windows-amd64-compatiblev1.81。

**Comment by 2dust** [comment]
升级只会检查正式版
