### ISSUE TITLE
退出CLASHN的时候电脑会卡顿几秒钟的时间，用CLASH和V2RAYN不会这样。

### ISSUE THREAD

**Issue by piggy9527** [2dust/clashN#326]
退出CLASHN的时候电脑会卡顿几秒钟的时间，用CLASH和V2RAYN不会这样。

**Comment by 2dust** [comment]
暂时找不到问题

**Comment by blankhang** [comment]
我也发现了这个

**Comment by Jimmy20220531** [comment]
会不会是剪贴板的问题？

**Comment by spcprt** [comment]
![image](https://github.com/2dust/clashN/assets/58890783/e9ac5c97-a25b-48b3-8f81-ff36e1261c7c)
![image](https://github.com/2dust/clashN/assets/58890783/7dea366f-f200-49d9-9d0a-4e5b7ae69b6d)
![image](https://github.com/2dust/clashN/assets/58890783/3d03956a-ac3d-469f-9434-c9fb7ba92ad6)
退出的時候報這個，有時候運行的時候也報

**Comment by 2dust** [comment]
试一试
https://github.com/2dust/clashN/releases/tag/2.21

**Comment by yuxianzi666** [comment]
我猜测是某个.NET的版本问题，之前的V2RayN也会出现这个情况 @2dust

**Comment by Kukuair** [comment]
我也有此问题

**Comment by lyshensir** [comment]
确实，最新版也是。

**Comment by 2dust** [comment]
等下更新下.net 版本

**Comment by 2dust** [comment]
试一试
https://github.com/2dust/clashN/releases/tag/2.22

**Comment by yuxianzi666** [comment]
新版本确实改善了许多

**Comment by 2dust** [comment]
感谢反馈，再等等

**Comment by lyshensir** [comment]
确实，比以前快多啦 @``

**Comment by Kukuair** [comment]
没问题了，现在是秒关了
另外我想问问大家有没有感觉开机自启clashN很慢？开机等很久在托盘才出现clashN的图标？
我同时打开V2rayN和clashN的自启对照了一下，V2rayN的图标都出现了，clashN还没出现，还要再等
