### ISSUE TITLE
订阅更新成功，但是当前代理TAB是空白 不显示服务器列表？

### ISSUE THREAD

**Issue by blankhang** [2dust/clashN#328]
![image](https://github.com/2dust/clashN/assets/3981276/243ee66d-439f-4c62-9ac3-9d2b8ca39b5d)
![image](https://github.com/2dust/clashN/assets/3981276/7ec771fa-4667-41ae-88bd-1ec355d7078e)
![image](https://github.com/2dust/clashN/assets/3981276/dd378fb2-5a60-4085-a4a4-bb200b1010e5)
![image](https://github.com/2dust/clashN/assets/3981276/c3c74df9-e5b6-4194-8883-b9beabcfeef0)
配置文件里面是有服务器的

**Comment by HKMV** [comment]
同样的问题

**Comment by DerickIT** [comment]
看了下代码，获取了订阅但没有进行节点页面数据更新
