### ISSUE TITLE
关机时有时会提示clashN正在阻止关闭计算机，有时会弹出一个报错的对话框

### ISSUE THREAD

**Issue by Fliny** [2dust/clashN#329]
windows11 23h2，clashN 2.20。
现在每次关机前我都手动在clashN上点右键点退出，然后关机就正常的。如果忘了退出就会报个错，点一下确定之后就继续关机了。因为是关机过程所以也截不了图，如果下次看到我把报错内容发上来。

**Comment by 2dust** [comment]
试一试
https://github.com/2dust/clashN/releases/tag/2.22

**Comment by Fliny** [comment]
新版本OK了
