### ISSUE TITLE
切换成tun模式，core自动变为clash_meta?

### ISSUE THREAD

**Issue by anglesccs** [2dust/clashN#33]
切换成tun模式，core自动变为clash_meta?
还有能否增加订阅的定时更新功能？

**Comment by FrzMtrsprt** [comment]
订阅定时更新是有的吧，在clashN设置里

**Comment by 2dust** [comment]
> 切换成tun模式，core自动变为clash_meta? 还有能否增加订阅的定时更新功能？

因为clash_meta的tun模式支持的更好
