### ISSUE TITLE
大佬好，流量统计似乎无法与机场同步。

### ISSUE THREAD

**Issue by Eastegg** [2dust/clashN#330]
大佬好，流量统计似乎无法与机场同步。不知道是不是我不会用，我不小心点击了“清除所有服务统计数据”以后，流量跟机场的剩余流量不同步了。
![image](https://github.com/2dust/clashN/assets/11242470/b74f0b6b-8664-4440-a184-93f837b9b646)

下面是verge rev，他这个倒是挺准
![image](https://github.com/2dust/clashN/assets/11242470/8bafbef0-687a-47a6-8845-262681c9af4a)

**Comment by 2dust** [comment]
重新添加一个订阅，然后更新，看看上面是否会显示
