### ISSUE TITLE
在公共场所连接WiFi的时候认证网页无法执行

### ISSUE THREAD

**Issue by huang5307** [2dust/clashN#331]
我的笔记本在星巴克或是麦当劳等工作场所需要连接它们的WiFi的时候，发现那个认证网页无法执行。因为跳的比较快，网址应该（但不确定）是： http://www.msftconnecttest.com/redirect

我尝试把连接方式由“规则”改为直连，发现还是无法使用。因为我是使用TUN模式所以本来就没有设定系统代理（也就是清除系统代理），我试了重刷什么的，都没有用，最后我是把classN关闭了，连上WiFi，再打开classN才能使用。

**Comment by Fliny** [comment]
试试加入例外列表呢？参数设置-系统代理设置，例外框里加入 *.msftconnecttest.com; 然后点上面的保存
