### ISSUE TITLE
设置开机启动无效

### ISSUE THREAD

**Issue by HoboCY** [2dust/clashN#334]
ClashN版本：2.20
Win版本：Windows 11 专业版 23H2 22631.3296
软件设置开机启动无效，已经尝试过管理员运行，仍无效

**Comment by 2dust** [comment]
设置后请打开注册表 \HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run
查看是否有clashNAutoRun，值是否正确路径
