### ISSUE TITLE
内存占用

### ISSUE THREAD

**Issue by oriswy** [2dust/clashN#336]
前几天，任务管理器里 clashN 内存占用6、7个G，
昨天，win11重启后，没开啥软件内存就占用12-14个G， 任务管理器里看到 clashN 的 Mihomo占用2G内存，退出 clashN  删除 Mihomo 再重启后 总内存占用就只有5、6个G了，现在用的 clash Meta 内核

**Comment by 2dust** [comment]
如果没有开tun模式，可以把问题反馈给Mihomo
