### ISSUE TITLE
当电脑休眠后内存占用过高

### ISSUE THREAD

**Issue by TingChieh** [2dust/clashN#338]
使用笔记本电脑，在关盖重新启动电脑后，会查看到 ClashN 进程内存占用过高，正常打开情况下 仅占用 100MB 以下，但休眠后启动，会看到占用在 500MB 以上，长期不这样休眠甚至能高达 2000MB-3000MB。

**Comment by 2dust** [comment]
请查看是calshN占用的，还是core占用？

**Comment by TingChieh** [comment]
查看任务管理器后，是 ClashN 的占用，core 占用正常。

**Comment by TingChieh** [comment]
![ca8f5c01ca8c766e0f02a62835407e5](https://github.com/2dust/clashN/assets/52627954/ef2a16de-21ce-4ab0-9fe7-6186c1143d59)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/releases/tag/6.49
请尝试使用v2rayN，本app将不再维护
