### ISSUE TITLE
大佬好，反馈个问题，和这个#332很像，更新不了hysteria协议的节点

### ISSUE THREAD

**Issue by lyshensir** [2dust/clashN#342]
大佬好，你开发的软件非常简洁明了，功能强大，非常喜欢。
但是最近总发现更新的订阅不全，hy协议的一直没有，很奇怪，看了和这个#332的问题一样。
用clash verge就能更新到，我把mihomo的内核更新过了还是不行。

**Comment by 2dust** [comment]
这个一般需要设置定义的agent，你改成mihomo或meta试一试

**Comment by lyshensir** [comment]
> 这个一般需要设置定义的agent，你改成mihomo或meta试一试

你好，这个试过了，还是不行的。
自定义agent也加了还是出不来。方便的话你可以测试下 :):)

**Comment by 2dust** [comment]
发地址到 captainIronng@protonmail.com
或者你可以问下提供者，要怎样得到hy2

**Comment by lyshensir** [comment]
> 发地址到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com) 或者你可以问下提供者，要怎样得到hy2

你好大佬，已发邮箱~

**Comment by 2dust** [comment]
Agent 填入 Clash-verge/v1.6.0
试一试
