### ISSUE TITLE
全局热键无效

### ISSUE THREAD

**Issue by sanmaodo** [2dust/clashN#345]
设置了全局热键，前面4个都没反应，最后一个“pac模式”的按键，执行了 打开/关闭 主界面.

**Comment by sanmaodo** [comment]
全局模式也无效，任何需要链接代理的网址都打不开，只能选择规则模式

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/releases/tag/6.49
请尝试使用v2rayN，本app将不再维护
