### ISSUE TITLE
mihomo内核CPU占用率过高

### ISSUE THREAD

**Issue by liyansong2018** [2dust/clashN#348]
Hello，感谢您的出色工作。不过我发现每次运行clashn之后，mihomo进程的占用率都会到100%，有没有啥好的解决方法
```
处理器	12th Gen Intel(R) Core(TM) i5-12400，2500 Mhz，6 个内核，12 个逻辑处理器
已安装的物理内存(RAM)	32.0 GB
版本	10.0.22631 版本 22631
操作系统名称	Microsoft Windows 11 专业版
```
截图

![Snipaste_2024-05-08_18-29-47](https://github.com/2dust/clashN/assets/25031216/5a18fcb7-a6d8-43fa-ad4e-332dfca8c697)

**Comment by 2dust** [comment]
https://github.com/MetaCubeX/Mihomo
这里反馈
