### ISSUE TITLE
V2rayN和ClashN

### ISSUE THREAD

**Issue by littlebigdream** [2dust/clashN#35]
用过V2rayN，ClashN和CFW，真心觉得V2rayN是最好用的。
ClashN和CFW是以 配置文件为单位的，不能自由调整。
V2rayN是以节点为单位的，可以对每个节点 删除，添加，排序，测速，自由调整。

感觉目前V2rayN的唯一的缺点是不支持SSR，有时需要换用别的客户端。
请求作者不要放弃V2rayN，V2ray核心不支持SSR，能不能为 V2rayN再 添加一个SSR核心呢，现在的V2rayN也是可以切换核心的。
请求作者 再给V2rayN一个机会啊！

**Comment by 2dust** [comment]
v2ray-core不支持SSR

**Comment by 0x0004** [comment]
> v2ray-core不支持SSR

这个issues的每一句都真是说出了我的心里话。另外希望作者不要把重心放在clash支持上面，
