### ISSUE TITLE
订阅后，日志显示订阅成功，本地文件已生成有内容，但在当前代理页一空白。

### ISSUE THREAD

**Issue by obirdobird** [2dust/clashN#350]

**Comment by gg6fnxa75** [comment]
![Uploading 屏幕截图 2024-05-19 135313.png…]()

**Comment by zjmyyds007** [comment]
我的也是这样

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/releases/tag/6.49
请尝试使用v2rayN，本app将不再维护
