### ISSUE TITLE
全局热键设置小键盘数字后会导致界面无法显示

### ISSUE THREAD

**Issue by mmfoxred** [2dust/clashN#352]
全局热键设置小键盘数字后会导致界面无法显示，在界面上识别为Ctrl+Alt+LMenu，保存并重启应用后，出现问题：
- GUI界面不显示
- 托盘右键配置混乱
- 在设置为系统代理情况下显示为蓝色图标。
[
![QQ截图20240514073359](https://github.com/2dust/clashN/assets/79360463/ccb2b180-6cb8-42b5-a858-cd2896aa717d)
](url)

```json
  "globalHotkeys": [
    {
      "GlobalHotkey": 0,
      "Alt": true,
      "Control": true,
      "Shift": false,
      "KeyCode": 164
    },
```

将**guiNConfig.json**重置后，重启应用恢复正常。
```json
  "globalHotkeys": [
    {
      "GlobalHotkey": 0,
      "Alt": false,
      "Control": false,
      "Shift": false,
      "KeyCode": null
    },
```

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/releases/tag/6.49
请尝试使用v2rayN，本app将不再维护
