### ISSUE TITLE
选择和切换节点功能有问题

### ISSUE THREAD

**Issue by wyjtm** [2dust/clashN#355]
选择和切换节点功能有问题

情况如下
比如，双击从a节点切换到b，然后在浏览器刷新，发现还是a节点的ip信息，然后切换到c然后回到浏览器刷新还是a节点的ip信息；

只有切换节点后，再去点击左上角箭头，下面提示配置成功，再去浏览器刷新才会发现ip变化了，

上面问题是在下网盘的时候遇到的，网盘免费用户一个ip一小时内只能下载一次；发现换节点没用无法再次下载，才发现clashN切换节点功能有bug；

同样使用Clash Verge没有这个问题，单击切换节点再刷新网页就能再次下载了

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/releases/tag/6.49
请尝试使用v2rayN，本app将不再维护
