### ISSUE TITLE
可以支持混合端口吗

### ISSUE THREAD

**Issue by ie13** [2dust/clashN#38]
在参数设置，Core:基础设置里能增加本地混合端口mixed-port选项吗

**Comment by 2dust** [comment]
请问本地混合端口的优势是什么

**Comment by ie13** [comment]
混合端口可以一个端口同时支持socks5和http，这样不管是支持socks5还是http的软件都可以填同一个端口号，操作上方便一点

**Comment by ie13** [comment]
> 请问本地混合端口的优势是什么

混合端口可以一个端口同时支持socks5和http，这样不管是支持socks5还是http的软件都可以填同一个端口号，操作上方便一点

**Comment by 2dust** [comment]
[clashN-test.zip](https://github.com/2dust/clashN/files/8602994/clashN-test.zip)

测试下

**Comment by ie13** [comment]
> [clashN-test.zip](https://github.com/2dust/clashN/files/8602994/clashN-test.zip)
> 
> 测试下

混合端口可以使用，感谢

**Comment by fyhzc** [comment]
在主界面左下角也显示个：混合端口：1080
