### ISSUE TITLE
更新订阅提示：无效的订阅内容

### ISSUE THREAD

**Issue by staoran** [2dust/clashN#39]
更新订阅开始
free->开始获取订阅内容
free->获取订阅内容成功
free->无效的订阅内容
自己私有的订阅源，网上公开的订阅源，都是这个提示。
这些订阅源的格式都是合法的，在其他gui都可以正常使用的。
使用原始的Base64编码格式的订阅源再使用内置的订阅转换是可以成功更新订阅源。
所以就是不知道我们自己生成的yml和系统内置生成的yml有何区别导致报无效的订阅内容。
或者问题出在下载阶段？明明没有下载成功却报 获取订阅内容成功 ？（可能性最大）

如下网址：
https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml
https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
Base64编码格式的订阅源 https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity

**Comment by staoran** [comment]
看来就是下载的问题吧。
更新订阅(不通过代理)  重复N多次，偶尔能成功一次。
clash_subscription->开始获取订阅内容
clash_subscription->获取订阅内容成功
clash_subscription->更新订阅结束

更新订阅(通过代理)  重复N多次，偶尔能失败一次。
pro->开始获取订阅内容
pro->获取订阅内容成功
pro->无效的订阅内容

但是这些订阅，使用其他软件，不管是通过代理还是直连更新，都是直接能成功下载和更新的。

**Comment by 2dust** [comment]
githubusercontent 间歇性不能访问
Base64编码格式的订阅源请勾选订阅转换

**Comment by FlameSky-S** [comment]
遇到同样的问题，无论是否通过代理更新都提示无效内容。订阅链接输入浏览器可以100%正确获得base64编码，浏览器输入订阅转换＋订阅链接也可以获得正确的输出。尝试过清除系统代理再更新，也没有解决。

手动修改了yaml中proxies的地址，再次更新仍然未解决。退出软件重启，问题解决。

由于debug日志中并未记录相关问题，所以并不清楚到底是哪里出了问题。

**Comment by staoran** [comment]
@FlameSky-S 别折腾了，浪费时间，换别的软件吧 😄

**Comment by 2dust** [comment]
[clashN-test.zip](https://github.com/2dust/clashN/files/9394511/clashN-test.zip)

改进了订阅的提示，更新了测试 @FlameSky-S

**Comment by FlameSky-S** [comment]
> 改进了订阅的提示，更新了测试

感谢更新，暂时无法复现问题，后面遇到再反馈。
