### ISSUE TITLE
建议: 给 [自动选择] 提供新的检测机制

### ISSUE THREAD

**Issue by Masir01** [2dust/clashN#40]
尊敬的开发者: 
使用[自动选择]时, 不知道是机场服务器原因还是本人宽带运营商的原因, 有时候会出现看一阵子youtube节点就挂掉的现象, 但是它又不会重新自动切换, 所以使用[自动选择]体验很差. 当然, 我不知道其他用户有没有类似情况. 

所以大多数时间只能设置并使用 [节点选择], 但是一旦更新订阅, 服务器链接发生改变, [节点选择]设置即会丢失. 

开发者是否可以考虑单独给[自动选择]升级或者使用新的检测机制:
  比如每隔一段时间(短周期), 检测服务器是否可以连通 或者 检测google是否可以连通;
  或者更智能的检测机制!

**Comment by 2dust** [comment]
自动选择是clash-core提供的功能，如果有问题请到core那边反馈

**Comment by 2dust** [comment]
[clash core](https://github.com/Dreamacro/clash) and [Clash.Meta core](https://github.com/MetaCubeX/Clash.Meta)
