### ISSUE TITLE
端口的疑问，启动不起来？

### ISSUE THREAD

**Issue by zgithubx-code** [2dust/clashN#42]
订阅地址通过转换后 ，载入到软件里面，回车后显示这个提示。在当前代理里面看不到节点。那位指教一下？

time="2022-05-11T16:39:44+08:00" level=error msg="External controller listen error: listen tcp 127.0.0.1:9090: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

**Comment by 2dust** [comment]
把9090端口改大点，比如19090

**Comment by zgithubx-code** [comment]
收到，但是为什么我导入转换玩的clash的订阅地址，回车后没有反应那。提示取得默认配置失败。

**Comment by 2dust** [comment]
[clashN-test2.zip](https://github.com/2dust/clashN/files/8700117/clashN-test2.zip)

请用此版本测试
如有问题请反馈
