### ISSUE TITLE
建议在设置加个“启用ipv6”选项。不然配置文件xxx.yaml中的ipv6服务器不能用，信息栏显示"连接错误：ip版本错误"

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#43]
time="2022-05-14T02:01:08+08:00" level=warning msg="[TCP] dial 国外网站 (match DomainSuffix/youtube.com) to www.youtube.com:443 error: [2001:19f0:5:14da:5400:03ff:fe60:56be]:443 connect error: ip version error"

**Comment by fyhzc** [comment]
![image](https://user-images.githubusercontent.com/26890748/168343054-c8c7d93c-fc44-4551-8948-393ae1c55a89.png)

**Comment by fyhzc** [comment]
和cfw中的一般

**Comment by 2dust** [comment]
[clashN-test.zip](https://github.com/2dust/clashN/files/8692799/clashN-test.zip)

写死了ipv6: true
测试下是否可以

**Comment by fyhzc** [comment]
可以了。正常可以通了，
但个人觉的还是像cfw一样好，不用写死。给个选项自己设定好

**Comment by 2dust** [comment]
刚刚给的是测试，后面会加上

**Comment by fyhzc** [comment]
好的，还有个人觉的tun模式的驱动的安装和删除。也可以在设置里加个开关。如cfw一样。

**Comment by fyhzc** [comment]
tun模式的驱动的安装和删除
![fff](https://user-images.githubusercontent.com/26890748/168424270-8c9213bf-55e0-4d38-8e6a-04f778712dc9.JPG)

**Comment by 2dust** [comment]
> 好的，还有个人觉的tun模式的驱动的安装和删除。也可以在设置里加个开关。如cfw一样。

给N管理员权限，随时开tun就行了。
没有必要安装个服务浪费资源

**Comment by fyhzc** [comment]
哦，那就好。嘻嘻
