### ISSUE TITLE
订阅转换功能中的转换接口 https://sub.xeton.dev/不好用了

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#44]
升级(https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.11.0)后
订阅转换功能中的转换接口 https://sub.xeton.dev/不好用了
核心core 类型换成Clash.Meta就会在信息窗口中出错

可以更换转换接口,修改guiNConfig.json文件中的subConvertUrl属性
    "subConvertUrl": "https://sub.xeton.dev/sub?target=clash&url={0}",
    "subConvertUrl": "https://sub.id9.cc/sub?target=clash&new_name=true&url={0}",
就行了

另附：核心core 类型换成Clash就没错

订阅转换用的是https://acl4ssr-sub.github.io/

**Comment by 2dust** [comment]
使用https://sub.xeton.dev 转换后的配置，检查下是否包含!<str>

**Comment by fyhzc** [comment]
是升级Clash.Meta为v1.11.0后出现的错误，v1.10.0没出错。

**Comment by 2dust** [comment]
把配置文件发一个到邮箱captainIronng@protonmail.com

**Comment by fyhzc** [comment]
错误效果
![wwww](https://user-images.githubusercontent.com/26890748/168459411-d5adc4c4-50d3-4c23-bd05-4c45e1825386.JPG)

**Comment by fyhzc** [comment]
邮件发了

**Comment by 2dust** [comment]
找到问题了，在这里 ` MATCH,,🐟 漏网之鱼,dns-failed`
最后的这条有两个逗号,新版Clash.Meta会报错
你有空把这个提交给Clash.Meta请他们看看

**Comment by fyhzc** [comment]
要不在设置中设一个“更换转换接口”功能

**Comment by fyhzc** [comment]
那就多放几上预设的吧
