### ISSUE TITLE
请问自动更新时默认是以什么方式进行的？

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#48]
默认是通过哪种方式：1.不通过代理
                                     2.通过代理
                                     3.自动判断（先不通代理，如不通再自动切换到通过代理）
![捕获](https://user-images.githubusercontent.com/26890748/170900389-6b527bf2-4a0a-45b7-be9e-2ee34eb95cc0.JPG)

**Comment by 2dust** [comment]
2.通过代理

**Comment by fyhzc** [comment]
那就注明啊，要是在主界面上有订阅源都挂了，自动更新设置就无效了，结论就是要保证主界面中的所有订阅源至少要保证有 一个是有效的。这里的自动更新才有效

**Comment by fyhzc** [comment]
觉的还是设智能为好，顺序可以是：代理-----不通过代理------哪 个有效用哪 个

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.14
