### ISSUE TITLE
tun模式开启后 CPU 狂飙 直接100%

### ISSUE THREAD

**Issue by hihi427** [2dust/clashN#49]
tun模式开启后 CPU 狂飙 直接100% 系统卡死  log处疯狂刷记录

**Comment by HanHan666666** [comment]
我也是

**Comment by fyhzc** [comment]
是啊，感觉clash.meta不是太稳，开启后，系统资源占用比clash大多了。要是有可能。tun 模式也可选用clash

**Comment by HanHan666666** [comment]
> 是啊，感觉clash.meta不是太稳，开启后，系统资源占用比clash大多了。要是有可能。tun 模式也可选用clash

带有tun的是clash premium内核, 是不开源的

**Comment by fyhzc** [comment]
看来clashN选用clash.meta就是为了tun功能

**Comment by 2dust** [comment]
> 带有tun的是clash premium内核, 是不开源的

 请把相同的配置使用clash premium core 测试看看cpu占用

**Comment by 2dust** [comment]
把配置文件掩脱敏后发出来

**Comment by 2dust** [comment]
把配置文件（yaml）脱敏后发出来

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/8814137/clashN.zip)
测试下

**Comment by HanHan666666** [comment]
> [clashN.zip](https://github.com/2dust/clashN/files/8814137/clashN.zip) 测试下

测试正常, 可以正常使用

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.12

**Comment by shaojilin** [comment]
我的也是问题解决了 看看是不是设置中系统代理开关开了，两者不能同时开启会冲突。
