### ISSUE TITLE
1.1版，已经下载Clash.Meta，还在使用，可检查更新-更新Meta Core那还是不停的提示要下载更新

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#5]
1.1版，已经下载Clash.Meta，还在使用，可检查更新-更新Meta Core那还是不停的提示要下载更新
![image](https://user-images.githubusercontent.com/26890748/161434046-f33f8448-7a5f-4f3a-ac50-311550c9f0d7.png)

**Comment by ag2s20150909** [comment]
you can use this api Check for updates

https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/latest

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.2
