### ISSUE TITLE
建议增加主界面上右键所选任意订阅源更新的方式

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#50]
附注：所谓“全部”是指：主界面上所有在“配置文件”中打勾了“启用更新订阅”的订阅源
![0000](https://user-images.githubusercontent.com/26890748/170901963-9f0f426b-d4dc-4084-bebe-99bdc41bcfe5.JPG)

![fff](https://user-images.githubusercontent.com/26890748/170901988-576afedc-4ab2-44ec-b881-15e1007139f9.JPG)

**Comment by 2dust** [comment]
多选更新时，是否过滤掉不打勾的订阅呢？

**Comment by fyhzc** [comment]
当然，前题是以”全部“为准。
附注：所谓“全部”是指：主界面上所有在“配置文件”中打勾了“启用更新订阅”的订阅源

**Comment by fyhzc** [comment]
哪 个没打勾 ，在主界面中”更新订阅（转换）中一目了然

**Comment by fyhzc** [comment]
全更新（打勾状态）
选更新（打勾状态-可多选）

这样写是不是明白些

**Comment by 2dust** [comment]
> 全更新（打勾状态） 选更新（打勾状态-可多选）
> 
> 这样写是不是明白些

可行

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.12
