### ISSUE TITLE
建议“系统代理设置”中增加配置文件中“mode"三种模式的强制复写原配置文件中mode状态

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#51]
mode:直连
          规则 
          全局
![kkkkk](https://user-images.githubusercontent.com/26890748/170903575-274634a1-f2a2-428b-86b4-e8b174f24215.jpg)

**Comment by 2dust** [comment]
请问什么场景会用到全局和直连？

**Comment by fyhzc** [comment]
用到时就有用了呀。看cfw和clash.net上都有，心㾕㾕的。
配置文件的mode的默认通常是mode: Rule   ，有了这个设置就方便改了呀。
右下快捷菜单中的“自动配置系统何理不会变就以这里设置的为准

**Comment by fyhzc** [comment]
自动配置系统代理

配置文件模式（mode）: 源配置（原始）  # 【注：这里随原配置】
                                        强制复写(直连/规则/全局)    #【注：这里随clashN强制复写原配置】

**Comment by fyhzc** [comment]
托盘菜单加个”配置模式“
下分：1，随原mode配置
           2，覆写mode配置：
                rule/global/direct
您看这样可好？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.12

**Comment by 2dust** [comment]
> 托盘菜单加个”配置模式“ 下分：1，随原配置mode 2，覆写配置mode： rule/global/direct 您看这样可好？
> 
> 默认还是设为1，随原mode配置 上面 2，覆写mode配置的设置只有在勾选了”自动配置系统代理“才有效

路由模式设置和自动配置系统代理无关，一个是core功能，也给是windows系统功能
