### ISSUE TITLE
应用配置文件报找不到Country.mmdb

### ISSUE THREAD

**Issue by shuzeyuxuan** [2dust/clashN#55]
配置成功
trojan
启动服务(2022/6/4 12:06:00)...
time="2022-06-04T12:06:01+08:00" level=info msg="Can't find MMDB, start download"
time="2022-06-04T12:06:22+08:00" level=fatal msg="Initial configuration directory error: can't initial MMDB: can't download MMDB: Get \"https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb\": dial tcp 128.121.243.77:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

然后我手动下载Country.mmdb，放到软件根目录，还是报同样的错误

系统：win11 22000.708

**Comment by 2dust** [comment]
Country.mmdb是core自动下载的，位置应该系统盘
或使用便携版，在ClashN目录下面新建一个文件夹data 
https://github.com/2dust/clashN/issues/26

**Comment by shuzeyuxuan** [comment]
Country.mmdb放到data目录，问题解决了
