### ISSUE TITLE
"多选更新订阅“是不是改为”自选更新订阅“来的更贴切

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#56]
从下面选一个

**Comment by fyhzc** [comment]
更新订阅（不通过代理）
更新订阅（不通过代理）

**Comment by fyhzc** [comment]
更新订阅（不通过代理）
更新所选（多选）订阅（不通过代理）
更新订阅（通过代理）
更新所选（多选）订阅（通过代理）

**Comment by fyhzc** [comment]
更新订阅（不通过代理）
更新所选（多选）订阅（不通过代理）
更新订阅（通过代理）
更新所选（多选）订阅（通过代理）

**Comment by 2dust** [comment]
能明白意思就行
