### ISSUE TITLE
翻看：“设置”-“参数设置”-“clashN设置”，发现“更新core时忽略geo文件”这个geo文件在下载的两个core压缩包中根本不存在啊

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#57]
如下图
![xxxxx](https://user-images.githubusercontent.com/26890748/172411678-691c3546-214c-4601-a8ed-0718315a7363.PNG)

手动下载的两个core文件压缩包
![3333](https://user-images.githubusercontent.com/26890748/172411718-c700c849-7fde-41e5-a5e4-1fba68509721.PNG)

“更新core时忽略geo文件”这个选项是不是多余啊。
![666](https://user-images.githubusercontent.com/26890748/172412484-f53d9ac1-9a82-4374-9b60-87dd03e61e14.PNG)

**Comment by 2dust** [comment]
这个是预留的，Clash.Meta可能会包含
