### ISSUE TITLE
clash文件只能用“自动选择”的节点，其他的节点不能用，也无法切换自动选择的节点

### ISSUE THREAD

**Issue by hjp070928** [2dust/clashN#6]
比如CFW就可以使用全局模式，现在1.1版本中只能强制使用自动选择的节点，其他的模式都无法使用，也无法切换

**Comment by bios99** [comment]
**clash文件只能用“自动选择”的节点**——当前代理-左侧规则选一个-右侧选择节点（enter）估计你的配置文件是不是只有自动选择？自动选择的是不能手动改的。
**全局模式**——GLOBAL了解下

**Comment by hjp070928** [comment]
> **clash文件只能用“自动选择”的节点**——当前代理-左侧规则选一个-右侧选择节点（enter）估计你的配置文件是不是只有自动选择？自动选择的是不能手动改的。 **全局模式**——GLOBAL了解下
![屏幕截图 2022-04-04 131428](https://user-images.githubusercontent.com/37642754/161478396-2613525b-7005-4da6-8c17-46c47d094daa.png)

**Comment by hjp070928** [comment]
> **clash文件只能用“自动选择”的节点**——当前代理-左侧规则选一个-右侧选择节点（enter）估计你的配置文件是不是只有自动选择？自动选择的是不能手动改的。 **全局模式**——GLOBAL了解下

我就是全局模式用不了才反馈的

**Comment by 2dust** [comment]
什么情况下会用到全局模式，还有直连模式？

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.12
