### ISSUE TITLE
能出个订阅转换教程吗

### ISSUE THREAD

**Issue by Yzcloud** [2dust/clashN#60]
用自己的模板或者本地模板教程😂

**Comment by ublubeu** [comment]
因为有写订阅更新失败🙈

**Comment by 2dust** [comment]
看这里，有详细的文档  https://github.com/tindy2013/subconverter
如果订阅更新失败，可以把您的订阅放到浏览器中打开看看结果

**Comment by ublubeu** [comment]
> 看这里，有详细的文档 https://github.com/tindy2013/subconverter 如果更新失败，可以把您的订阅浏览器中打开查看结果

同样的配置下载到本地就可以用，然后订阅链接Clash for Windows也可以用，我试了ClashN要嘛更新失败，要嘛转换配置文件失败，订阅链接用>启用订阅转换 就可以完美使用，作者可以帮忙看下什么问题吗？我在TG群组里看到有人反馈同样的问题。谢谢！ 
![photo_2022-06-18_09-53-03](https://user-images.githubusercontent.com/88927779/174418771-cbec20cc-21a2-4375-ac0e-01d4780d6bb3.jpg)
![photo_2022-06-18_10-17-00](https://user-images.githubusercontent.com/88927779/174418772-d85c48a3-da19-413c-b2db-7822ec291bba.jpg)

**Comment by ublubeu** [comment]
> > 看这里，有详细的文档https://github.com/tindy2013/subconverter如果更新失败，可以把您的订阅浏览器中打开查看结果
> 
> 的配置下载到本地就可以使用，然后订阅链接 Clash for Windows 也可以使用，我试了 ClashN 嘛要更新失败，要转换配置文件失败，订阅链接用>启用订阅转换就可以完美使用，作者可以帮忙看一下问题吗？我在TG里有什么看到同样的问题！ ![照片_2022-06-18_09-53-03](https://user-images.githubusercontent.com/88927779/174418771-cbec20cc-21a2-4375-ac0e-01d4780d6bb3.jpg) ![照片_2022-06-18_10-17-00](https://user-images.githubusercontent.com/88927779/174418772-d85c48a3-da19-413c-b2db-7822ec291bba.jpg)

用的是clashN-Core.zip 1.13版本，

**Comment by ublubeu** [comment]
咨询了长风大佬，已经发现问题出在哪里了，

**Comment by ublubeu** [comment]
希望作者大大看到后可以修改一下，麻烦啦，谢谢！

**Comment by 2dust** [comment]
本地监听端口不要重复。
通过代理更新订阅时会用到已经启动的代理
不通过代理更新订阅时，如果开启了系统代理也会用到系统代理

**Comment by ublubeu** [comment]
> 监听到本地端口 时，会通过代理通知启动不通过代理订阅的时候启动代理 ，如果不代理订阅时，系统代理会启动代理。

![微信图片_20220619121134](https://user-images.githubusercontent.com/88927779/174465512-8a8bcfa7-960d-4a7d-acc5-37d563ed5648.png)
![微信图片_20220619121139](https://user-images.githubusercontent.com/88927779/174465515-59fb1c9b-b78f-4d26-a4dc-08c0328e11cf.png)
（https://paste.to/cn/raw/62aea2bbb2f52）<配置A
