### ISSUE TITLE
订阅上次更新时间

### ISSUE THREAD

**Issue by lichaoyangnice** [2dust/clashN#62]
可以在界面显示上次订阅更新时间吗？订阅较多时方便查看和管理，保持最新订阅

**Comment by 2dust** [comment]
[clashN-test1.zip](https://github.com/2dust/clashN/files/8986184/clashN-test1.zip)

使用此版测试

**Comment by 2dust** [comment]
[clashN-test2.zip](https://github.com/2dust/clashN/files/8986239/clashN-test2.zip)

使用此版本测试

**Comment by lichaoyangnice** [comment]
> 
可以呢，感谢大佬
