### ISSUE TITLE
msg="[TCP] dial DIRECT (match DstPort/80) to blank:80 error: lookup blank: no such host"

### ISSUE THREAD

**Issue by Hreint** [2dust/clashN#63]
您好，

我发现打开微信 windows 版之后接收文件时 clashN 会出现以下的错误提示，有时候会接受文件失败，请问这是代表什么意思呢？怎么解决这个错误呢？谢谢！

level=warning msg="[TCP] dial DIRECT (match DstPort/80) to blank:80 error: lookup blank: no such host"

PS: 用的是 clash_meta core，开了 tun 模式

**Comment by 2dust** [comment]
可以把日志提交给 https://github.com/MetaCubeX/Clash.Meta

**Comment by Hreint** [comment]
好的，感谢回复！
