### ISSUE TITLE
部分软件出现 SSL connect error

### ISSUE THREAD

**Issue by jokervTv** [2dust/clashN#64]
使用部分软件（例如`cargo`）会出现 `SSL connect error (schannel: failed to receive handshake, SSL/TLS connection failed)` 使用 clash for windows 则没有问题，请问这个是 clashN 的问题吗，谢谢

**Comment by 2dust** [comment]
请提供log
clashN是使用clash-core提供服务

**Comment by jokervTv** [comment]
最后发现是供应商的问题，麻烦了
