### ISSUE TITLE
建议修改软件布局

### ISSUE THREAD

**Issue by kettly1260** [2dust/clashN#65]
clash用的多的是节点的切换而不是订阅的切换，目前应该是套用的v2rayN的UI，但是这个交互逻辑和clash不大一样，能不能主页直接是节点的选择和切换，二级页面才是订阅的切换。
而且节点规则排序那里没有按照订阅设置的进行排序，看起来很混乱

**Comment by 2dust** [comment]
[clashN-test1.zip](https://github.com/2dust/clashN/files/9042922/clashN-test1.zip)

改了一个版本，帮忙测试

**Comment by kettly1260** [comment]
> [clashN-test1.zip](https://github.com/2dust/clashN/files/9042922/clashN-test1.zip)
> 
> 改了一个版本，帮忙测试

看了看最新发布的，确实更好用了，但是这个代理排序的问题能不能也修改一下吗？代理排序和自己确定的订阅排序不一致。比如节点选择之类的我规则设定里面应该在前面，但是现在排序乱了还没办法调整

**Comment by kettly1260** [comment]
https://github.com/kettly1260/clash-scholar.google/blob/master/config/ACL4SSR_Online_scholar_google.ini

我自己的配置，基本上是ACL4SSR的，其他的clash都可按照自己的排序显示

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.16
