### ISSUE TITLE
加载远程配置文件的需求

### ISSUE THREAD

**Issue by samulo911** [2dust/clashN#66]
clashN-配置文件-订阅网址这一选项的内容能否兼容个人配置文件外链地址？ 现在填入外链地址，本地无法生成正确的配置文件；勾选“启用订阅转换”选项后，能生成配置文件，但跟原配置相去甚远。感谢！

**Comment by 2dust** [comment]
订阅网址这里填写任意有效的链接，只要能获取到内容就可以生成本地文件，不需要一定选择订阅转换。
可以把您的链接发到邮箱我们来测试

**Comment by samulo911** [comment]
http://kdy.19900819.xyz:5212/api/v3/file/get/10/test.yaml?sign=x1VVWyW2-JZCrsLTWpqzbaYrBBLoGZaOQ9YtxXKciXk%3D%3A0
可以试下这个地址。在CFW里可以通过该链接在本地生成跟远端一致的配置文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月5日(星期二) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [2dust/clashN] 加载远程配置文件的需求 (Issue #66)





 
订阅网址这里填写任意有效的链接，只要能获取到内容就可以生成本地文件，不需要一定选择订阅转换。
 可以把您的链接发到邮箱我们来测试

**Comment by 2dust** [comment]
使用你的链接订阅成功

**Comment by samulo911** [comment]
测试了下，貌似是缩进的问题。按标准缩进的文件没法导入，而未遵循标准，全部顶格写的文件能导入，但是无法正常运行
