### ISSUE TITLE
Updating clash_meta core issue

### ISSUE THREAD

**Issue by m-koushan** [2dust/clashN#7]
When I press `Update Meta Core` it bring me the link to download while I have the latest version

![image](https://user-images.githubusercontent.com/50526840/161523818-cbf4ae57-d688-4831-9a70-6f988ff88e3a.png)

Also it doesn't update it correctly, as you can see in the image after downloading some of the file it stops without replacing the file and in the console it doesn't give any error or warning about that

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.2
