### ISSUE TITLE
“更新配置文件”文字更新建议

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#71]
这几天刚刚开始从Clash for Windows转过来，clashN很大的一个优点就是节省资源。其他除了一些人机交互界面上的问题，挺好用的。

关于配置文件的更新，能不能做成这样：

在主界面工具栏上的配置文件按钮的扩展菜单里，将“更新订阅”开头的两个选项改为“更新全部订阅”，将“多选更新订阅”开头的两个选项改为“更新所选订阅”，感觉这样逻辑更清楚一点。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.16
