### ISSUE TITLE
关于当前代理左边栏目里的条目排序

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#72]
现在的排序应该是根据别名做升序排列的。

现在不少人是通过类似acl4ssr这样的订阅转换获取订阅的，在本地的yaml文件里，“🚀 节点选择”，排在第一个，其次是“♻️ 自动选择”，建议也是根据yaml里面的顺序做显示。这样第一眼就能看到需要手动调整的代理节点是什么。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.16
