### ISSUE TITLE
建议增加定时“延时测试”的功能

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#73]
现在的延时测试都需要手动触发，建议可以做一个配置项，让用户自己定义每隔多少秒进行一次对当前订阅中所有代理节点的延时测试，测试的结果可以展示到所有的“proxy-groups”里面的同一个代理节点上。

自动定时做延时测试还能够帮助那些“URL Test”类型的proxy-groups。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.16
