### ISSUE TITLE
yaml配置文件里IP为IPv6时已经加中括号了，软件会再加一次中括号

### ISSUE THREAD

**Issue by willaytoun** [2dust/clashN#74]
![Snipaste_2022-07-12_20-31-12](https://user-images.githubusercontent.com/43229736/178495210-97612121-6969-4b72-83e6-e1a17d527e28.png)
![Snipaste_2022-07-12_20-29-13](https://user-images.githubusercontent.com/43229736/178495282-2aae2da1-4fb2-4fb6-bd3f-72da0e0b0196.png)

把上边yaml里IPv6的中括号去掉是可以正常使用的

**Comment by 2dust** [comment]
这个需要问clash-core那边，看下calsh wiki
