### ISSUE TITLE
记住手工选中的服务器节点

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#75]
1.15版本中如果选择A配置文件，然后在一个服务器组中选择了一个特定的节点，接着切换到另一个配置文件B，接着再切换回A，会发现之前的那个服务器组已经恢复默认的选择，而不是之前手动选择的那个节点。

希望在手动修改选择的节点的时候能记住选择，原因是很多节点的流量倍数是很高的，但是ping很低，默认都是选中ping低的节点。每次启动电脑后再启动clashN，就会回到默认的ping很低的节点，造成流量浪费。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.0
试用下，是否有此问题，反馈
