### ISSUE TITLE
启动软件和当前使用节点比较慢时不会自动Ping后选择节点

### ISSUE THREAD

**Issue by willaytoun** [2dust/clashN#79]
启动软件只是使用第一个节点，当前节点比较慢时不会自动切换，节点延迟的"测试结果"也不会显示。不知道是"当前代理"这里显示问题还是就是不会自动Ping然后切换。
![Snipaste_2022-07-19_17-17-12](https://user-images.githubusercontent.com/43229736/179716618-ac7454e5-13f1-4262-8663-ce9b6968a6f1.png)

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.16

**Comment by willaytoun** [comment]
更新到了1.16，配置文件首次启动还是没有Ping的"测试结果"，"自动选择"依然为第一个节点。
设置了"自动延迟测试的间隔"，自动Ping之后就没有上面的问题了。
![image](https://user-images.githubusercontent.com/43229736/181400676-851072be-7fa9-48c4-8283-b19ab7472cb9.png)

**Comment by 2dust** [comment]
[clashN.zip](https://github.com/2dust/clashN/files/9209377/clashN.zip)

改进些，请反馈

**Comment by willaytoun** [comment]
已测试，首次启动可以正常Ping"自动选择"也没有问题。只是我不知道下边提示先"Refresh proxies"然后"Clash Proxies Delay Test"然后再"Refresh proxies"，这个是连着Ping了两次吗？
![image](https://user-images.githubusercontent.com/43229736/181576579-3760dba5-bc3d-401f-8cd3-9c0fb8c2595b.png)

**Comment by 2dust** [comment]
暂时只能做到这样了
日志显示是刷新了两次

**Comment by willaytoun** [comment]
嗯嗯 已经很好了，谢谢😀

**Comment by willaytoun** [comment]
我发现一个配置文件里的节点都Ping不通，再切换到另一个配置文件之后的第一次"自动选择"就会出现上面的问题，我用1.16版本也是这样。

**Comment by 2dust** [comment]
暂时关闭
