### ISSUE TITLE
同样的配置文件 clashN tun 模式总是出错，clash for windows 就可以

### ISSUE THREAD

**Issue by Hreint** [2dust/clashN#80]
你好，

我一直很喜欢作者您的软件，之前一直在使用 v2rayN，看到 clashN 支持 tun 模式我就想试一试，因为需要代理所有流量。但 clashN的 tun 模式我一直没整明白，我的配置文件在 clash for windows 的 tun 模式就能用， 一到 clashN 这就不行了，以下是报错的日志：

time="2022-07-23T12:33:22+08:00" level=info msg="Start initial configuration in progress"
time="2022-07-23T12:33:22+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-07-23T12:33:22+08:00" level=warning msg="Auto detect interface: WLAN"
time="2022-07-23T12:33:22+08:00" level=info msg="Initial configuration complete, total time: 0ms"
time="2022-07-23T12:33:22+08:00" level=info msg="Sniffer is closed"
time="2022-07-23T12:33:22+08:00" level=info msg="Start initial compatible provider default"
time="2022-07-23T12:33:22+08:00" level=info msg="Start initial compatible provider PROXY"
time="2022-07-23T12:33:29+08:00" level=warning msg="[TCP] dial PROXY (match DomainSuffix(google.com)) to mtalk.google.com:5228 error: context deadline exceeded"
time="2022-07-23T12:33:31+08:00" level=warning msg="[TCP] dial PROXY (match Match()) to www.msftconnecttest.com:80 error: context deadline exceeded"
time="2022-07-23T12:33:34+08:00" level=warning msg="[TCP] dial PROXY (match DomainSuffix(google.com)) to mtalk.google.com:5228 error: context deadline exceeded"
time="2022-07-23T12:33:34+08:00" level=warning msg="[UDP] dial PROXY (match DomainSuffix/google.com) to www.google.com:443 error: new vmess client error: context deadline exceeded"
time="2022-07-23T12:33:35+08:00" level=warning msg="[TCP] dial PROXY (match Match()) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-23T12:33:38+08:00" level=warning msg="[TCP] dial PROXY (match DomainSuffix(google.com)) to www.google.com:443 error: context deadline exceeded"
time="2022-07-23T12:33:38+08:00" level=warning msg="[UDP] dial PROXY (match DomainSuffix/google.com) to www.google.com:443 error: new vmess client error: context deadline exceeded"
time="2022-07-23T12:33:38+08:00" level=warning msg="[TCP] dial PROXY (match DomainSuffix(google.com)) to www.google.com:443 error: context deadline exceeded"
time="2022-07-23T12:33:42+08:00" level=warning msg="[TCP] dial PROXY (match Match()) to self.events.data.microsoft.com:443 error: context deadline exceeded"

我的配置文件是：

proxies:
  - name: US
    type: vmess
    server: xxx
    port: 443
    uuid: xxx
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: false
    network: tcp

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - US

rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-KEYWORD,google,PROXY
  - DOMAIN,google.com,PROXY
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,PROXY

有人能知道问题出在哪吗？或者能贴一下能够正常使用 clashN 的 tun 模式的配置吗？愿意有偿求助。

**Comment by 2dust** [comment]
是否已经管理员运行？
请把完整配置发来，替换掉关键信息

**Comment by httpsColon** [comment]
> 是否已经管理员运行？ 请把完整配置发来，替换掉关键信息

非常好工作，electron开发代理程序性能简直垃圾

**Comment by Hreint** [comment]
> 是否已经管理员运行？ 请把完整配置发来，替换掉关键信息

您好，

已经是以管理员身份运行了，上面发的就是我的完整配置，因为这个配置在 clash for windows 是可以用的，所以我就用在 clashN 上，但发现 tun 模式就不能用，系统代理倒是正常。

我又尝试以下配置，也是不行：

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: ':9090'
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
  fallback:
    - 8.8.8.8
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
proxies:
  - name: HK
    type: vmess
    server: XXXX
    port: XXXX
    uuid: XXXX
    alterId: 0
    cipher: auto
    network: tcp
    udp: true
proxy-groups:
  - name: proxy
    type: select
    proxies:
      - HK
rules:
  - DOMAIN-KEYWORD,voddazn,proxy
  - DOMAIN,d151l6v8er5bdm.cloudfront.net,proxy
  - DOMAIN-SUFFIX,d151l6v8er5bdm.cloudfront.net,proxy
  - DOMAIN-SUFFIX,d1sgwhnao7452x.cloudfront.net,proxy
  - DOMAIN-SUFFIX,dazn-api.com,proxy
  - DOMAIN-SUFFIX,dazn.com,proxy
  - DOMAIN-SUFFIX,dazndn.com,proxy
  - DOMAIN-SUFFIX,dcblivedazn.akamaized.net,proxy
  - DOMAIN-SUFFIX,indazn.com,proxy
  - DOMAIN-SUFFIX,indaznlab.com,proxy
  - DOMAIN-SUFFIX,sentry.io,proxy
  - PROCESS-NAME,OneDrive,proxy
  - PROCESS-NAME,OneDriveUpdater,proxy
  - DOMAIN-KEYWORD,1drv,proxy
  - DOMAIN-KEYWORD,onedrive,proxy
  - DOMAIN-KEYWORD,skydrive,proxy
  此处省略...后面这些应该是没问题的，因为 cfw 一直能正常使用

**Comment by Hreint** [comment]
> 是否已经管理员运行？ 请把完整配置发来，替换掉关键信息

不知道您能否发一个您那边能用的配置，把节点信息模糊掉就行。

**Comment by 2dust** [comment]
[tun-dns.zip](https://github.com/2dust/clashN/files/9198676/tun-dns.zip)

@Hreint  这个配置，测试下看

**Comment by Hreint** [comment]
> [tun-dns.zip](https://github.com/2dust/clashN/files/9198676/tun-dns.zip)
> 
> @Hreint 这个配置，测试下看

还是不行，已经确定是以管理员身份运行，然后用了您提供的配置文件，把 proxies 部分替换成我的，系统代理一点问题都没有，只要开 tun 模式就报错...但奇怪的是 clash for windows 就没问题...clash for windows 的 tun 可以连上，但是用上一会就时不时上不了网，得要关闭再打开才行...系统代理就一直没问题。

错误日志：
配置成功
import custom@2022/7/27
启动服务(2022/7/27 23:07:41)...
time="2022-07-27T23:07:41+08:00" level=info msg="Start initial configuration in progress"
time="2022-07-27T23:07:41+08:00" level=warning msg="Auto detect interface: WLAN"
time="2022-07-27T23:07:41+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-07-27T23:07:41+08:00" level=info msg="Initial configuration complete, total time: 13ms"
time="2022-07-27T23:07:46+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 224.0.0.252:5355 error: new vmess client error: context deadline exceeded"
time="2022-07-27T23:07:47+08:00" level=warning msg="[UDP] dial proxy (match IPCIDR/198.18.0.0/16) to 198.18.255.255:137 error: new vmess client error: context deadline exceeded"
time="2022-07-27T23:07:47+08:00" level=warning msg="[TCP] dial proxy (match Match/) to www.msftconnecttest.com:80 error: context deadline exceeded"
time="2022-07-27T23:07:49+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 239.255.255.250:1900 error: new vmess client error: context deadline exceeded"
time="2022-07-27T23:07:49+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/mtalk.google.com) to mtalk.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:49+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 224.0.0.252:5355 error: new vmess client error: context deadline exceeded"
time="2022-07-27T23:07:51+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 239.255.255.250:1900 error: new vmess client error: context deadline exceeded"
time="2022-07-27T23:07:52+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:52+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:54+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:54+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/mtalk.google.com) to mtalk.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:56+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:57+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:57+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:07:59+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:01+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:02+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:07+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 224.0.0.251:5353 error: new vmess client error: read tcp4 192.168.3.5:65318->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:08:07+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 153.254.86.179:27017 error: new vmess client error: read tcp4 192.168.3.5:65316->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:08:07+08:00" level=warning msg="[TCP] dial proxy (match IPCIDR/173.252.64.0/18) to www.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:10+08:00" level=warning msg="[UDP] dial proxy (match Match/) to 224.0.0.252:5355 error: new vmess client error: read tcp4 192.168.3.5:65330->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:08:12+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: read tcp4 192.168.3.5:65338->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:08:13+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gcp.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:13+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/google) to clients4.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:14+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:17+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/www.gstatic.com) to www.gstatic.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:18+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gcp.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:18+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/google) to clients4.google.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:19+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:23+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:25+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:25+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:28+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:30+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gcp.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:31+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:33+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:35+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gcp.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:36+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons2.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:39+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:41+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons2.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:44+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:45+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: read tcp4 192.168.3.5:65393->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:08:49+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/mtalk.google.com) to mtalk.google.com:5228 error: context deadline exceeded"
time="2022-07-27T23:08:49+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:49+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons3.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:54+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/mtalk.google.com) to mtalk.google.com:5228 error: context deadline exceeded"
time="2022-07-27T23:08:55+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons3.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:08:57+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/safebrowsing.googleapis.com) to safebrowsing.googleapis.com:443 error: read tcp4 192.168.3.5:65422->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:09:00+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons2.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:02+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/safebrowsing.googleapis.com) to safebrowsing.googleapis.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:05+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons2.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:06+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:07+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: read tcp4 192.168.3.5:65438->185.218.7.9:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
time="2022-07-27T23:09:10+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons4.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:11+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:13+08:00" level=warning msg="[TCP] dial proxy (match DomainKeyword/github) to alive.github.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:15+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons4.gvt2.com:443 error: context deadline exceeded"
time="2022-07-27T23:09:17+08:00" level=warning msg="[TCP] dial proxy (match DomainSuffix/gvt2.com) to beacons3.gvt2.com:443 error: context deadline exceeded"

配置文件可以看见是用了您提供的：
![1](https://user-images.githubusercontent.com/64591583/181284200-5341b197-5a3a-4744-9894-892deb98a0ea.PNG)

**Comment by WoChen5770** [comment]
我用的vless,使用系统代理正常,tun模式就断网,报错信息如下:
time="2022-07-28T18:06:46+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainSuffix(live.com)) to by3301.storage.live.com:443 error: never touched"
time="2022-07-28T18:06:46+08:00" level=warning msg="[TCP] dial Ⓜ️ 微软服务 (match DomainSuffix(live.com)) to by3301.storage.live.com:443 error: never touched"
time="2022-07-28T18:06:46+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP(CN)) to 183.3.224.144:80 error: never touched"
time="2022-07-28T18:06:47+08:00" level=warning msg="[TCP] dial 🎯 全球直连 (match GeoIP(CN)) to 203.119.129.34:443 error: never touched"

**Comment by 2dust** [comment]
启动tun模式后，clashN文件夹中的config.yaml就是配置文件
请把此文件提交给core那边看看 https://github.com/MetaCubeX/Clash.Meta

**Comment by 2dust** [comment]
https://github.com/Dreamacro/clash/releases/tag/premium
把clashN里面所有的clash-exe都删除了
下载下clash的p core放入文件夹
开tun模式测试

**Comment by Hreint** [comment]
> 

经测试，“把clashN里面所有的clash-exe都删除了，下载下 clash 的 p core 放入文件夹”，再开tun模式会提示缺少 clash meta 内核，然后我进行了一个骚操作，把 premium core 的文件名改成 Clash.Meta-windows-amd64.exe，就不提示缺少 meta 内核了，并且 tun 模式没问题！盛赞！

**Comment by Hreint** [comment]
> https://github.com/Dreamacro/clash/releases/tag/premium 把clashN里面所有的clash-exe都删除了 下载下clash的p core放入文件夹 开tun模式测试

经测试，“把clashN里面所有的clash-exe都删除了，下载下 clash 的 p core 放入文件夹”，再开tun模式会提示缺少 clash meta 内核，然后我进行了一个骚操作，把 premium core 的文件名改成 Clash.Meta-windows-amd64.exe，就不提示缺少 meta 内核了，并且 tun 模式没问题！盛赞！

**Comment by WoChen5770** [comment]
我对比了cfw和clashN的配置,有个不同就是我cfw配置了mixin-dns。
clashN好像目前还不支持mixin配置，这个有计划吗 @2dust

**Comment by 2dust** [comment]
> > https://github.com/Dreamacro/clash/releases/tag/premium 把clashN里面所有的clash-exe都删除了 下载下clash的p core放入文件夹 开tun模式测试
> 
> 经测试，“把clashN里面所有的clash-exe都删除了，下载下 clash 的 p core 放入文件夹”，再开tun模式会提示缺少 clash meta 内核，然后我进行了一个骚操作，把 premium core 的文件名改成 Clash.Meta-windows-amd64.exe，就不提示缺少 meta 内核了，并且 tun 模式没问题！盛赞！

那估计Meta-core的tun模式还有些问题，建议可以给他提交下log帮助改进。
在设置tun模式界面，clashN移除强制使用Meta-core

**Comment by 2dust** [comment]
> 我对比了cfw和clashN的配置,有个不同就是我cfw配置了mixin-dns。 clashN好像目前还不支持mixin配置，这个有计划吗 @2dust

你们cfw里面的mixin-dns部分代码给整合到clashN的配置文件中，
也就是clashN的配置文件你把dns部分写好写全
然后启动tun模式试一试
如果还是不行，看下[Hreint](https://github.com/Hreint) 的方法

**Comment by WoChen5770** [comment]
@2dust 我想我找到了原因
我自行编辑本地配置文件,把dns,出口网卡,tun写进去,成功上网。具体配置文件如下：
`dns:
  enable: true    
  enhanced-mode: redir-host
  listen: :53
  nameserver:
    - ~~~
  default-nameserver:
    - ~~~
  nameserver-policy:
    ~~~
interface-name: WLAN
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true`

**Comment by WoChen5770** [comment]
里面的关键点应该是我把clashN里tun默认的 ` auto-detect-interface: true `去掉了,自行指定了网卡

**Comment by WoChen5770** [comment]
还有个想法建议,希望大佬能把cfw的parsers功能做出来,可以自己追加配置一些路由

**Comment by WoChen5770** [comment]
> 还有个想法建议,希望大佬能把cfw的parsers功能做出来,可以自己追加配置一些路由

是指在更新订阅的情况下

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.18
增加了Mixin配置，可以试一试修改dns和tun

**Comment by WoChen5770** [comment]
> https://github.com/2dust/clashN/releases/tag/1.18 增加了Mixin配置，可以试一试修改dns和tun

1.18可以在mixin里配置dns,tun和出口网卡了，nice。
但是在mixin里配置了tun，那配置界面里的启用tun打勾就会失效了，建议在界面上启用tun时可以附加个手动指定网卡的配置

**Comment by WoChen5770** [comment]
> 只需要指定网卡的配置？ 或每个配置文件独立设置mixin，这样繁琐但是灵活

每个配置文件独立设置mixin 感觉倒也不用。我的意思是mixin里设置了tun，那界面上tun打不打勾就都不起作用了。
另外有个需求，就是手动追加路由。目前直接改配置文件的话，更新一下订阅就覆盖了

**Comment by 2dust** [comment]
> > 只需要指定网卡的配置？ 或每个配置文件独立设置mixin，这样繁琐但是灵活
> 
> 每个配置文件独立设置mixin 感觉倒也不用。我的意思是mixin里设置了tun，那界面上tun打不打勾就都不起作用了。 另外有个需求，就是手动追加路由。目前直接改配置文件的话，更新一下订阅就覆盖了

需求请另外提issue
全局的mixin文件里面写tun确实会覆盖了每个配置tun模式的选项，这个界面和操作需要重新设计，希望大家一起提供方案

**Comment by WoChen5770** [comment]
> 

要不tun模式的配置跟配置mixin一样，给个默认配置，然后写上非专业人士不建议修改哈哈哈

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/files/9296111/clashN-test.zip

启用全局的mixin后，mixin里面有tun相关设置
如果本配置启用了tun模式，则使用mixin中的tun覆盖
如果本配置没有启用tun模式，则mixin中tun也被忽略

**Comment by WoChen5770** [comment]
> https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> 
> **启用全局的mixin后，mixin里面有tun相关设置**
> 
> 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略

测试可以

**Comment by Hreint** [comment]
> https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> 
> **启用全局的mixin后，mixin里面有tun相关设置**
> 
> 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略

有个问题在于，目前我没找到哪里有关闭 tun 模式强制使用 meta 内核的设置，就是说要勾选启用 tun 模式，就必须添加 meta 内核，不然提示内核不存在。我目前是不勾选启用 tun 模式，但是通过 mixin 来开启 tun 模式，如果这样更新之后，这条路就被堵死了，只能修改其他内核的文件名为 meta 内核的文件名欺骗 clashN，让它以为 meta 存在。

**Comment by Hreint** [comment]
> > https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> > **启用全局的mixin后，mixin里面有tun相关设置**
> > 
> > 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> > 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略
> 
> 有个问题在于，目前我没找到哪里有关闭 tun 模式强制使用 meta 内核的设置，就是说要勾选启用 tun 模式，就必须添加 meta 内核，不然提示内核不存在。我目前是不勾选启用 tun 模式，但是通过 mixin 来开启 tun 模式，如果这样更新之后，这条路就被堵死了，只能修改其他内核的文件名为 meta 内核的文件名欺骗 clashN，让它以为 meta 存在。

clashN 的 tun 模式还有另外一个问题，在开启 tun 模式的情况下，在编辑配置文件之后（该情况不一定会出现下述错误，但短时间内连续编辑一次以上配置文件，就极大概率会出现），或者切换到另一个配置文件后（是切换配置文件，不是切换同一个配置文件的不同节点），大概率会出现一个错误：
Start Tun interface error: error creating interface: Cannot create a file when that file already exists.

此时 tun 模式实际上开启失败。

**Comment by Hreint** [comment]
> https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> 
> **启用全局的mixin后，mixin里面有tun相关设置**
> 
> 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略

clashN 的 tun 模式还有另外一个问题，在开启 tun 模式的情况下，在编辑配置文件之后（该情况不一定会出现下述错误，但短时间内连续编辑一次以上配置文件，就极大概率会出现），或者切换到另一个配置文件后（是切换配置文件，不是切换同一个配置文件的不同节点），大概率会出现一个错误：
Start Tun interface error: error creating interface: Cannot create a file when that file already exists.

此时 tun 模式实际上开启失败。

**Comment by Hreint** [comment]
> 里面的关键点应该是我把clashN里tun默认的 `auto-detect-interface: true`去掉了,自行指定了网卡

很奇怪，我像你一样去掉了 `auto-detect-interface: true`，然后指定了网卡，meta 内核还是开启 tun 模式失败，clash premium 内核就无论是 auto-detect-interface 还是自行指定，tun 模式都没问题

**Comment by WoChen5770** [comment]
> > 里面的关键点应该是我把clashN里tun默认的 `auto-detect-interface: true`去掉了,自行指定了网卡
> 
> 很奇怪，我像你一样去掉了 `auto-detect-interface: true`，然后指定了网卡，meta 内核还是开启 tun 模式失败，clash premium 内核就无论是 auto-detect-interface 还是自行指定，tun 模式都没问题

你可以去meta那里自行下载其他的版本，我用的就是 Clash.Meta-windows-amd64-compatible.exe，不是clashN里自带的那个

**Comment by Hreint** [comment]
> 载其他的版本，我用的就是 Clash.Meta-windows-amd64-compatible.exe，不是clashN里自带

原来是这样，感谢

**Comment by 2dust** [comment]
> > https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> > **启用全局的mixin后，mixin里面有tun相关设置**
> > 
> > 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> > 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略
> 
> 有个问题在于，目前我没找到哪里有关闭 tun 模式强制使用 meta 内核的设置，就是说要勾选启用 tun 模式，就必须添加 meta 内核，不然提示内核不存在。我目前是不勾选启用 tun 模式，但是通过 mixin 来开启 tun 模式，如果这样更新之后，这条路就被堵死了，只能修改其他内核的文件名为 meta 内核的文件名欺骗 clashN，让它以为 meta 存在。

https://github.com/2dust/clashN/releases/tag/1.20

**Comment by 2dust** [comment]
> > https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> > **启用全局的mixin后，mixin里面有tun相关设置**
> > 
> > 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> > 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略
> 
> clashN 的 tun 模式还有另外一个问题，在开启 tun 模式的情况下，在编辑配置文件之后（该情况不一定会出现下述错误，但短时间内连续编辑一次以上配置文件，就极大概率会出现），或者切换到另一个配置文件后（是切换配置文件，不是切换同一个配置文件的不同节点），大概率会出现一个错误： Start Tun interface error: error creating interface: Cannot create a file when that file already exists.
> 
> 此时 tun 模式实际上开启失败。

https://github.com/2dust/clashN/releases/tag/1.20
测试反馈

**Comment by Hreint** [comment]
> > > https://github.com/2dust/clashN/files/9296111/clashN-test.zip
> > > **启用全局的mixin后，mixin里面有tun相关设置**
> > > 
> > > 1. 如果本配置启用了tun模式，则使用mixin中的tun覆盖
> > > 2. 如果本配置没有启用tun模式，则mixin中tun也被忽略
> > 
> > 
> > clashN 的 tun 模式还有另外一个问题，在开启 tun 模式的情况下，在编辑配置文件之后（该情况不一定会出现下述错误，但短时间内连续编辑一次以上配置文件，就极大概率会出现），或者切换到另一个配置文件后（是切换配置文件，不是切换同一个配置文件的不同节点），大概率会出现一个错误： Start Tun interface error: error creating interface: Cannot create a file when that file already exists.
> > 此时 tun 模式实际上开启失败。
> 
> https://github.com/2dust/clashN/releases/tag/1.20 测试反馈

经测试，这两个问题都已解决，感谢！！！
