### ISSUE TITLE
感谢作者的辛苦开发！特意来发个帖子感谢一下！

### ISSUE THREAD

**Issue by Jimmy20220531** [2dust/clashN#83]
特别是在路由规则方面和v2rayN一样可以自主更新Geo Files，这点特别好。
因为机场订阅链接自带的规则实在不敢恭维。
再次感谢作者，希望能够继续完善这个软件。
感谢！感谢！感谢！
此致，敬礼！
Respect！！！

**Comment by Jimmy20220531** [comment]
想问一下作者：【规则模式】里的【规则】和【不变（随原配置）】这两个选项，其中【规则】指的是clashN的PAC规则对吧？另一个【不变（随原配置）】指的是机场订阅的PAC规则对吧？

**Comment by Jimmy20220531** [comment]
@2dust

**Comment by 2dust** [comment]
> 想问一下作者：【规则模式】里的【规则】和【不变（随原配置）】这两个选项，其中【规则】指的是clashN的PAC规则对吧？另一个【不变（随原配置）】指的是机场订阅的PAC规则对吧？

是指配置文件里面的规则，差不多就是你理解的意思
