### ISSUE TITLE
请问，前天使用了clashN后，今天发现v2rayN没法正常使用了。

### ISSUE THREAD

**Issue by Jimmy20220531** [2dust/clashN#84]
在【清除系统代理】并退出clashN后，再启动v2rayN并选择【自动配置系统代理】，发现v2rayN没法翻墙了，所有添加的机场订阅只能正常更新但无法完成【真连延迟测试】，不知道是什么回事？
系统唯一的更改是：昨天第一次启动clashN时提示需要Microsoft .NET Runtime，然后就装了一个windowsdesktop-runtime-6.0.7-win-x64，其他的什么都没变。
@2dust

**Comment by Jimmy20220531** [comment]
22/08/01 10:31:43 [Warning] [2343432690] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp [2606:4700:3031::6815:3542]:10086: i/o timeout] > common/retry: all retry attempts failed
2022/08/01 10:31:43 [Warning] [2343432690] proxy/http: failed to read response from [2001:b28:f23f:f005::a]:80 > io: read/write on closed pipe

**Comment by Jimmy20220531** [comment]
2022/08/01 10:29:33 [Warning] [699628447] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [dial tcp [2606:4700:3031::6815:3542]:10086: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2022/08/01 10:29:35 [Warning] [1555944694] app/proxyman/inbound: connection ends > proxy/http: malformed proxy host: 2001:b28:f23f:f005::a:443 > address 2001:b28:f23f:f005::a:443: too many colons in address
2022/08/01 10:29:35 127.0.0.1:1746 accepted http://91.108.56.184:80/api [proxy]
2022/08/01 10:29:35 127.0.0.1:1747 accepted http://[2001:b28:f23f:f005::a]:80/api [proxy]
2022/08/01 10:29:35 127.0.0.1:1744 accepted //91.108.56.184:443 [proxy]

**Comment by Jimmy20220531** [comment]
请问大佬，有没有clashN的电报群呀？

**Comment by Jimmy20220531** [comment]
刚刚把5.29版本的v2rayN彻底删除了，然后换成了5.31版本的v2rayN，发现又可以和clashN兼容了，奇怪，奇怪。

**Comment by 2dust** [comment]
应该不是v2rayN版本问题
看你前面的log，是节点无法连接
