### ISSUE TITLE
订阅转换clash meta内核配置文件解析报错

### ISSUE THREAD

**Issue by Ghost-yc** [2dust/clashN#85]
使用订阅转换功能时选择clash meta内核启动服务会报配置文件解析错误如下：
time="2022-08-01T15:25:35+08:00" level=fatal msg="Parse config error: rules[9779] [MATCH,,🐟 漏网之鱼,dns-failed] error: proxy [] not found"

**Comment by 2dust** [comment]
设置中，订阅转换网址选中第二个试一试
如果不行可以找一个其他的订阅转换服务填入

**Comment by 2dust** [comment]
如果您使用订阅转换是第一个服务网址，在转换出来的rule部分有点问题，会导致Meta core加载失败
解决办法：
1.在设置中把订阅转换网址换成第二个
2.或使用clash core
