### ISSUE TITLE
关于软件界面的几个图文并茂建议，大佬有空可以看看。

### ISSUE THREAD

**Issue by Jimmy20220531** [2dust/clashN#86]
![微信截图_20220802090730](https://user-images.githubusercontent.com/106609389/182272170-40b5ac03-8796-4d78-ba9a-fbbc07178551.png)

![微信截图_20220802091148](https://user-images.githubusercontent.com/106609389/182272212-59d1c876-8e1e-4ea4-af7e-a21c38616237.png)

![微信截图_20220802091354](https://user-images.githubusercontent.com/106609389/182272228-3471b5ac-eafd-45a4-ae52-0c5f9b0295f1.png)

![微信截图_20220802092313](https://user-images.githubusercontent.com/106609389/182272255-853c51d2-ca4e-41af-aea7-31b1e31f7911.png)

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.17
当前代理界面做了调整
规则文字不变
