### ISSUE TITLE
1.17版本的【移除Geo文件自动更新和手动更新功能】，Geo文件都没有了，那【规则模式】中的【规则】还管用吗？

### ISSUE THREAD

**Issue by Jimmy20220531** [2dust/clashN#88]
大佬，1.17版本中“移除Geo文件自动更新和手动更新功能”。
那么使用1.17版本clashN的时候，Geo文件都没有了，那【规则模式】中的【规则】还管用吗？

**Comment by Jimmy20220531** [comment]
还有个问题，大佬，检查更新——【更新 Core】和【更新 Meta Core】的时候产生的.zip_temp文件可以手动删除吗？

**Comment by 2dust** [comment]
> 

Geo文件没有了，只影响Meta-core的Geo规则，Meta-core启动的时候会自动下载；

**Comment by 2dust** [comment]
> 还有个问题，大佬，检查更新——【更新 Core】和【更新 Meta Core】的时候产生的.zip_temp文件可以手动删除吗？

可以手动删除，下次更新把临时文件清理下

**Comment by Jimmy20220531** [comment]
谢谢大佬
