### ISSUE TITLE
全局模式仍然走的是规则模式

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#89]
版本：v1.17
内核：Clash Core v1.11.4
订阅规则：ACL4SSR_Online 默认版

在Clahs for Windows里面，将模式切换为Global之后，则所有流量都通过远程代理节点访问，是无视订阅的规则的。而ClashN里面，切换为全局模式之后，仍然还是走订阅的规则的。

以微软的onedrive.live.com为例，之前都是可以直连的，订阅里面也将微软服务定义为直连，但是最近无法直连了。用Clash for Window中开启全局模式，可以正常访问，而在ClashN里面开启全局模式则不行，给的日志如下：
time="2022-08-07T11:06:05+08:00" level=info msg="[TCP] 127.0.0.1:7313 --> onedrive.live.com:443 match DomainSuffix(live.com) using Ⓜ️ 微软服务[DIRECT]"

**Comment by 2dust** [comment]
暂时这样：切换到Global后点击一次重启服务
等修复

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.18
