### ISSUE TITLE
1.2版，“设为活动配置文件” 信息框出现“生成默认配置文件失败”

### ISSUE THREAD

**Issue by fyhzc** [2dust/clashN#9]
生成默认配置文件失败
启动服务(2022/4/5 1:15:10)...
配置成功
zj-clash
启动服务(2022/4/5 1:15:10)...

生成默认配置文件失败
time="2022-04-05T01:15:11+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T01:15:11+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T01:15:11+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T01:15:11+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T01:15:11+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2022-04-05T01:15:11+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"

**Comment by 2dust** [comment]
请问提示 生成默认配置文件失败 后，此配置文件能正常启动吗？

**Comment by fyhzc** [comment]
能正常启动，就是点”设为活动配置文件“就会出现上面的错误提示

**Comment by fyhzc** [comment]
点一次就出现一次，每次点每次都出现

**Comment by fyhzc** [comment]
配置成功
zjr13808836946-clash-v2ray_t_clash
配置成功
zjr13808836946-clash-v2ray_t_clash
生成默认配置文件失败
生成默认配置文件失败
启动服务(2022/4/5 20:24:32)...
Cannot access a disposed object.
Object name: 'Process'.
启动服务(2022/4/5 20:24:32)...
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T20:24:32+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T20:24:32+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T20:24:32+08:00" level=error msg="External controller listen error: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2022-04-05T20:24:33+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
time="2022-04-05T20:24:33+08:00" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:1081: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2022-04-05T20:24:33+08:00" level=error msg="Start SOCKS server error: listen tcp 127.0.0.1:1080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2022-04-05T20:24:33+08:00" level=warning msg="[CacheFile] can't open cache file: timeout"
time="2022-04-05T20:24:33+08:00" level=error msg="Start HTTP server error: listen tcp 127.0.0.1:1081: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
time="2022-04-05T20:24:33+08:00" level=error msg="Start SOCKS server error: listen tcp 127.0.0.1:1080: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

**Comment by fyhzc** [comment]
声明在主界面中我的订阅源有20个左右。
我的过程如下 ：
打开clashN
点：检查更新”----里面的选项从上到下更新一遍（都正常）
在选中的服务器上点”设为活动配置文件“，正常
再在“配置文件”中选“更新订阅（通过代理），主界面在机率 出现卡住和乱码的情况
这时在选中的服务器上点“设为活动配置文件” 信息框出现“生成默认配置文件失败”
只要发生一次，在不关闭软件的情况下，就会循环再现。
关了软件 ，再打开，重复上面操作。又是一样的错误出现

**Comment by 2dust** [comment]
找到guiLogs文件夹中今天的日志文件，发下出来。
应该是出现异常了

**Comment by fyhzc** [comment]
里面没啥啊：
旧的（里面两个文件2022-04-04.txt和2022-04-05.txt）
2022-04-04
2022-04-04 22:13:24,916 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-04 22:31:26,582 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-04 23:18:29,174 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe

2022-04-05
2022-04-05 08:39:00,174 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 11:14:44,945 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:30:04,157 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:32:37,006 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:39:37,078 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 20:16:46,432 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 20:19:43,253 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe

**Comment by fyhzc** [comment]
你发新文件复盖后
（里面两个文件2022-04-04.txt和2022-04-05.txt）
2022-04-04.txt
2022-04-04 22:13:24,916 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-04 22:31:26,582 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-04 23:18:29,174 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe


2022-04-05.txt
2022-04-05 08:39:00,174 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 11:14:44,945 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:30:04,157 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:32:37,006 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 13:39:37,078 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 20:16:46,432 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/04 | D:\Portable\gfw\clashN\clashN.exe
2022-04-05 20:18:22,675 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/05 | D:\Portable\clashN\clashN.exe
2022-04-05 20:21:55,999 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/05 | D:\Portable\clashN\clashN.exe
2022-04-05 20:46:05,150 [1] INFO  Log1 - clashN start up | clashN - V1.2 - 2022/04/05 | D:\Portable\clashN\clashN.exe

**Comment by fyhzc** [comment]
复盖新你发的文件后，
我又走了一遍过程。出现 错误

配置成功
zjr13808836946-clash-v2ray_t_clash
生成默认配置文件失败
启动服务(2022/4/5 20:58:46)...
time="2022-04-05T20:58:46+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T20:58:46+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T20:58:46+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T20:58:46+08:00" level=info msg="Start initial compatible provider 🚀 节点选择"
time="2022-04-05T20:58:46+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T20:58:46+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-04-05T20:58:46+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:1081"
time="2022-04-05T20:58:46+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:1080"
time="2022-04-05T20:58:52+08:00" level=info msg="[TCP] 127.0.0.1:53501 --> alive.github.com:443 match DomainKeyword(github) using 🚀 节点选择[🇸🇬 一键连广移>>新103.157.250.22 2]"
time="2022-04-05T20:58:53+08:00" level=info msg="[TCP] 127.0.0.1:53504 --> rr3---sn-i3belney.googlevideo.com:443 match DomainSuffix(googlevideo.com) using 🚀 节点选择[🇸🇬 一键连广移>>新103.157.250.22 2]"

**Comment by fyhzc** [comment]
刚试了下本地yaml配置导入，导入成功后。用着正常。可在这个配置上点“设为活动配置文件” 信息框出现“生成默认配置文件失败


配置成功
clash_local_file
生成默认配置文件失败
启动服务(2022/4/5 21:10:43)...
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🎥 NETFLIX"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider ⛔️ 广告拦截"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🚫 运营劫持"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2022-04-05T21:10:44+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-04-05T21:10:44+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-04-05T21:10:44+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:1081"
time="2022-04-05T21:10:44+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:1080"
time="2022-04-05T21:10:47+08:00" level=info msg="[TCP] 127.0.0.1:53881 --> alive.github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:52+08:00" level=info msg="[TCP] 127.0.0.1:53883 --> rr3---sn-i3belney.googlevideo.com:443 match DomainSuffix(googlevideo.com) using 🌍 国外媒体[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:53+08:00" level=info msg="[TCP] 127.0.0.1:53885 --> github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:54+08:00" level=info msg="[TCP] 127.0.0.1:53888 --> github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:55+08:00" level=info msg="[TCP] 127.0.0.1:53890 --> avatars.githubusercontent.com:443 match DomainSuffix(githubusercontent.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:55+08:00" level=info msg="[TCP] 127.0.0.1:53892 --> github.githubassets.com:443 match Match() using 🐟 漏网之鱼[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:56+08:00" level=info msg="[TCP] 127.0.0.1:53895 --> alive.github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:10:56+08:00" level=info msg="[TCP] 127.0.0.1:53897 --> collector.github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:11:11+08:00" level=info msg="[TCP] 127.0.0.1:53899 --> rr3---sn-i3belney.googlevideo.com:443 match DomainSuffix(googlevideo.com) using 🌍 国外媒体[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:11:12+08:00" level=info msg="[TCP] 127.0.0.1:53901 --> www.youtube.com:443 match DomainSuffix(youtube.com) using 🌍 国外媒体[🇯🇵日本(绿头外网集团)(Public) 2]"
time="2022-04-05T21:13:01+08:00" level=info msg="[TCP] 127.0.0.1:53904 --> github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇯🇵日本(绿头外网集团)(Public) 2]"

**Comment by fyhzc** [comment]
配置成功
clash_local_file
启动服务(2022/4/5 21:16:23)...
生成默认配置文件失败
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🎯 全球直连"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🔰 节点选择"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🛑 全球拦截"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 📲 电报信息"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🎥 NETFLIX"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🌏 国内媒体"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🚫 运营劫持"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider ♻️ 自动选择"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🐟 漏网之鱼"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider ⛔️ 广告拦截"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🍎 苹果服务"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
time="2022-04-05T21:16:23+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软服务"
time="2022-04-05T21:16:23+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-04-05T21:16:23+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:1081"
time="2022-04-05T21:16:23+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:1080"
time="2022-04-05T21:16:24+08:00" level=info msg="[TCP] 127.0.0.1:54027 --> rr3---sn-i3belney.googlevideo.com:443 match DomainSuffix(googlevideo.com) using 🌍 国外媒体[🇭🇰香港(绿头外网集团)(Public)]"
time="2022-04-05T21:16:26+08:00" level=info msg="[TCP] 127.0.0.1:54016 --> rr3---sn-i3belney.googlevideo.com:443 match DomainSuffix(googlevideo.com) using 🌍 国外媒体[🇭🇰香港(绿头外网集团)(Public)]"
time="2022-04-05T21:16:27+08:00" level=info msg="[TCP] 127.0.0.1:54041 --> alive.github.com:443 match DomainSuffix(github.com) using 🔰 节点选择[🇭🇰香港(绿头外网集团)(Public)]"
time="2022-04-05T21:16:32+08:00" level=info msg="[TCP] 127.0.0.1:54043 --> www.youtube.com:443 match DomainSuffix(youtube.com) using 🌍 国外媒体[🇭🇰香港(绿头外网集团)(Public)]"

**Comment by 2dust** [comment]
能否把您的所有配置发email，我们看下是否能重现？
目前在测试环境无法重现
captainIronng@protonmail.com

**Comment by fyhzc** [comment]
俺配置已发。

2dust ***@***.***> 于2022年4月6日周三 20:30写道：

**Comment by fyhzc** [comment]
要不要我把整个软件打包邮给你。打包时会把两个core删了。

**Comment by 2dust** [comment]
还是无法复现，请使用下面这个包使用，然后出现问题后把日志发下（增加了详细异常）
[clashN.zip](https://github.com/2dust/clashN/files/8427066/clashN.zip)

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.3
请使用此版本
