### ISSUE TITLE
自动更新订阅之后，“更新时间”并不发生变化

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#91]
版本：v1.17
内核：Clash Core v1.11.4
订阅规则：ACL4SSR_Online 默认版

如题，自动更新之后，在配置文件tab的“更新时间”这一列，其中的时间不会发生变化。将clashN退出之后，重新启动，可以看到这个地方的数值更新成最近一次的更新时间了。

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.18
