### ISSUE TITLE
切换为全局模式之后，油管无法访问

### ISSUE THREAD

**Issue by none2003** [2dust/clashN#92]
版本：v1.18
内核：Clash Core v1.11.4
订阅规则：ACL4SSR_Online 默认版

先设置为规则模式，油管可以正常访问，点任务栏图标切换为全局模式，发现油管可以正常访问，但是走的是规则模式：
time="2022-08-09T10:53:56+08:00" level=info msg="[TCP] 127.0.0.1:9230 --> youtube.com:443 match DomainKeyword(youtube) using 🌍 国外媒体[XXXXXXX]"
time="2022-08-09T10:53:57+08:00" level=info msg="[TCP] 127.0.0.1:9240 --> www.youtube.com:443 match DomainKeyword(youtube) using 🌍 国外媒体[XXXXXXX]"

这时保持在全局模式下，重启服务，发现油管不能访问了，并给了下面的报错：
time="2022-08-09T10:32:15+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: never touched"

切换到规则模式，发现油管仍然不能访问，感觉仍然停留在全局模式：
time="2022-08-09T10:58:23+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: never touched"
time="2022-08-09T10:58:24+08:00" level=warning msg="[TCP] dial GLOBAL to 0.1.0.1:1001 error: dial tcp4 0.1.0.1:1001: connectex: A socket operation was attempted to an unreachable network."
time="2022-08-09T10:58:28+08:00" level=warning msg="[TCP] dial GLOBAL to www.youtube.com:443 error: never touched"
time="2022-08-09T10:58:28+08:00" level=info msg="[TCP] 127.0.0.1:10586 --> www.youtube.com:443 using GLOBAL"

重启服务之后，发现油管可以正常访问了：
time="2022-08-09T10:59:32+08:00" level=info msg="[TCP] 127.0.0.1:10899 --> www.youtube.com:443 match DomainKeyword(youtube) using 🌍 国外媒体[XXXXXXX]"

**Comment by 2dust** [comment]
等修复

**Comment by 2dust** [comment]
[clashN-test.zip](https://github.com/2dust/clashN/files/9296111/clashN-test.zip)

模式切换已经修复
全局模式下报错的这个需要提交log给core那边

**Comment by none2003** [comment]
> [clashN-test.zip](https://github.com/2dust/clashN/files/9296111/clashN-test.zip)
> 
> 模式切换已经修复 全局模式下报错的这个需要提交log给core那边

1.19里面模式切换确实好了。

全局模式报错的问题是否换为clash premium core就好了？

**Comment by 2dust** [comment]
> > [clashN-test.zip](https://github.com/2dust/clashN/files/9296111/clashN-test.zip)
> > 模式切换已经修复 全局模式下报错的这个需要提交log给core那边
> 
> 1.19里面模式切换确实好了。
> 
> 全局模式报错的问题是否换为clash premium core就好了？

切换p core不一定行，建议把log提交给core那边
