### ISSUE TITLE
报个问题：初始化时下载不了geoip.mmdb

### ISSUE THREAD

**Issue by easythd** [2dust/clashN#94]
今天突然打不开clashN了，打开后没有代理服务器，更新订阅成功，也有本地文件了，但无法装载出来代理服务器，点重启服务按钮就闪退了，在配置订阅那里按回车也会闪退，查guiLogs报错日志是说远程服务器拒绝连接。

后来重新配置订阅，删除配置文件重打开，发现消息窗口里提示的是没有mmdb，但无法下载“https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb”
检查了一下，是我这边环境中ghproxy.com被污染了，本地电信dns给的ip无法访问，如果用114或8.8.8.8等dns服务器，响应居然是127.0.0.1。
但我找了所有参数设置和配置文件，都没有这个文件下载地址的配置，也不知道这个文件应该放哪里？
最后，只能开了一个v2rayN，加了个节点，然后用proxifier强制clashN去使用v2rayN，这样终于正常下载了mmdb,工作正常了。。。
折腾了将近1小时。。。

这个要有个办法吧？能修改geoip.mmdb下载地址？再加上明确存放位置，可以自己单独下载放进去？
或还是什么方法？不太懂。

@2dust

**Comment by 2dust** [comment]
默认在 C:\Users\用户名\.config\clash

或可以启用便携模式，在clashN目录下面建立一个文件夹data，重启 https://github.com/2dust/clashN/issues/26

**Comment by easythd** [comment]
怎么弄便携模式会 了，但这个不可以在参数配置里有明确的选项么？

另外，更重要的是，如果是新环境，就卡在这里了，根本无法下载mmdb，完全无法用，怎么办？要求再下个v2rayN来弄？

**Comment by 2dust** [comment]
> 怎么弄便携模式会 了，但这个不可以在参数配置里有明确的选项么？
> 
> 另外，更重要的是，如果是新环境，就卡在这里了，根本无法下载mmdb，完全无法用，怎么办？要求再下个v2rayN来弄？

可以在发布包里面直接加上data文件夹和db，默认就启用，需要看后面的反馈

**Comment by easythd** [comment]
建议默认就带着，能上网了自动更新

2dust ***@***.***> 于 2022年8月21日周日 20:19写道：

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/1.21
