### ISSUE TITLE
希望大佬增加查看剩余流量的功能

### ISSUE THREAD

**Issue by 332sdasf** [2dust/clashN#97]
有些机场不会给你下图显示剩余流量的节点
![image](https://user-images.githubusercontent.com/70708328/185795063-b0102b5b-da0e-4dad-ac88-db8ea84d0058.png)
所以个人觉得CFW里面的查看剩余流量功能（如图）很不错，
![image](https://user-images.githubusercontent.com/70708328/185794965-f2757f9c-1d87-49c3-88ee-2d49b7d04fc3.png)
不用跑到机场网站里面看，希望大佬增加查看剩余流量的功能

**Comment by 2dust** [comment]
暂时还未有精力处理

**Comment by 2dust** [comment]
https://github.com/2dust/clashN/releases/tag/2.1
