### ISSUE TITLE
几点小问题

### ISSUE THREAD

**Issue by Syzygy33** [2dust/clashN#98]
感谢大佬 内置转换非常方便 但有几个问题 1.以管理员运行时 开机不能自启动 2.meta运行tun模式时直接闪退 3.软件边框大小调完打开又恢复默认大小

**Comment by 2dust** [comment]
1. 正在想办法
2. 请另外开issue提交详情
3. 这个正常退出时可以记忆，暂时忽略

**Comment by Syzygy33** [comment]
2.已解决 不在闪退
3.是完全退出再打开或者重启开机时 窗口大小无法记忆

**Comment by Syzygy33** [comment]
1.关于开启管理员无法开机启动后 可以通过添加任务计划解决 亲测可用 说明教程如下
https://blog.csdn.net/weixin_45330449/article/details/105778391

**Comment by 2dust** [comment]
有需要的请自己使用任务计划解决
任务计划也可以用c#代码实现，等有时间添加上去

**Comment by Rashhz** [comment]
大佬，现在出现了一个新问题，用这种方式开机启动tun，会提示“Start TUN listening error: setting interface address and routing failed: unable to set routes: Element not found."”clashN没有启动。手动点击左上角按钮后能恢复。

**Comment by 2dust** [comment]
> 大佬，现在出现了一个新问题，用这种方式开机启动tun，会提示“Start TUN listening error: setting interface address and routing failed: unable to set routes: Element not found."”clashN没有启动。手动点击左上角按钮后能恢复。

每次都这样吗？

**Comment by Rashhz** [comment]
> > 大佬，现在出现了一个新问题，用这种方式开机启动tun，会提示“Start TUN listening error: setting interface address and routing failed: unable to set routes: Element not found."”clashN没有启动。手动点击左上角按钮后能恢复。
> 
> 每次都这样吗？


是的，每次开机都会这样。

**Comment by 2dust** [comment]
> > > 大佬，现在出现了一个新问题，用这种方式开机启动tun，会提示“Start TUN listening error: setting interface address and routing failed: unable to set routes: Element not found."”clashN没有启动。手动点击左上角按钮后能恢复。
> > 
> > 
> > 每次都这样吗？
> 
> 是的，每次开机都会这样。系统是win11/10.0.22621

请新开issue，提交详情。
比如core类型，配置文件可以提交到邮箱 captainIronng@protonmail.com
